### ISSUE TITLE
Auto fill-and-submit leads to hang

### ISSUE THREAD

**Issue by hwine** [passff/passff#122]
If "auto fill" and "auto submit" are both checked, AND the "first" password found is not the correct one for the site, the page reloads, and an infinite loop is created. In FF 45 Dev Edition I had to force quit app on Mac.

I ran into this issue with AWS login, which uses the main amazon.com login, and I have (different) kindle credential there in the same password-store instance.

Disabling the auto fill & auto submit checkboxes allowed everything to work correctly.

**Comment by jvenant** [comment]
could you provide me the url you use to login

**Comment by hwine** [comment]
Browser navigation (new private window): https://aws.amazon.com -> "My Account" -> "Account Settings" puts me at:
  https://www.amazon.com/ap/signin?openid.assoc_handle=aws&openid.return_to=https%3A%2F%2Fsignin.aws.amazon.com%2Foauth%3Fresponse_type%3Dcode%26client_id%3Darn%253Aaws%253Aiam%253A%253A934814114565%253Auser%252Fportal-aws-auth%26redirect_uri%3Dhttps%253A%252F%252Fconsole.aws.amazon.com%252Fbilling%252Fhome%253Fstate%253DhashArgs%252523%25252Faccount%2526isauthcode%253Dtrue%26noAuthCookie%3Dtrue&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&action=&disableCorpSignUp=&clientContext=&marketPlaceId=&poolName=&authCookies=&pageId=aws.ssop&siteState=pre-register%2Cen_US&accountStatusPolicy=P1&sso=&openid.pape.preferred_auth_policies=MultifactorPhysical&openid.pape.max_auth_age=120&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&server=%2Fap%2Fsignin%3Fie%3DUTF8&accountPoolAlias=&forceMobileApp=0&language=en_US&forceMobileLayout=0

**Comment by oneirosFade** [comment]
While the RegEx solution in the referencing issue might be a nice addition on its own, it occurs to me that this issue would also be a problem if the user has stored an outdated or otherwise incorrect password in their store, leading to repeated failed logins (and possibly an easy account lockout, depending on the service).

Maybe the number of consecutive login attempts should be tracked somehow and auto-submit temporarily disabled if this number exceeds a maximum (either hardcoded or set in preferences)?

**Comment by jvenant** [comment]
We already have this kind of safeguard in the plugin.
But obviously, it doesn't seems to work on this specific case.
The current safeguard is url based. So if for any reason the url change on each submit, it could explain the behaviour

**Comment by gutierri** [comment]
I confirm this problem.

I think maybe the auto-fill function should be better. Without an agent, it is an option that can be disabled or passwords are not available as well (via pass).

CC @nwallace
