### ISSUE TITLE
Support multiple password stores

### ISSUE THREAD

**Issue by hwine** [passff/passff#123]
I have 2 separate password stores - one for work & one for personal use. It would be nice to allow both to be configured, and have a run time selection of which to use.

I currently switch by using a different wrapper script for each password store, which sets the environment variable PASSWORD_STORE_DIR before invoking 'pass'. So, I can "work around" by just tweaking the config to launch a different script.

I also use QtPass -- they have a notion of "profiles" which addresses the same issue. Choosing a drop down is easier than editing the config. :)

**Comment by tuxor1337** [comment]
@hwine There is an option in the preferences to change the `PASSWORD_STORE_DIR`. If that's too clumsy for your usecase, would you please suggest a better way how to integrate your desired functionality into the existing user interface?

**Comment by hwine** [comment]
@tuxor1337 - thanks for reviving this issue.
- a "good" way would be to allow saving & naming `PASSWORD_STORE_DIR` values, so switching only involves clicking, not typing. Let's call that "context selection"
- an "even better" way would be to tie automatic  context selection to URL's and/or [containers](https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers)

Personally, since there is no longer support for macos, I don't have interest in this bug.

**Comment by tuxor1337** [comment]
How exactly would you integrate the switching of `PASSWORD_STORE_DIR` into the existing UI? Once that's settled, it should be easy to implement. Didn't know about containers, sounds interesting for sure.

Who said there's no support for Mac? This is an anarchic open source project, so... no support for anything, I'd say ;-) Once some contributor with a Mac machine stumbles upon this, we might have a working Mac version in no time. Nobody is stopping you from contributing the missing parts 👍

**Comment by hwine** [comment]
Long ago, when I opened this issue, `passff` worked on mac and could easily be installed. The current extension is not marked as installable on the mac (in Firefox on the addons site). [I edited my comment to be clearer about that.]

**Comment by tuxor1337** [comment]
Closing this since no active user seems to be interested in such a feature.
