### ISSUE TITLE
Login/password input field names should accept wildcards

### ISSUE THREAD

**Issue by rightaway** [passff/passff#135]
In the login/password input field names, would be good to accept wildcards. For example `*username*`, so that any input field containing `username` within it would match. This would be useful because many websites still don't use 'standard' names for those input fields, or they auto-generate those fields with a name like `username-field0122`.

**Comment by jvenant** [comment]
Currently, the test is
```javascript
    if (fieldName.indexOf(goodFieldNames[i].toLowerCase()) !== -1)
```
So actually, it should work.

**Comment by rightaway** [comment]
Thanks. It's strange, could you please see why it doesn't seem to be auto-filling on a site like https://www.equabanking.cz/IBS/, for example? According to the names of the login/password fields there, it should auto-fill but doesn't.
