### ISSUE TITLE
Intercept Form data and offer copy&paste for gpg file

### ISSUE THREAD

**Issue by novalis111** [passff/passff#138]
Hi, i have been using KeePass2 for years, but as it's really clunky under Mono, i am looking for alternatives. 

KeeFox (the FF plugin of KeePass) does a really good job when saving the relevant form fields along with their values for auto-completion. I really appreciate the KISS in pass/PassFF, but atm i am copying and renaming a lot of stuff to get my auto-fill right:
- Rename the gpg file to match the url where i have to enter login+password
- Examine the html source to add the input field name(s) to PassFF
- Edit the pass entry to add meta-data like login, url

I wouldn't like PassFF editing/renaming the pass entries, but it would be really helpful to have sth. like this generated after each (login) form submission in Firefox:

```
$ pass insert needed.url.tld

usrname: foo
pswrd: bar
```

with the option to directly add input field name(s) to PassFF preferences. Looking at the html source and copying to preferences textfield is really tedious. With the above feature it would be much easier to update the password storage and customize PassFF quickly.

I would try myself, but after looking at the source i had to realize that my firefox-plugin skills are limited ;-)

**Comment by tuxor1337** [comment]
@novalis111 Adding input field name(s) to PassFF preferences is already possible via the context menu. Would you please open a new issue with a more specific description of which functionality you're missing exactly?
