### ISSUE TITLE
MacOS: No connection to (python3) host app

### ISSUE THREAD

**Issue by drscream** [passff/passff#188]
Hello awesome `passff` Developers,

thanks a lot for providing `passff`, I currently expecting an issue with the latest `master` version which use `web_extensions` support on Firefox. For me `passff` doesn't show any content of my `password-store` located in my HOME if I run Firefox from the Dock.app or from the Finder.app.

If I run Firefox from an open Terminal.app session via the following command everything is working:

```
open -a Firefox
```

I expect some issues with the environment or variables which are missing if I run Firefox with Dock.app or Finder.app. At the moment I've no idea about the issue, but I would provide the above workaround.

Environment:
- Firefox 52.0.1 (64-bit)
- macOS 10.12.3

I use `pkgsrc` to provide `gpg2`, `pass`, `gpg-agent` and `python` to my environment. Everything is installed in `/opt/pkg/{bin,sbin,...}` expect the `passff.py` script which is located in `/usr/local/bin` - I've already modified the settings to the correct path anyway. Also my `gpg-agent` is configured to create an env file in `~/.gpg-agent-info`.

If you've any hint for debugging my issue or if you expect the same let me know.

**Comment by nwallace** [comment]
Thanks for the report! Do you know how to debug the extension? There's [some details here](https://github.com/nwallace/passff/blob/master/docs/CONTRIBUTING.md#debugging) on setting that up. Do you see anything interesting in those logs?

I've got a Macbook lying around, but I've never used `pkgsrc` before. I'll try to use that to narrow down the problem space sometime this week.

**Comment by waeltken** [comment]
I ran into the same problem.

I had to both set the location of the the pass executable to `/usr/local/bin/pass` and check the option to run the pass script within a shell.

This solved the problem for me.

**Comment by nwallace** [comment]
Do you have python3 installed and available in your shell's $PATH?

Also, have you all tried the configurations recommended on the README:

* Set "User home" to the absolute path to your home directory
* Set "Pass command" to the path to the pass binary (if installed with homebrew, the default location is /usr/local/bin/pass)
* Set "Pass shell" to your preferred shell (e.g. /bin/bash)
* Set "Shell arguments" to --login

I'm going to try to test this out tonight and see what's going on. Could be an incompatibility with the host app.

**Comment by nwallace** [comment]
I've been digging into this some more, and I'm baffled at the moment. The problem is occurring when we try to send the native message to the host app, but the host app doesn't appear to be receiving the message at all. It's blowing up in the internals of the `browser.runtime.sendNativeMessage` call before it actually sends the message. The error is completely unhelpful ("An unexpected error occurred" with no backtrace). I'll keep trying to figure this out, but I wanted to update you all in the meantime.

**Comment by phryneas** [comment]
you could try to use `runtime.connectNative()` as it should give some more feedback in the port.error field (although `browser.runtime.lastError` might also help you).

You would have to keep track of the listeners, as the postMessage has no direct callback.
Something like this might work (I did this code without checking syntax, some corrections might be necessary)

```

let port = runtime.connectNative('passff');
port.onDisconnect(function(){console.log(port.error);};

let listeners = [];
port.onMessage(function(...args){
	(listeners.shift())(...args);
});

new Promise((resolve) => {
	listeners.push(resolve);
	port.postMessage(args);
}).then((result) => {
...
})

```

**Comment by nwallace** [comment]
Yeah, thanks @phryneas. I tried using `connectNative` also, but I got the same unhelpful error.  I need another day with my wife's laptop to dig into this again

**Comment by graham1228** [comment]
I'm experiencing this same issue, has there been any progress on a code resolution or a workaround?

**Comment by tuxor1337** [comment]
@graham1228 Unfortunately, there doesn't seem to be any MacOS dev with time to look into this. I don't have a MacOS machine and don't want to stab around in the dark.

**Comment by GrippenDynamik** [comment]
> I've been digging into this some more, and I'm baffled at the moment. The problem is occurring when we try to send the native message to the host app, but the host app doesn't appear to be receiving the message at all. It's blowing up in the internals of the `browser.runtime.sendNativeMessage` call before it actually sends the message. The error is completely unhelpful ("An unexpected error occurred" with no backtrace). I'll keep trying to figure this out, but I wanted to update you all in the meantime.
> 
> **Update:** The problem seems to be related to the native app Python script. I replaced our passff.py script with the example host app from [Mozilla's example extension](https://github.com/mdn/webextensions-examples/tree/master/native-messaging), and the native messages work just fine. But when using our Python script, they fail

I encountered the same error under
- Manjaro Linux
- Firefox 79.0 (64-Bit)

My extensions's background script uses browser.runtime.sendNativeMessage() to send a string to a Python 3 script.
It catches the following exception:
Error: An unexpected error occurred

( There was no error when I instead used app/ping_pong.py from https://github.com/mdn/webextensions-examples/tree/master/native-messaging )

The console shows:
null ExtensionCommon.jsm:740
    normalizeError resource://gre/modules/ExtensionCommon.jsm:740
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:891

The problem was that my Python script didn't have an infinite while loop.
Apparently, the Python script isn't supposed to terminate by itself.
If it does, the script probably isn't running anymore when Firefox sends the native message.
