### ISSUE TITLE
Host binary is dangerous

### ISSUE THREAD

**Issue by emersion** [passff/passff#194]
The host allows any command to be executed. If there is a security issue in the addon, that would allow an attacker to do what he wants.

See https://github.com/nwallace/passff/blob/master/src/host/passff.py#L33

I've been working on browserpass. I think it would be great to define a common JSON protocol for the host to only have one binary to install and then choose between passff and browserpass.

**Comment by phryneas** [comment]
Yeah, that definitely needs some work. 
But as long as you're going to replace the gpg binary with some go pgp library I'll strongly oppose using a shared binary. There are passff users with smartcards (myself included) and that change would make not only browserpass, but also passff unusable for us.

I'm personally experimenting with lib-gpgme at the moment (also using go, the https://github.com/proglottis/gpgme go wrapper is working quite good), so if we want to go that route, would that be an idea?

**Comment by emersion** [comment]
We haven't decided anything about ditching the gpg binary, it's just an idea. Since smartcards are used by many people, if this happens we'll likely provide an option to either use Go's PGP library or the GPG binary.

If I remember well, gpgme has no real advantage over using directly the gpg binary. It expects gpg to be installed and spawns gpg itself. Plus, it uses cgo which makes cross-compilation difficult and depends on a C compiler. Though, if we implement multiple PGP backends (Go's PGP library, GPGME and GPG binary) that shouldn't be a problem (it could be enabled or disabled with a build flag for instance).

**Comment by tuxor1337** [comment]
No, it does not allow any command to be executed, see https://github.com/nwallace/passff/blob/master/src/host/passff.py#L30

**Comment by emersion** [comment]
Okay, that's not as bad as I thought. Anyway, that's still a bad practice. There are many tricks (putting a NULL char in command, sending `receivedMessage['arguments']` as a string, etc...) that don't work thanks to Python, but who knows, there might be one thing I didn't thought of that works.

Also, I don't like how the extension is able to read any file on the system (https://github.com/nwallace/passff/blob/master/src/host/passff.py#L69). It's one more time not that bad, because it reads only lines with a `=` char, but still, I can imagine someone getting a part of my private key with this technique.

**Comment by tuxor1337** [comment]
Well, there are two easy fixes for this: Remove the option in PassFF to use a user-defined path to the `.gpg-agent-info` and remove the option to use a user-defined path to the `pass` executable. Alternatively, we could add an optional external config file for the host app (e.g. in `$XDG_CONFIG_HOME`) where these things could be defined outside of PassFF.

Actually, I'm wondering how many users would be affected by such a change.

**Comment by nwallace** [comment]
Is the fundamental problem that the installed add-on might have been tampered with? Perhaps a man-in-the-middle attack during download or a rogue distribution?  If so, I wonder if concerned users could verify the installed extension via a checksum or something. Since nothing is compiled (it's just JavaScript and Python), checksums on one computer should match those on another computer, right?  Would this be an acceptable solution, or is there another problem I'm not aware of?
