### ISSUE TITLE
Some sites use variable field names

### ISSUE THREAD

**Issue by thblt** [passff/passff#198]
The [OVH customer login page](https://www.ovh.com/auth/?action=gotomanager&from=https://www.ovh.com/fr/) uses randomized field IDs, probably as a defense against brute force attacks. This is probably unsolvable wrt the basic, "passive" autofilling, but maybe the "Fill/Submit" and "Goto/Fill/Submit" methods could, in such cases, try to be more aggressive and put the username wherever they can?

Thanks,

**Comment by nwallace** [comment]
Hm. I feel like "aggressive" auto-filling would cause problems for you after you logged in, since the plugin doesn't know whether you're logged in or not. After logging in, any other fields on any pages in the site would end up getting auto-filled with your username/password.

What if, instead, you could configure your password for that site specifically to use the placeholder text instead of the element's name attribute? That would solve this problem, right?

**Comment by thblt** [comment]
Nathan Wallace writes:

> Hm. I feel like "aggressive" auto-filling would cause problems for you
> after you logged in, since the plugin doesn't know whether you're
> logged in or not.

My suggestion was to restrict the "agressive" approach to the "Fill", "Fill and Submit", "Goto, Fill and Submit" functions, *not* autofilling.  That is, when passff gets *explicitely* asked to fill in a form, if there are fields in the pass records it hasn't been able to include, and inputs in the page it hasn't been able to fill, it should match them.

> What if, instead, you could configure your password for that site
> specifically to use the placeholder text instead of the element's name
> attribute?

That would indeed be an elegant solution, but wouldn't that require
some deep changes in pass?

**Comment by nwallace** [comment]
@thblt Indeed it would require some significant changes. I've started to work on this, though, since I think this is really important. Turns out someone brought this up years ago on #61, so let's move the conversation there.

**Comment by thblt** [comment]
I'm not sure this is a duplicate of #61.  Just to clarify: the issue with OVH Customer login page is  that the field names are unusual *and* not constant: they seem to be five hex-encoded random bytes (or more probably the result of some cryptographic operation with a random session id). IIUC, the point of #61 is handling unusual, but constant, field names.

**Comment by nwallace** [comment]
@thblt You're right -- this isn't the same as #61. Reopening!

**Comment by gutierri** [comment]
@thblt @nwallace For the password, we can find the field by type (password). Now the username is a bit difficult. An unsightly solution is to try to match some pattern (with keywords: username, email, user).

**Comment by madduck** [comment]
Maybe there's another indication we can use, or a combination of hints, such as "the input field just before the password field", or maybe a match using DOM-specifics could work?

Btw, this issue isn't just on the OVH pages. Almost every banks and most security-conscious websites randomise the field names precisely to prevent bots from wreaking havoc. Now, of course, PassFF is acting a bit like a bot, but there is a human behind it…

Couldn't PassFF ask its human to select the field if it can't identify it, and then store this information for the page somehow?

**Comment by tuxor1337** [comment]
If a web page is purposely obfuscating the DOM location of the relevant input fields, we are taking up an endless fight if we try to detect the input fields against the will of that web page. There already is the possibility to right click into the field and tell PassFF to fill in this field. I don't think it's worth the afford to go any further...

**Comment by thblt** [comment]
@gutierrii @madduck : For OVH specifically, the placeholder text ("Account ID or email address") may also help.   Or even look for `input type="text"`, there's only one.

@tuxor1337: I think it's still trivial to identify the correct field within the page, there is no actual DOM obfuscation. I think the point is to make it harder to bruteforce credentials rather than prevent password managers from working. (but I can't say for sure)

**Comment by phryneas** [comment]
an idea I just had, don't know if it really makes sense: another idea would be to allow some css selectors like `input[placeholder="Account ID or email address"]`

**Comment by madduck** [comment]
I like the idea with placeholders, and I also agree with @tuxor1337 about the slippery slope. But maybe there are some ways by which we can improve things? It'll probably be overkill to put a lot of heuristics into PassFF, but how about we honour DOM attributes like `x-passff="login"`, which could be added to `<input/>` elements using e.g. GreaseMonkey? At least that'd be a start, and later we might be able to move some of that into the main code?

**Comment by tuxor1337** [comment]
Even though the first request was to aggressively fill in all input fields on the page, I reinterpret this issue as being about the OVH customer login page and about the general idea of recognizing input fields from user interface information like `<label>` tags (already implemented) and `placeholder` attributes (added in 5536113).
