### ISSUE TITLE
Override $GNUPGHOME in preferences

### ISSUE THREAD

**Issue by mem-** [passff/passff#201]
As a complement to issue #96 I'd like to have the possibility to override my default $GNUPGHOME settings.

Background:
I use $GNUPGHOME pointing to a specific location for my regular keyring.
For pass I created a new (dedicated) keyring, stored in an other path.
For regular pass usage, I've set  PASSWORD_STORE_GPG_OPTS="--homedir some-alt-path"

Possible solutions:
- Use $GNUPGHOME as today and apply $PASSWORD_STORE_GPG_OPTS when applicable
- and/or add a preferences setting in PassFF for its "internal" $GNUPGHOME value

Regards,
// Mem

**Comment by tuxor1337** [comment]
You can now set arbitrary environment variables in the preferences. This should fix this issue.
