### ISSUE TITLE
Windows: Host App installation process not working.

### ISSUE THREAD

**Issue by phryneas** [passff/passff#202]
As the title says: At least Chrome in windows needs a registry entry, also the shebang alone in the .py file might not be enough -  maybe something like a .bat wrapper could work.

I can do this within the next month or so if you need someone to implement this.

**Comment by nwallace** [comment]
That would be great. I don't have access to a Windows machine, so I can't do this myself.

I assumed everyone would know the Windows installation process wouldn't really work... how does pass itself work on Windows? Don't you need to be running Cygwin or the new Linux Subsystem anyway?

**Comment by phryneas** [comment]
Pass itself works great with most types of bash compiled for windows, which would include the Linux Subsystem for Windows, Cygwin, Msys2 or the Gnu tools for windows.

I'm a linux-windows mixed user, so I always have a nicely working console on my windows machines ;)

As for passff - the old passff worked using the "though shell" method, bit it had it's quirks lately with the resetting configuration. So updating to HostApp would not be the worst idea for me ^^

I'm currently writing a HostApp & Typescript library for Chrome/Firefox to use the native GPG from the browser without having to store private keys within the browser, so I think this will work quite well, although I'll have to look into the python part. I had been using go, so there was no need to specify an interpreter.

**Comment by gutierri** [comment]
close (ref #203 ,  cc @tuxor1337 )?

**Comment by phryneas** [comment]
works fine on two of my windows machines, so I gues you can close it
