### ISSUE TITLE
Add option to hide "new password" button

### ISSUE THREAD

**Issue by acabal** [passff/passff#205]
I only ever add passwords to `pass` using the terminal, so I wind up with an extra button there that takes up space for something I never do in the browser.  An option to hide that button would be cool.

**Comment by tuxor1337** [comment]
That would mean adding a "hide new password button" checkbox in the settings UI which is even more clutter. In my opinion that's to big of an effort for such an unnecessary "feature". If the "new password" button is hidden, there's nothing else which could take it's place. It would just mean slightly larger "show root" and "show context" buttons.

**Comment by acabal** [comment]
Yes it would mean a new checkbox, but in the settings pane, which for most people is only displayed once, after installation.  As opposed to a button which for me does nothing but is *always* displayed during the main use case of the addon--which in my case is the actual definition of clutter.

You could make the popup window smaller perhaps, or as you mentioned make a different button wider.  Having less buttons in the same space would also mean less chance of accidentally clicking or tapping the wrong one.  (Which does happen more often when using touchscreens on Linux, since Gnome's touch support isn't that great yet.)

**Comment by acabal** [comment]
Awesome, thanks! :)
