### ISSUE TITLE
Error of occasional path resets

### ISSUE THREAD

**Issue by ng-0** [passff/passff#206]
Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIFile.isExecutable]

It seems to me as if the "Pass command" field is semi-hardcoded to "/usr/bin/pass", which is the default on some systems but not mine.
It is the default value (https://github.com/passff/passff/blob/af066f61f116644b0206dc10ae736d1e3f268abf/src/modules/preferences.js#L13) but there is some random factor which resets my setting of the passff addon every n days (n: it really depends on the windows manager in use).

I'm planing to get webbrowser extension support for our system wide package manager, but patching it can't be a solution to what feels like an error.

**Comment by tuxor1337** [comment]
Are you using the latest version of PassFF from Github? Unfortunately this version hasn't been accepted for addons.mozilla.org yet - it's been stuck in the review process for weeks.

**Comment by ng-0** [comment]
Thanks for clearing that up. Okay, then I should use github in the future.
