### ISSUE TITLE
PassFF is outdated on the "Mozilla's addons store"

### ISSUE THREAD

**Issue by Encrypt** [passff/passff#207]
Hello PassFF devs!

I am currently PassFF that I downloaded and installed from the official "Mozilla add-ons store" here: https://addons.mozilla.org/en-US/firefox/addon/passff/

Wondering if I was the only one to encounter a few bugs, I came here and I noticed that the current version is the 1.0.0, whereas it is the 0.1.32 on Mozilla's page.

Therefore, have you planned to update the signed extension there?
If I am right, users automatically get updates for the extensions they are using when they get updated on "Mozilla's add-ons store", which is very handy :smile: 

Cheers!
Encrypt

**Comment by tuxor1337** [comment]
I answered on this two weeks ago over here: https://github.com/passff/passff/issues/169#issuecomment-307618346

But you are right to ask. The update has been stuck in the review process for a month now. I'm also getting curious about what's going on...

**Comment by Encrypt** [comment]
Oh, great! I guess we should just wait then.

Thanks for the info, I'm looking forward to testing the updated version of PassFF! :tada:

**Comment by singron** [comment]
It's worth pinging mozilla about this. It might just be lost in the queue somewhere not making any progress.

Now that addons require a mozilla signature to load at startup, there is no relief valve for AMO review slowness, so it is important that they know our pain.

The [July AMO queue update](https://discourse.mozilla-community.org/t/queue-weekly-status-2017-07-14/17081) showed a reduction in 10+ day long reviews, but they had recently been very high.

**Comment by Encrypt** [comment]
Hello guys! Have you had any news from Mozilla? 
One month has gone by since I opened the issue and PassFF is still outdated on their extensions store :confused:

As @singron said, it may be worth pinging them.

**Comment by hellomika** [comment]
https://discourse.mozilla.org/t/passff-review/18036

**Comment by tuxor1337** [comment]
Some news here: Because of issues concerning the host app under MacOS (#219, #188) and concering the general setup under Windows (#202, #171), we decided to submit a Linux-only version to AMO for now. As soon as the issues with MacOS are sorted out, a MacOS version will follow.

**Comment by tuxor1337** [comment]
We're in position 109 of 167 in the review queue. It definitely takes it's time. Is there anybody who would be willing to look into our macOS issues so that we can upgrade our Apple users asap? Unfortunately, I don't have access to an Apple machine for testing.

**Comment by hiteshpaul** [comment]
Will the extension be compatible with Firefox web-extensions? i.e, will it support Firefox version 57+?

**Comment by tuxor1337** [comment]
Yes: The version of PassFF currently under review on AMO will be based on WebExtensions. That's what we're all being so excited about 👍

**Comment by cjustin88** [comment]
@tuxor1337 I have a macOS machine and can help out with testing. I'm not much of a software developer though...

Thanks for working on this migration and AMO approval. I've freed my passwords from the grips of LastPass -- their Firefox extension is buggy and often out of date...

**Comment by tuxor1337** [comment]
@cjustin88 Okay thanks, I will come back to you as soon as I have time to look into the macOS issue. Of course, it would be better if a developer with a macOS machine could look into this.

Regarding the approval process: In the future, approval will definitely be faster in most cases. We submitted our new version for review on May 28. Because of the major changes, it was flagged for admin review. In June, we noticed the macOS problem and told the reviewers to wait since one of our devs was hoping to fix the issue soon. However, the issue was harder than we thought and the reviewers became impatient (understandably!). So they kicked us out of the review queue at the beginning of July. Then, until the beginning of August, our AMO owner was AFK. Eventually, I was added as a new owner and I decided to submit a Linux-only version last week.

Current position in AMO queue: 99

**Comment by girst** [comment]
The [Linux version](https://addons.mozilla.org/en-US/firefox/addon/passff/versions/1.0.1linux) is now available on AMO! I got the automatic update today!

**Comment by Encrypt** [comment]
Yeah, same here!

However, with this new version, I can't access my passwords anymore 😕

![capture](https://user-images.githubusercontent.com/9038199/30131671-e7010fe8-934d-11e7-8a36-a55f80f6e44a.png)

Moreover, clicking on the wheel icon (to edit the configuration) will just hide the PassFF menu.

I tried uninstalling / reinstalling the extension without success (I thought that could purge configuration files or something...). Do you have an idea?

Note: I'm running Firefox 52.3.0 on Debian Jessie.

**Comment by girst** [comment]
you'll need the host application. see the `README` for how to install it.

**Comment by Encrypt** [comment]
Indeed, I had missed that!
It works like a charm now, congratulations guys! 🎉

**Comment by tuxor1337** [comment]
Yes, it's now official 👍  Thanks for your patience!

@Encrypt: If your problem about the preferences button (wheel icon) persists, please open a new bug report here on Github.

I'm closing this. For users waiting for the macOS version, please refer to the blocking bugs #188 and #219.
