### ISSUE TITLE
Loses preferences

### ISSUE THREAD

**Issue by madduck** [passff/passff#210]
I'm not sure anymore how many times I've told PassFF to change it's behaviour, listen to `ctrl-alt-l` instead of `ctrl-y`, and use `fill-submit` as default…

Whenever I make a change, it doesn't become active right away but requires a restart of the browser.

And then, at random times, the configuration just resets itself. Every few days I find `ctrl-alt-l` no longer working, and the default having switched back to `goto-fill-submit`.

**Comment by tuxor1337** [comment]
Are you using the latest version of PassFF from Github? Unfortunately, this version hasn't been accepted for addons.mozilla.org yet - it's been stuck in the review process for weeks.

Your issue seems to be related to #184 which was a bug in the legacy version that's still distributed from addons.mozilla.org.

**Comment by madduck** [comment]
Thanks for the hint, @tuxor1337. I've now installed 1.0.0 from the Github releases page. Unfortunately, despite having set `xpinstall.signatures.required = false` and verifying that the addon was upgraded and continues to be enabled, there now isn't any "P" icon at all anywhere. I'm using FF 54…

**Comment by madduck** [comment]
Hey @tuxor1337, I've now managed to get 1.0.0 working. However, even after setting `control,alt` and `l` as the hotkey, the addon still only responds to `ctrl-y`. I've even restarted FF…

**Comment by tuxor1337** [comment]
It seems like there's no support for shortcut changes during runtime in Firefox's WebExtension implementation. In Google Chrome, there is a dialog "Configure Commands": https://stackoverflow.com/a/32709790 But in Firefox, the only way to change the keyboard shortcut would be to change the `commands` section in `src/manifest.json` and rebuild/reinstall PassFF.

If you want, you can open a new issue about nonworking keyboard shortcut configuration. Seems like the current entries in the preferences are defunct.
