### ISSUE TITLE
Conflicts with RequestPolicy plugin

### ISSUE THREAD

**Issue by madduck** [passff/passff#211]
If the RequestPolicy plugin is in use and blocking is enabled, PassFF doesn't work and can't display its dialog. Disabling blocking in RP makes it work (after a FF-restart).

I've tried adding a rule matching on destination `moz-extension://ac60db93-f403-4ecf-8e82-a8e35a1f38dc` but to no avail yet.

I'll update this issue as I find out more.

**Comment by madduck** [comment]
Seems like `moz-extension://*:*` makes it work, as would `moz-extension://ac60db93-f403-4ecf-8e82-a8e35a1f38dc:*` (note the final `*`).

**Comment by tuxor1337** [comment]
As far as I see it, this has to be "fixed" in the RequestPolicy addon. Please reopen if there's anything that we can do to make this work.
