### ISSUE TITLE
0.1.32 seems to run fine also without host application

### ISSUE THREAD

**Issue by svictor9** [passff/passff#216]
Having installed passff version 0.1.32 from Mozilla, I tried it _before_ properly installing the host application. I was surprised to see it already working. I mean after providing my gpg key password, I have access to my other passwords, can fill in forms etc. 
As far as I understood the installation instructions, the host application should be mandatory. It should live in `$HOME/.mozilla/native-messaging-hosts` (Firefox on Linux). I double checked and that folder does not exist on my system. Am I missing something?

**Comment by tuxor1337** [comment]
See #207

**Comment by svictor9** [comment]
Well, actually I had seen that post about Mozilla’s signed version lagging behind the current release. But on Mozilla’s extension page — which delivers 0.1.32 — the installation instructions already state that host application is needed. That’s what confused me. Are those instructions ahead of time and actually ment for version 1.x when it has undergone the reviewing process?

**Comment by tuxor1337** [comment]
Yes, the instructions are "ahead of time", unfortunately. Nobody expected the review process to take two months...
