### ISSUE TITLE
PassFF not compatible with Electrolysis

### ISSUE THREAD

**Issue by dannycolin** [passff/passff#218]
I've added "browser.tabs.remote.force-enable" "true" in about:config and I noticed that PassFF does not work when Electrolysis is enabled.

**Comment by Adonai** [comment]
Have you tried updating to 1.0.0?

**Comment by dannycolin** [comment]
> Have you tried updating to 1.0.0?
I've downloaded it directly from Firefox and it's definitely an old version (v0.1.32). 
I'll give 1.0.0 a try and i'll report back if it works or not. Thank for the info.

**Comment by dannycolin** [comment]
> I'll give 1.0.0 a try and i'll report back if it works or not.

Since FF 48 it seems that it isn't possible to install an add-on if it's unsigned even if you set
_xpinstall.signatures.required_ and _xpinstall.whitelist.required_ to _false_.

I know it's possible to install it with the Unbranded, Developer Edition and Nightly but I feel it is more like a workaround than a real solution. So, could you submit PassFF 1.0.0 to the Mozilla Signing Service.

You can find the information on the followed link : [https://wiki.mozilla.org/Add-ons/Extension_Signing](https://wiki.mozilla.org/Add-ons/Extension_Signing)

**Comment by Adonai** [comment]
It's already submitted. It's in Mozilla review queue since May.

**Comment by dannycolin** [comment]
> It's already submitted. It's in Mozilla review queue since May.

Thanks for the quick reply. I'll wait and report back when it will be available.

**Comment by insanemal** [comment]
So like Mozilla said it failed review? Has it been resubmitted?

**Comment by tuxor1337** [comment]
Please refer to #207 for any further discussions on the current review state. I'm closing this issue since it only applies to a now unsupported (legacy) version of PassFF.
