### ISSUE TITLE
Autofill: Asks for GPG password several times

### ISSUE THREAD

**Issue by Trollwut** [passff/passff#220]
Hi folks!

Started to use `passff` today, but TBH I'm not very happy about it yet. The installation of `pass` went fine and I use a private GitLab repo (via SSH), works.

Ok, now when I start FF, it asks me for the GPG password - I get that.

It asks me again about 5 seconds after that first one. And a third time about 30 seconds later.
It works, but I don't want to type my password 3 times.

Also, after about an hour or so, it seems like it looses functionality. I can still crawl through my passes, but pressing ENTER on them or clicking and using *any* function (fill, goto and fill) doesn't do anything. I have to de- and re-activate the plugin (enter passwords 3 times...) and then it works again.

What did I fuck up?

In my terminal, `pass` works wonderful and without problems, so I guess that's not the problem.

This is my config: [http://i.imgur.com/DWqSKPI.png](http://i.imgur.com/DWqSKPI.png)
Plugin version is 1.0.0

If you need any other information, pls don't hesitate to ask. :-)

**Comment by tuxor1337** [comment]
Do I get it right, that it's asking you for your password on startup even if you don't look up a specific password?

**Comment by Trollwut** [comment]
Yes and No - for that I can't be sure.

It asks me without *actively* seeing a login form. But on startup I've got tabs opened, which may have a login form (e.g. my mail server), so maybe it tries to autofill in background.

Should I deactivate autofill and see what it's doing then?
Or should I rather change to the version in the addons site of FF to not get annoyed every few minutes? :D

**Comment by tuxor1337** [comment]
All in all, I would call the current version from Github more secure and more stable than the previous version (which, indeed, is still available from AMO even though the new version is in review). So, I don't recommend changing your version.

But the autofill feature is pretty unstable (and that has been the case for the old version just as well). If you don't mind, disable it. Still, I'm wondering why your gpg agent keeps asking you for your gpg password even if you have unlocked it a few seconds before.

By the way, which operating system are you using?

**Comment by Trollwut** [comment]
Yeah, I also don't get the GPG issue, as I do GPG daily and don't have issues anywhere else. Also my passes are encrypted with only one specific key, so... "multi-decryption" isn't a topic either.

I'll deactivate autofill now and see if those problems reoccur. :-)

Oh, BTW: Sometimes, if it asks me those 3 times of my GPG password, it then gives me the error of "no secret key", where I then have to re-activate the `passff` addon. Will capture the message on next time.

I'm using Arch Linux, everything up-to-date.

**Comment by Trollwut** [comment]
FYI

I deactivated autofill for about an hour now and played a bit with passwords. On <Enter> a password, it will ask for my GPG pass, gets accepted, fills the form, everything ok.

So I'd like to make a quick conclusion that it might be the autofill feature causing problems.

------

On a side note: If I open a webpage and it immediately focusses the login form, I can't use CTRL+Y to open the passff menu. I have to click anywhere and then it works. Any pro tip to not have that extra click? :) (This is just a convenience thing, so... nothing really bad :D)

**Comment by tuxor1337** [comment]
Okay, let me know if you experience any problem while autofill is disabled.

Yes, unfortunately, the keyboard handling of focused web content like forms overrides the shortcut handling of Firefox addons. I don't know any way around this.

**Comment by Trollwut** [comment]
For now it works as intended. :-)
I'm fine with that. "Autofill" is now only a click, CTRL+Y and ENTER. That's convenient enough.

Mh, any way for another shortcut? For example that it just overrides CTRL modified key presses?

Or e.g. Lastpass inserts a little symbol at the end of a textbox (if its a login form) where you then can choose which credentials you want to insert there.

**Comment by tuxor1337** [comment]
PassFF adds an entry to the context menu. So, if you right click in a text input, it will give you the option to choose which credentials you want to insert. But I didn't know about the way LastPass does it. That looks pretty smooth. Maybe at some point we will reconsider adding a similar feature :+1:

**Comment by Trollwut** [comment]
Ah, didn't see the context entry, as my testsite seems to have used other form names/ids. Cool stuff!

Yeah, LastPass is really good in terms of convenience. :D

As it works for now, I'm happy with `passff`. Unfortunatelly I couldn't provide why it asks me several times when using autofill.
