### ISSUE TITLE
PassFF button does not appear with FireFox 55

### ISSUE THREAD

**Issue by guiniol** [passff/passff#222]
Since updating to FireFox 55, the PassFF button does not appear anymore.
PassFF is installed and is not disabled in `about:addons` (though it has a big `LEGACY` sticker, but this is v0.1.32, so it is expected). I can access the preferences, but that's it. the `Ctrl+Alt+t` shortcut does not work either.
One weird thing is that the version is shown as v0.1.32 but it says it was last updated on August 10th.

Any ideas?

**Comment by gutierri** [comment]
@guiniol For me too. The Add-on needs to be updated (cc @nwallace )

**Comment by shtrom** [comment]
Same issue here. I tried removing and reinstalling, and saw that.

<img width="641" alt="screen shot 2017-08-17 at 15 44 37" src="https://user-images.githubusercontent.com/160280/29397645-1c306b14-8363-11e7-980b-e444c93918c6.png">

No explanation as to why it's considered incompatible, though ):

**Comment by guiniol** [comment]
at least I'm not alone.
version 1.0.0 as been in the approval process for a while (see #169).

I removed the current version, reinstalled it, installed it from the package manager, but nothing changed. But I have not had a "not compatible with your version of FireFox" message. @shtrom are you on FF55 too?

**Comment by shtrom** [comment]
On Thu 17 Aug 2017 at 07:19:24 +0000, guiniol wrote:
> I removed the current version, reinstalled it, installed it from the package manager, but nothing changed. But I have not had a "not compatible with your version of FireFox" message. @shtrom are you on FF55 too?

Yup, just upgraded to 55 (.0.2, I think)

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by guiniol** [comment]
Just checked, and I can uninstall and reinstall it (this is with 55.0.2).

**Comment by shtrom** [comment]
On Thu 17 Aug 2017 at 06:21:35 -0700, guiniol wrote:
> Just checked, and I can uninstall and reinstall it (this is with 55.0.2).

But does it work, though?

(Note: this was on an OS X machine, that I couldn't reinstall it)

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by LoomisLoud** [comment]
This is because of [firefox dropping add ons not using WebExtensions APIs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on)
You guys probably just upgraded your firefox browser. Here are the [options to run legacy add ons](https://www.ghacks.net/2017/08/08/firefox-your-options-to-run-legacy-add-ons/).
We will have to wait for someone to port passFF to WebExtensions APIs, or do it ourselves :)

**Comment by guiniol** [comment]
@shtrom no, it didn't work

@LoomisLoud I'm aware of that, but 55 still supports legacy extensions. There is a version of PassFF using WebExtension, but it's stuck in the review process (see #169).

**Comment by tuxor1337** [comment]
Since this refers to an unsupported version of PassFF, I'm closing this.

**Comment by shtrom** [comment]
Is there a way to install v1.0.0? I've disabled signature required in about:config, but Firefox still prevents me from installing it from the Github releases 🤔

**Comment by tuxor1337** [comment]
In my case, using Firefox 55.0.2, disabling `xpinstall.signatures.required` was sufficient for installing the PassFF v1.0.0 from the Github releases. But I'm on Ubuntu, so maybe it has to do with your OS (macOS as far as I can see it). Are you aware that there are unresolved critical issues for PassFF v1.0.0 on macOS? #219, #188

**Comment by shtrom** [comment]
Yeah, I noticed those. Apparently that's why the addons in blocked in review. I'll try at home on Arch tonight.

**Comment by guiniol** [comment]
`xpinstall.signatures.required` didn't do anything for me. As noted [here](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox) it only has any effect in the ESR and the developer editions.

**Comment by tuxor1337** [comment]
Okay, but it still works for me and I'm neither on ESR nor on a developer edition. Maybe the version shipped with Ubuntu is modified to support this preference.

**Comment by guiniol** [comment]
`xpinstall.signatures.required` didn't do anything for me. As noted [here](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox) it only has any effect in the ESR and the developer editions.

**Comment by shtrom** [comment]
Yeah, same issue with 55.0.2 (64-bit) on Arch

**Comment by guiniol** [comment]
@shtrom probably. I'm also on Arch. (didn't mean to sound pedant, sorry)
