### ISSUE TITLE
Shortcut does not activate plugin while focused on textbox

### ISSUE THREAD

**Issue by dongcarl** [passff/passff#225]
Control-Y does not activate the plugin if I'm focused a textbox (let's say username), it DOES work when I unfocuse the textbox by clicking elsewhere. I'm on Arch Linux with Firefox Developer Edition and unsigned 1.0.0 release.

**Comment by tuxor1337** [comment]
This has been discussed very briefly here: https://github.com/passff/passff/issues/220#issuecomment-320230773

Maybe we can fix this by injecting a content script that listens for the keyboard shortcut. However, we would have to make sure that it's listening to the same shortcut that is defined outside for the BrowserAction.

In any case, the solution to this issue needs to be compatible with a fix for #212
