### ISSUE TITLE
PassFF panel is blank in Firefox 57

### ISSUE THREAD

**Issue by m-wynn** [passff/passff#226]
The panel has been blank for the past few days.  
![2017-09-01-205217_565x383_scrot](https://user-images.githubusercontent.com/2483388/29992021-92d1bd72-8f57-11e7-847b-68fe5281b175.png)

Some errors I see in the browser console:
``` 
addons.webextension.passff@invicem.pro	WARN	Please specify whether you want browser_style or not in your browser_action options.
ReferenceError: Iterator is not defined[Learn More]  preferences.js:53:1
	init moz-extension://a10b57f5-eb7c-4467-ac9b-0bb1eee2a308/modules/preferences.js:53:1
	init moz-extension://a10b57f5-eb7c-4467-ac9b-0bb1eee2a308/modules/main.js:112:12
	<anonymous> moz-extension://a10b57f5-eb7c-4467-ac9b-0bb1eee2a308/background.js:4:1
ReferenceError: Iterator is not defined[Learn More]  preferences.js:53:1
	init moz-extension://a10b57f5-eb7c-4467-ac9b-0bb1eee2a308/modules/preferences.js:53:1
	init moz-extension://a10b57f5-eb7c-4467-ac9b-0bb1eee2a308/modules/main.js:112:12
	<anonymous> moz-extension://a10b57f5-eb7c-4467-ac9b-0bb1eee2a308/content/popup.js:4:21
```

**Comment by tuxor1337** [comment]
Oh, this is critical. Thanks for testing it with Firefox 57! We will have to get a new version out that doesn't use the legacy `Iterator(...)` function asap. For reference: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Iterator

**Comment by justin2net** [comment]
I'm also experiencing this. Seeing the same error in the browser console:
`ReferenceError: Iterator is not defined`
Firefox 57.0a1 (2017-09-07) with plugin version 1.01linux and host extension 1.0.0.

**Comment by justin2net** [comment]
Thanks for fixing this quickly.

It is a fatal error for 57, so I'm wondering when to expect a new version to roll-out on AMO with this fix. Do you have an estimate of that?

**Comment by tuxor1337** [comment]
I submitted a new version with this hotfix on AMO yesterday, starting in queue position 139. Now we are in queue position 90. In the worst case it will take until next friday, I suppose.
