### ISSUE TITLE
Documentation for: Settings > Adding Passwords > Preferred new method

### ISSUE THREAD

**Issue by urzds** [passff/passff#228]
In the Settings, under Adding Passwords, there is a checkbox "Preferred new method", without any documentation. The README.md also gives only a very sparse explanation: "Preferred new password method ("generate" or "insert")".

What does this checkbox do? What is the old method and what is the new method and why is the latter preferred? And if it is preferred, why is the checkbox not enabled by default?

**Comment by tuxor1337** [comment]
If you open the PassFF menu and click on the "+" symbol to add a new password, a dialog will open that asks whether you want to type in your password manually or whether you would like to let the extension take care of the password generation. So there are two "new password" methods. In the preferences, you can define which of the two methods is your preferred method (if the checkbox is checked it means that you prefer the "insert" over the "auto-generate" method). This will make sure that the "add new password" dialog will preselect your preferred method whenever you press on the "+" symbol in the PassFF menu.

You are right to complain about the description and documentation of this preference. Do you have an idea how to improve it?

**Comment by urzds** [comment]
Maybe `'New password' defaults to: [Auto-generate, Manual]`?

**Comment by urzds** [comment]
Could you remember the last setting for the "New password" method? It might be more intuitive if the dialogue just remembered which method was used last time.

**Comment by nwallace** [comment]
We should change it to a dropdown with those two options. I think the reason it was a checkbox was due to some legacy contraint (or just bad decision making on my part)
