### ISSUE TITLE
Disable autofilling doesn't work until the extension is disabled and enabled again

### ISSUE THREAD

**Issue by mildred** [passff/passff#230]
Hi,

It seems that passff tries to auto fill password on many pages where I don't want it to do that. For example, I have a google search, when I reload the page, I am asked for the password. I refuse, because I don't want to log-in just then and got a message that pass failed because it has no private key.

I have both auto fill options disabled on passff preferences.

![image](https://user-images.githubusercontent.com/33804/30429826-32bb7c3c-9959-11e7-8561-7dabf44d5245.png)

I disabled passff and enabled it again, now it works. I am no longer to provide my gpg password so often.

**Comment by tuxor1337** [comment]
Can you give step by step instructions on how to reproduce this?

**Comment by tillschaefer** [comment]
I experience the same behavior. The steps to reproduce are simple: 

- go to settings
- untick "try to auto fill page login forms" 
- close setting 
- goto any site with login form 

Result: Login form is filled with credentials .

The above mentioned workaround (disable / enable) passff also works for me. 

Software:
    FF: 52.4.0
    passff : 1.0.3linux
    pass: 1.7.1
    GnuPG: 2.1.20
    os: Gentoo

**Comment by tuxor1337** [comment]
Okay thanks, confirmed.
