### ISSUE TITLE
Unexpected Error - no connection to pass?

### ISSUE THREAD

**Issue by bdynamic** [passff/passff#231]
When I hit ctrl-Y or click on the passff icon I get the following error message:
Sorry, an unexpected error occured. Make sure your preferences are correctly set and that the native host app is installed.

The debugger concole shows the following:
===
[PassFF] Runtime port has crashed: Error: Could not establish connection. Receiving end does not exist.  main.js:16:7
	logPrototype moz-extension://2c93ed20-a04e-4d86-a2df-478626df5530/modules/main.js:16:7
	bg_exec/< moz-extension://2c93ed20-a04e-4d86-a2df-478626df5530/modules/main.js:157:7
[PassFF] Error restoring menu : TypeError: menu_state is undefined
Stack trace:
init/<@moz-extension://2c93ed20-a04e-4d86-a2df-478626df5530/modules/menu.js:24:1
  main.js:16:7
	logPrototype moz-extension://2c93ed20-a04e-4d86-a2df-478626df5530/modules/main.js:16:7
	logAndDisplayError/< moz-extension://2c93ed20-a04e-4d86-a2df-478626df5530/modules/menu.js:9:5

This happens, no matter if I config PassFF via direct call or via bash
pass is reachable on bash (in PATH), config of PassFF is pointing to the output of "which pass"

System configuration:
===
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
Firefox 55.0.2 (64-bit)
PassFF Version: 1.0.1
pass Version: v1.6.5

**Comment by tuxor1337** [comment]
Have you installed the [host application](https://github.com/passff/passff/blob/master/docs/INSTALLATION.md#installing-the-host-application)?

**Comment by bdynamic** [comment]
I'm terrible sorry - I overlooked that! Previously just installing the plugin was enough.
Suggestion: If connection to the host application can't be established - wouldn't be a pup up pointing this out extremely helpful?

Yes ... I know (now) ... it is stated in the plugin description.... 

Sorry again - please reject this ticket and thank you for the great work!
