### ISSUE TITLE
Different encoding of password store does not fit well

### ISSUE THREAD

**Issue by mowgli** [passff/passff#235]
I have all terminals iso8859-1. With that, passff has some trouble to use such passwords that are in paths with german umlauts.

The following patch is a hotfix for me although it hardcode the encoding so it is not good for release.

```patch
--- passff.py   2017-08-12 16:45:33.860904579 +0100
+++ passff.py      2017-09-16 17:47:42.922327114 +0100
@@ -46,7 +46,7 @@
       proc_out, proc_err = proc.communicate()
     sendMessage(encodeMessage({
         "exitCode": proc.returncode,
-        "stdout": proc_out.decode(receivedMessage['charset']),
+        "stdout": proc_out.decode('iso8859-1'),
         "stderr": proc_err.decode(receivedMessage['charset']),
         "other": ""
     }))
```

**Comment by tuxor1337** [comment]
Would it be somehow possible to fix this by changing line https://github.com/passff/passff/blob/master/src/modules/pass.js#L487 ? We could add an option in the PassFF preferences for that.
