### ISSUE TITLE
select password with arrow keys (FF 52.3.0)

### ISSUE THREAD

**Issue by svictor9** [passff/passff#236]
In passff 1.0.3linux, once the extension’s dialog is opened (by clicking on the extension button or through the keyboard shortcut), moving down with the "down" arrow key stops at the first item of the list. The other items below the first one can only be accessed through mouse click.

**Comment by tuxor1337** [comment]
I cannot reproduce this. Which version of Firefox and which OS are you using?

**Comment by svictor9** [comment]
Hi! I have Firefox ESR 52.3.0 (64-bit) on Debian stable.

**Comment by svictor9** [comment]
In the browser console, I get the following:
Upon open passff through mouse click:
```
DEPRECATION WARNING: _getTabForBrowser` is now deprecated, please use `getTabForBrowser
You may find more details about this deprecation at: https://developer.mozilla.org/docs/Mozilla/Tech/XUL/Method/getTabForBrowser
chrome://browser/content/tabbrowser.xml 422 _getTabForBrowser
chrome://ublock/content/js/vapi-background.js 388 getTabForBrowser
chrome://ublock/content/js/vapi-background.js 509 vAPI.tabs.getTabId
chrome://ublock/content/js/vapi-background.js 1366 vAPI.net.registerListeners/locationChangedListener
  Deprecated.jsm:79
[PassFF] Initializing Menu  main.js:16:7
[PassFF] Create contextual menu  main.js:16:7
[PassFF] Search items for: URL { href: "about:newtab", origin: "null", protocol: "about:", username: "", password: "", host: "", hostname: "", port: "", pathname: "newtab", search: "" }  main.js:16:7
[PassFF] Matching items: Array [  ]  main.js:16:7
[PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 21 more… ] undefined  main.js:16:7
```

Then the first press on down arrowkey writes
```
[PassFF] Search keydown keypress { target: <input#passff-search-box>, key: "ArrowDown", charCode: 0, keyCode: 40 }  main.js:16:7
[PassFF] Select first child  main.js:16:7
```

Then the other keypresses don’t write anything more to the console.

**Comment by tuxor1337** [comment]
I assume for now that this is related to your version of Firefox. If you can reproduce this with a more recent version, just tell me.

**Comment by svictor9** [comment]
I updated to Firefox-esr 52.4.0 this morning and still the same issue. Mozilla released this update two days ago, so I suppose it can be considered "recent". ESR stands for "Extended Support Release". I understand that it’s difficult to maintain compatibility with older versions of firefox, but  firefox-esr isn’t really an "old" version, just a more stable one. It’s also the only branch of firefox in the Debian stable repos. 
Filing a bug against firefox-esr would probably be useless since I only encounter a problem in passff.

**Comment by tuxor1337** [comment]
I cannot reproduce this with PassFF 1.0.4linux from addons.mozilla.org and Firefox ESR 52.5.2 (64 bit) on Fedora 27. Please reopen with step by step instructions on how to reproduce if this issue still affects you.
