### ISSUE TITLE
pass execution failed!

### ISSUE THREAD

**Issue by volker-raschek** [passff/passff#238]
Hello, 
I want to login about passff, but every time when I a open some websites I get the following error message.

![screenshot](http://666kb.com/i/dndjphk1p31d8xfwo.png)

I believe I have some configuration errors with pass or passff, but I don't know where I must change some gpg settings to avoid this error.

My settings 
![settings](http://666kb.com/i/dndjsliwdr4ea9fwo.png) 

With qtpass it works fine with gpg encryption and git.

Please help me to fix my error.

Volker

**Comment by tuxor1337** [comment]
Is your password store directory in the default location or are you using the environment variable `PASSWORD_STORE_DIR`? Do you use a smart card for GPG? Which desktop environment do you use?

**Comment by tuxor1337** [comment]
@volker-raschek Please test with the latest version from addons.mozilla.org and report back with more information about your setup if you still need help.
