### ISSUE TITLE
Location changed loop causes FF to hang with self-destructing cookies plugin

### ISSUE THREAD

**Issue by tillschaefer** [passff/passff#240]
I get the following "Location changed" loop, whenever i browser https://relate.kde.org/user/348. The log is taken from the browser console.

```
[PassFF] Location changed "https://relate.kde.org/user/348"  main.js:16:7
[PassFF] Search items for: URL { href: "https://relate.kde.org/user/348", origin: "https://relate.kde.org", protocol: "https:", username: "", password: "", host: "relate.kde.org", hostname: "relate.kde.org", port: "", pathname: "/user/348", search: "" }  main.js:16:7
[PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object ]  main.js:16:7
[PassFF] Search items for: URL { href: "https://relate.kde.org/user/348", origin: "https://relate.kde.org", protocol: "https:", username: "", password: "", host: "relate.kde.org", hostname: "relate.kde.org", port: "", pathname: "/user/348", search: "" }  main.js:16:7
[PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object ]  main.js:16:7
[PassFF] Start pref-auto-fill  main.js:16:7
[PassFF] Best fit item Object { children: Array[0], depth: 1, key: "relate.kde.org-kde_e.v._supporting_…", parent: Object, id: 222 }  main.js:16:7
[PassFF] Execute pass Object { command: "/usr/bin/pass", arguments: Array[1], environment: Object, charset: "UTF-8", mergeStderr: false }  main.js:16:7
[PassFF] Location changed "https://relate.kde.org/user/348" 
[...]
```

The loop causes Firefox to eat 100% CPU and sometimes crashes the gpg-agent, which causes repeated password prompts. 

This happens even with autofill disabled in the plugin configuration. Using a clean FF profile (with no other extensions) solves the problem.

### Versions

- FF: 52.4.0
- passff : 1.0.3linux
- pass: 1.7.1
- GnuPG: 2.1.20
- os: Gentoo

**Comment by tillschaefer** [comment]
I narrowed it down to the self-destructing cookies plugin. When I enable the cookies plugin, have some kind of matching pass entry for the site and just browse the site the loop is reproducible. 

Thus, i do not know if this is a problem of passff itself. Nevertheless, it might be worthwhile to see, if this error can happen in other ways and if passff can actually do something against running amok.

**Comment by nwallace** [comment]
Thanks for the report. I'd guess what's happening is that the cookie plugin has a callback function of its own that ends up trigger our callback which triggers their callback, and thus we cycle forever.

Can you link me the other plugin you're talking about? I see a few different ones in my search

**Comment by tillschaefer** [comment]
https://addons.mozilla.org/de/firefox/addon/self-destructing-cookies/

**Comment by tuxor1337** [comment]
Since the latest version of PassFF from addons.mozilla.org fixes essential implementation issues of the auto-fill feature, I assume this issue to be fixed. @tillschaefer Can you confirm?

**Comment by tillschaefer** [comment]
With PassFF 1.0.4Linux and Firefox 57 (I was using 52 before) I cannot reproduce the issue anymore.

**Comment by tuxor1337** [comment]
Okay, thanks.
