### ISSUE TITLE
UI improvements for filling fields

### ISSUE THREAD

**Issue by Glandos** [passff/passff#245]
As a user that constantly uses passff, I'd like to share some of my thoughts on possible improvements for its interface.
What makes Firefox great when using its password management feature is its integration: ![suggested logins](https://framapic.org/vQJxkL1oHtbi/Jp1SYvQ96cPW)

In the current state, when using passff, we need to either use the autofill, or click on the icon to get the menu, then another click to select the right entry, then another one to fill (and possibly submit). Usually, the menu is far away from the login fields.

I'm also using [Grammalecte](http://code.grammalecte.net/), a grammar checker for french, which now uses small visual indicator for every text areas: ![grammalecte indicators](https://framapic.org/oBFETN4WDuO4/cTFdZcOZ9vvg)

I'm currently dreaming (!) of passff doing the same thing for login and password field to mimic the behavior of Firefox: adding small indicators for login field that can display an embedded frame when clicked with possible matches.

This is an early thought, and unfortunately, I have no time to participate in the code… But I just thought it worth to be shared.

**Comment by tuxor1337** [comment]
Thanks for the reference to Grammalecte which is nice to have as an examplary implementation of such a UI. It injects a content_script that manually builds up the menus for each `textarea` in the document (see `gc_lang/fr/webext/content_scripts`).

However, I would like to add to your list of possible interactions with PassFF: It's possible to invoke the menu using Ctrl+Y which can be controlled entirely from the keyboard. Alternatively, you can right-click into an input field and use the `PassFF` context menu entry to fill (currently no autosubmit here).

**Comment by Glandos** [comment]
I can't wait for testing it!

**Comment by tuxor1337** [comment]
Here's a screenshot of what it currently looks like:

![passff-fillable](https://user-images.githubusercontent.com/1518387/34275213-8fd22c78-e69c-11e7-98a4-8a6feaa2adf4.png)

It does only show the first 3 entries that you see in the menu when pressing "Show context". Currently, I don't have plans to add more features (like a search bar) to that popup.

**Comment by madduck** [comment]
@Glandos it's really easy to build from source, just clone the Git repo and run `make -C src` and then you can install `bin/passff.xpi` from the add-ons screen.

**Comment by Glandos** [comment]
I just waited for the release. It seems nice so far, and very usable!

When on HTTP (not secure), the warning from Firefox pops over the passff menu, but I think this is not so important, since credentials shouldn't be sent over clear text page nowadays.
