### ISSUE TITLE
Enter fills but does not submit

### ISSUE THREAD

**Issue by madduck** [passff/passff#256]
I built from ef31d27f3d0e2cb9a8b34dd817d489ce178f6894 and now forms are filled, but then not submitted. It worked with aff9526. Bisecting reveals a25baf64304e7706edc76274603a93ab177c0502 as the commit that introduced this.

**Comment by tuxor1337** [comment]
I can't reproduce this. It works for me. Which version of Firefox do you use? Do you refer to the situation where you select an item and then click on "Fill and submit" in the PassFF menu?

**Comment by madduck** [comment]
Thanks, it's fixed!
