### ISSUE TITLE
new dialogs are empty until resized

### ISSUE THREAD

**Issue by tillschaefer** [passff/passff#257]
The recently added dialogs for showing an entry and selecting an entry for htaccess do not show any content until they are resized. Furthermore, they no expressive title. 

Screenshot
![screenshot_20171220_212412](https://user-images.githubusercontent.com/3009428/34227367-2867a768-e5cd-11e7-8f38-9bb3b2993476.png)

**Comment by tuxor1337** [comment]
As for the window title: We can't influence this. As for the gray or empty contents: This is definitely a Firefox bug - other extensions suffer from the same problem: https://github.com/kee-org/browser-addon/issues/71

**Comment by tuxor1337** [comment]
For now, I implemented a workaround (resize the window immediately after creation forcing a repaint).

I regard the part about the title as "wontfix", since there is no way to change the popup title from a WebExtension.

**Comment by tillschaefer** [comment]
THX!
