### ISSUE TITLE
(P) icon in password fields does not work

### ISSUE THREAD

**Issue by madduck** [passff/passff#259]
Having just built from 314b1eb58162a3a3fbb09f0d3be15f199dbbb31f, I noticed the new (P) icons in login form fields. While the username can be filled in like this, clicking on the (P) in a password field has no effect whatsoever.

**Comment by tuxor1337** [comment]
Yes, it's not supposed to have any effect at the moment. It's just a way to inform you that PassFF is able to auto-fill in that field. Of course, it is planned to add more functionality to that icon before the next release :)

I hope you are not too pissed by me constantly pushing stuff without any review process. I have currently quite some time for experimenting and somehow decided to do it in the open to get your reactions ... I'm really thankful for your input!

**Comment by madduck** [comment]
@tuxor1337 I'm nowhere near "pissed". In fact, I am so grateful for your work, PassFF is probably going to be my "software of the year 2017"!!

I'm happy to be your review process. Please keep up the fantastic work and never hesitate to poke me directly if I can be of any help. Are you hanging out on IRC too? Or just Gitter? I can connect to that too, thanks to Matrix… Let me know.

Please feel free to close this issue or leave it around for others to find.
