### ISSUE TITLE
Move focus back to website after filling action

### ISSUE THREAD

**Issue by tillschaefer** [passff/passff#260]
When using the fill option of PassFF the focus is not moved back to the website. E.g., if one is focusing the login field, presses ctrl+y, and chooses an entry->fill, one is not able login by pressing enter as the focus is still somewhere else. Furthermore, other plugins for keyboard navigation like Saka Key do not work, when the focus is lost. 

PassFF should move the focus back to the component that had he focus before the shortcut was called, such that the user can simply continue to use the browser as if the fill action has never been performed (with the exception of the filled fields, of course).

**Comment by tuxor1337** [comment]
It's easy to backup a reference to the last active element when the shortcut is pressed. However, just doing `lastActiveElement.focus()` does not have any effect, if the focus is not in the current tab's content. In general, a tab's content loses focus when the menu popup opens. Afaik, WebExtensions can't move the focus back to the tab content. I tried the most obvious stuff:

    browser.windows.update(tab.windowId, { focused: true })
      .then(() => { browser.tabs.update(tab.id, { active: true }); });

But this doesn't focus the tab's content. It just brings the tab to the front.

Does anybody else have an idea how to do this? Has anybody found an entry on Mozilla's Bugzilla about this?

**Comment by kingannoy** [comment]
I experience the same issue but in a slightly different context. 

I log in using 2 factor authentication, on gitlab for example, first I click fill and submit via the plugin. Then I get the 2FA dialog, grab my phone, look at my phone screen while I'm typing the code into numpad, only to realize the field was not selected. 

I learned to click the box first now, but still, it would be really great if this could be fixed! :slightly_smiling_face:

**Comment by tuxor1337** [comment]
This seems to be related: https://bugzilla.mozilla.org/show_bug.cgi?id=1341416
