### ISSUE TITLE
Limited number of entries available for login via (P) form field submenu

### ISSUE THREAD

**Issue by madduck** [passff/passff#261]
I maintain a dozen Twitter accounts and so I have a dozen Twitter credentials. When I try to log in, using the new (P) button in the login form field, I am only shown three entries, however. Via the toolbar menu, I get to see all 12. Is there a reason why not to show all matching entries in the context menu?

**Comment by tuxor1337** [comment]
Yes, we can easily change this. For more than 5 entries, only a scrollable overview of available entries makes sense. Would this be acceptable for you? I will present you with a prototype and you can decide whether you like it.

**Comment by madduck** [comment]
If possible, I wouldn't impose an upper limit. It's unlikely that
people will have multiple matches anyway, and if they do,
a scrollable view would be best, indeed. Maybe the length can be
made dependent on screen estate?

**Comment by tuxor1337** [comment]
Latest commit implements the menu without upper limit and with scrollable view for more than 5 entries.

Making the length dependent on the viewport size etc. is more complicated. I don't have the time to fiddle around with that. But if somebody comes up with a pull request, feel free to implement something like this.
