### ISSUE TITLE
Ordering of mutliple account

### ISSUE THREAD

**Issue by madduck** [passff/passff#262]
Of the dozen Twitter accounts I manage, my primary account is the 8th when sorted alphanumerically. This means that most of the time, I cannot use the default 'enter' means to select the first entry, but have to instead browse to my primary account.

As a hack, I've now renamed the file `twitter.com/0martinkrafft.gpg` and added a `login: martinkrafft` field to its contents, which works in that the primary account now gets listed first.

But it made me wonder whether it wouldn't make sense to read our an `order` field or the like, which defaults to `50` or so, such that I could specify `order: 0` for the pimary account and thusly have it listed first without mangling the name.

**Comment by tuxor1337** [comment]
Currently, we only ever decrypt files from the password store when absolutely necessary. Storing an order field inside of the encrypted file would require encryption at the time of a key look-up - which leads to pretty frequent decryption. This slows down the whole process a lot and poses an unnecessary security risk.

Changing the filename seems (at least to me) to be a reasonable solution.

**Comment by madduck** [comment]
That's a good point. Does the ordering come straight from pass
anyway? If so, maybe I can take it up with them. I.e. there could be
an optional `subdir/ORDER` file or so, defining some rules.

**Comment by phryneas** [comment]
I can't 100% speak for the pass developers, but your chances for that are pretty slim. Pass invokes `tree` for the directory listing, so you would have to convince the tree developers to add a switch for this and then the pass developers to use that swith.

All that with the background that adding such an option would be against everything "simple, unix" I can think of.

If you really need this functionality, you would be best off to create a wrapper-script around pass that does these changes or change pass just for yourself.

**Comment by madduck** [comment]
Again, fair point. In my case, prepending `0` will indeed just work and it's not something I'm going to get worked up over. Thanks guys for your insights. I'll close this issue.
