### ISSUE TITLE
Last entry does not work

### ISSUE THREAD

**Issue by sbrandtb** [passff/passff#263]
My passwords are organized like `www.example.com/username` because I need to use https://github.com/dannyvankooten/browserpass as extension for chrom{e,ium} (note: browserpass is available for Firefox, too, but passff is just miles better). That's working fine with passff except for the last entry always seems to be broken.

It appears as `www.example.com/username/` (note the trailing slash) in the list and does not have "fill" etc list entries and password fill in does not work

Need anymore info?

**Comment by tuxor1337** [comment]
Thanks for your report! Behind your problem, there was actually a major issue with the way we were parsing the pass tree.

**Comment by sbrandtb** [comment]
Thanks, glad to help :)
