### ISSUE TITLE
Url field names in preferences not working

### ISSUE THREAD

**Issue by 5bentz** [passff/passff#264]
Hello,
First, thanks to you for this great add-on!

It looks like passff does not recognize url field names different from _url_. A few lines of code fixed the issue.

# Versions
Debian 9
Firefox 52.5.2 ESR and Firefox Developer Edition 58.0b13
passff 1.0.7linux (from AMO, addons.mozilla.org) and last build (as of 4th January)
host application: 1.0.7linux

# Steps

* (Optional) Start a clean, fresh Firefox profile & install passff from addons.mozilla.org.
* Add these passwords in your password store:
```
$ pass insert -m does_work <<_EOF
placeholder_password
login: does_work
url: example.com
_EOF

$ pass insert -m does_not_work <<_EOF
placeholder_password
login: does_not_work
http: example.com
_EOF
```
* Refresh passff to display the new passwords
* Use the _Goto_ context menu entry of each password.

# What passff is doing
With password _does_not_work_, passff goes to http://www.does_not_work.com/
With password _does_work_, passff goes to http://example.com

# What passff should do
By default, passff should go to http://example.com with both passwords.
It should recognize the url field _http_ by default, and any url field defined in the preferences.

# Code
I fixed the issue.

By comparing the code for the login & url fields, the code to find URLs (in the fields defined in the preferences) seems to be missing.
So I fixed it by myself in *src/modules/pass.js* by creating a function _setUrl_, and casually calling it with the functions _setLogin_, _setPassword_ and _setOthers_ at lines 330 and 355.
This is actually _setPassword_, but for URLs.
```
  function setUrl(passwordData) {
    let url;
    for (let i = 0; i < PassFF.Preferences.urlFieldNames.length; i++) {
      url = passwordData[PassFF.Preferences.urlFieldNames[i].toLowerCase()];
      if (url) break;
    }
    passwordData.url = url;
  }
```

**Comment by tuxor1337** [comment]
Thanks for your thorough analysis!

**Comment by 5bentz** [comment]
I'm glad it helped 👍 
I am amazed this issue hasn't been found earlier!
