### ISSUE TITLE
Suggestion for improvement when selecting passwords during login via passff button

### ISSUE THREAD

**Issue by volker-raschek** [passff/passff#265]
Hello, 
I have a suggestion for improvement. 

My directory structure in pass looks like this:

* root
  * cloud
    * example.com
      * <password:login:url>
      * <password:login:url>
  * email
    * example.com
      * <password:login:url>
      * <password:login:url>
    * outlook. com
      * <password:login:url>
      * <password:login:url>

`<password:login:url>` is one Password entry with `password = password`, `login = login username or e-mail` and  `url = login url`.

Every time, when I visit my cloud for example (nextcloud.example.com) and I want to access about the button near my login and password text fields, passff suggest my password entry from cloud and from email folder, where I stored my email access. The passwords for the email and cloud access are different. 

![Screenshot](http://666kb.com/i/dpurare5w3bvu169s.png)

How can I set passff not to search for the directory structure, which can contains domain names in the folder name. How I can set passf to search only for the login property of a password entry? 

If there is currently no possibility to influence the behaviour of the proposed passwords, it would be nice to implement this in the future.

**Comment by tuxor1337** [comment]
We have discussed similar requests before and decided not to implement features that would mean decrypting all entries at some point.
