### ISSUE TITLE
OSX: `sed` syntax in host install script

### ISSUE THREAD

**Issue by tuxor1337** [passff/passff#266]
User @mddvul22 reported in https://github.com/passff/passff/issues/219#issuecomment-355705850 about problems when executing the `install_host_app.sh` script on his Mac machine. The output is:

    $ curl -sSL https://github.com/passff/passff/releases/download/1.1/install_host_app.sh | bash -s -- firefox
    Python 3 executable located at /usr/local/bin/python3
    Installing Firefox host config
    sed: 1: "/Volumes/Data/Users/cib ...": extra characters at the end of D command

My first guess is that it might have to do with the difference between `sed` (BSD style) and `gsed` (GNU style). But I'm not entirely sure. We need somebody with Mac to do some testing here, because it's not clear which of the two sed commands fails or whether it can be solved by replacing sed with gsed etc.

**Comment by vizv** [comment]
I'll look into this, since I installed GNU flavoured `sed` with `brew` and I forgot to mention that.

**Comment by jicksta** [comment]
I'm getting the following on High Sierra:

```
$ ./install_host_app.sh --local firefox
Python 3 executable located at /usr/local/bin/python3
Installing Firefox host config
sed: 1: "/Users/jay/Library/Appl ...": invalid command code j
```

**Comment by tuxor1337** [comment]
@jicksta Thanks! Have you tested with vizv's proposed changes from here: https://github.com/vizv/passff/blob/f5cd7a30d3e1214c1ffc89bba7e8b87432417a39/src/host/install_host_app.sh

**Comment by jicksta** [comment]
@tuxor1337: @vizv's script does execute without any errors (see below), but unfortunately my extension still seems unable to communicate with `pass`.

```
❯ ./install_host_app.sh --local firefox
Python 3 executable located at /usr/local/bin/python3
Installing Firefox host config
Native messaging host for Firefox has been installed to /Users/jay/Library/Application Support/Mozilla/NativeMessagingHosts.
```

Perhaps the extension could warn when the NativeMessagingHost is not installed or it's having trouble getting an index of entries from the host system?

**Comment by vizv** [comment]
@jicksta did you remove the `NativeMessagingHosts` before install the new script?

When installing with `--local` option, did you place the required files `passff.json` and `passff.py` in the same directory?

After installation is completed, could you verify shebang is replaced correctly for `~/Library/Application Support/Mozilla/NativeMessagingHosts/passff.py`?

One last thing, you might need to disable / re-enable passff in add-on page.

**Comment by mddvul22** [comment]
Also, makes sure that you have the location to pass set correctly in the addon preferences.  And that you have the two environment variables set in the addon preferences.

**Comment by jarhill0** [comment]
@mddvul22 What are the environment variables that need to be set?

**Comment by mddvul22** [comment]
@jarhill0 see https://github.com/passff/passff/issues/219#issuecomment-354935047

**Comment by tuxor1337** [comment]
Solved in https://github.com/passff/passff-host/pull/4
