### ISSUE TITLE
Also take into account label of input fields

### ISSUE THREAD

**Issue by YL-K** [passff/passff#269]
e.g. my bank is constantly changing the name and id fields, so they can't be filled by passff.
If, however, you could detect the corresponding text input field of a label then passff would work with that, too.  
Example:  
`<label class="error" for="DubxaAlXlktThsWC">Anmeldename</label>`

**Comment by tuxor1337** [comment]
Good idea! The labels are accessible through the input element's `labels` attribute: https://www.w3.org/TR/2012/WD-html5-20121025/the-label-element.html#dom-lfe-labels Hence, this should be really easy to implement 👍
