### ISSUE TITLE
Don't run gpg when there is no fillable login field

### ISSUE THREAD

**Issue by mist** [passff/passff#270]
I'm not having my gpg password saved so I have to enter it every time I want PassFF to enter a password for me.
But I am getting asked for my gpg password with every page load even when there is no login field PassFF could fill. This is pretty anoying and makes the extension quite unusable.

Would it be possible to not run gpg when there is no login form like defined in my PassFF config?

-------
PassFF version 1.1
FF version 57.0.1
pass version 1.7.1-3 (debian/testing)

**Comment by tuxor1337** [comment]
Do I understand correctly that you have the preference "Try to auto fill page login forms" enabled?

**Comment by mist** [comment]
Yes I have. 
But since there are no login forms I don't think I need to be asked.

**Comment by tuxor1337** [comment]
Edited some stuff into my comment above.

**Comment by mist** [comment]
Ahh.
Then maybe I did understand the config wrong. I can define which fields I want to fill in ("Password input names" and "Login input names"). Those I want to be auto filled and when such a field appears I wanna be asked for my gpg password. But I don't need any other field to be autofilled.
I understood that when unchecking that box nothing at all will be autofilled.
So if I'm right maybe there could be another option like "Try to auto fill page login forms with custom names from pass db" or sth. like that.

I guess there aren't many webpages with a login field on and no other forms at all, so the usecase "no forms at all" isn't really needed.
