### ISSUE TITLE
Get error message 'Script execution failed' with custom PASSWORD_STORE_DIR

### ISSUE THREAD

**Issue by sultanofrum** [passff/passff#271]
I have the pass storage dir in a custom location and I keep receiving this error with passff, even though pass works perfectly on the terminal. The older version of the extension config had that 'pass storage dir' field, and it worked. The new preferences page seems to have done away with this, so I added PASSWORD_STORE_DIR="/path/to/directory/a/b/c/" into the environment variables field. But yet, passff keeps giving me this error on the console. I reinstalled the host application, but that didn't help, either.

**Comment by tuxor1337** [comment]
Do you put `PASSWORD_STORE_DIR="/path/to/directory/a/b/c/"` or `PASSWORD_STORE_DIR=/path/to/directory/a/b/c/`? Have you tried without the quotes?

**Comment by sultanofrum** [comment]
Oh, removing the quotes worked, thanks a lot!
