### ISSUE TITLE
Password generation popup produces alert

### ISSUE THREAD

**Issue by dylnmc** [passff/passff#275]
![screenshot from 2018-01-15 13-35-35](https://user-images.githubusercontent.com/7635158/34956908-38909966-f9f9-11e7-880b-e9703cb2826d.png)

yes, I have `pass` installed (arch).

**Comment by tuxor1337** [comment]
Which version of PassFF and which version of Firefox do you use?

**Comment by dylnmc** [comment]
I forgot because I uninstalled, and now I am at work. Quickly:

1. `pacman -Syu && pacman -S pass`

2. installed passff for firefox

3. ran `pass init` to create a new password store (or whatever)

4. attempted to use the `generate` functionality of the *passff* firefox browser add-on.

If I didn't read the readme thoroughly enough ... apologies.

Good luck.

**Comment by tuxor1337** [comment]
Which version of PassFF and which version of Firefox do you use?

**Comment by wyager** [comment]
Same issue. passff 1.0-testing, firefox 58.0.1.

**Comment by wyager** [comment]
Got it. 

    Error parsing native manifest /home/user/.mozilla/native-messaging-hosts/passff.json: JSON.parse: unexpected character at line 1 column 1 of the JSON data

And, looking at the contents of passff.json, they're:

    Not Found

And indeed, the URL is wrong.

   https://github.com/passff/passff/releases/download/1.0testing/passff.json

By curling the 1.1 release install and running that, the install seems to work.

Probaly worth mentioning that install from git clone doesn't work, or fixing it. 

Cheers,
Will

**Comment by tuxor1337** [comment]
Seems to be fixed, right?

**Comment by dylnmc** [comment]
I will close the issue if it is fixed. As it turns out, password managers did not fit into my school and work life. It double the amount of hastle that I was trying to eliminate, but I wish you all the best of luck.
