### ISSUE TITLE
Logins to Twitter don't work with <enter> or "fill and submit"

### ISSUE THREAD

**Issue by madduck** [passff/passff#276]
On https://twitter.com/login, I can log in by

1. going to menu and selecting "fill", then clicking "log in"
2. filling from the (P) menu, then clicking "log in"
3. filling and submitting from the (P) menu.

However, if I try to use "fill and submit" (or hit <enter>) from the menu, the login fails ("The username and password you entered did not match our records. Please double-check and try again.")

**Comment by 5bentz** [comment]
I can reproduce on FF52 ESR with passff AMO version and on FF59, passff last version.
If I remember well, this problem occurs on many websites.
