### ISSUE TITLE
"fillable input fields icon": password list appears behind firefox' autofill

### ISSUE THREAD

**Issue by girst** [passff/passff#278]
Sorry for the incomprehensible title, but I don't know how else to describe this:      
![screenshot_2018-02-01_14-10-18](https://user-images.githubusercontent.com/11820748/35680393-2442ee30-0752-11e8-8240-2c5872334633.png)

Is this something that PassFF can fix?

on a side note: this form is at `https://lms.uibk.ac.at` --  PassFF is also matching a whole lot of other, unrelated stuff (**E**: the one I need is the first and hidden beneath the autofill)

**Comment by tuxor1337** [comment]
About the side note: URL matching needs improvements in many respects, see issues #78, #127, #208.

**Comment by girst** [comment]
I haven't tested that, but it just occurred to me: how about setting `autofill="off"` when clicking on the (P)?

**Comment by girst** [comment]
I've procrastinated some, and I found a way to do this: disable autocomplete before clicking  (i.e. on hovering over the icon). I've sent you a pull request, although you might want to improve on this (I'm really bad at javascript)

**Comment by girst** [comment]
@tuxor1337 : any chance you could have a look at the PR please?
