### ISSUE TITLE
Blank page when extension enabled

### ISSUE THREAD

**Issue by PrestanceDesign** [passff/passff#279]
Hi,

I just begin to work with `pass` and this Firefox extension and I issue with a blank page with the web hosting panel : https://panel.phpnet.org/.
Can you debugging and/or help me to debug this ?
Thx

Best regards.

**Comment by tuxor1337** [comment]
Wow, what's going on here?! Will look into this asap, thanks for reporting! Currently, I can only confirm that this is a bug in PassFF.

**Comment by PrestanceDesign** [comment]
Nice, thank you ! 👍
