### ISSUE TITLE
curl | bash

### ISSUE THREAD

**Issue by LucidOne** [passff/passff#282]
Does it make more sense to install `passff.py` via pip instead of `install_host_app.sh`?

**Comment by tuxor1337** [comment]
I don't know why it would make sense, because install_host_app.sh is managing both passff.py and passff.json. Clearly pip wouldn't be the right choice for something like passff.json so that we would be required to run two separate commands for install...

**Comment by LucidOne** [comment]
Why not have pip install both? At least the pip infrastructure has cryptographic signing.

**Comment by tuxor1337** [comment]
Can you implement this? If it looks clean - why not?

**Comment by LucidOne** [comment]
I was thinking of implementing it as a separate repo 
`pip install passff-host`

**Comment by tuxor1337** [comment]
Yeah sure, that would be fine. Feel free to implement the pip setup and do the packaging either on pypi.python.org (see https://wiki.python.org/moin/CheeseShopTutorial#Submitting_Packages_to_the_Package_Index) or here on Github (`pip install git+https://github.com/passff/passff-host.pip`).

**Comment by tuxor1337** [comment]
Let's continue this discussion [here](https://github.com/passff/passff-host/issues/1).
