### ISSUE TITLE
No text color in passff_popup_menu

### ISSUE THREAD

**Issue by tastytea** [passff/passff#283]
The popup menu is barely readable for me. I think the issue is that in `src/skin/content.css` the `background-color` is defined but not the `color`.

![screenshot_2018-02-10t09 22 09](https://user-images.githubusercontent.com/3681516/36060160-b307d460-0e3b-11e8-8aa9-9905196c5203.png)

**Comment by girst** [comment]
do you have a url to test this? i was unable to reproduce the issue by fiddling with the dev tools.

**Comment by tastytea** [comment]
It is on every URL. I use a dark GTK-theme and I'm using system colors in Firefox (Preferences -> General -> Language and Appearance -> Colors...).
You should be able to reproduce this if you select black as default background-color and white as foreground-color there.

**Comment by girst** [comment]
that i can reproduce. seems like `color: #000` in the rules `.passff_popup_menu *` and `.passff_popup_menu *:hover` does the trick. 

you might want to open a pull request about that :)
