### ISSUE TITLE
Feature request: Sort folders on top

### ISSUE THREAD

**Issue by innir** [passff/passff#285]
It would be nice if the folders would be shown fist in the password list (or if one could choose in the preferences).

So, the list of passwords

amazon.com
cloud-services/
github.com
mailinglists/

Would become:

cloud-services/
mailinglists/
amazon.com
github.com

[If someone points me to the relevant code fragments I can try to implement it myself]

**Comment by tuxor1337** [comment]
A good idea! If you want to try implementing it yourself, you can do the ordering in the code for the menu, namely in the function `createItemsMenuList` in https://github.com/passff/passff/blob/master/src/modules/menu.js#L224 - just make sure to bring the array `items` in the desired order before doing the loop `items.forEach` in line 230.

However, such a change should be optional, so we need a new preference in https://github.com/passff/passff/blob/master/src/modules/preferences.js#L64 and a corresponding checkbox in https://github.com/passff/passff/blob/master/src/content/preferences.html

**Comment by innir** [comment]
Thanks for the pointers! ... I fear I'll not implement it myself my JavaScript knowledge is too rusty...

**Comment by innir** [comment]
OK, it was not too hard :-)

Is this already enough? https://github.com/innir/passff/commit/228a701be3aade75ac6908d005b2f0b0b191dffd
Didn't  really understand how the preferences get loaded so maybe I missed some connecting code.

**Comment by tuxor1337** [comment]
Yeah, looks good!

Two things:
* A description for the entry in the preferences user interface, i.e., an entry for `passff_prefs_directories_first` in the locales file `src/_locales/en/messages.json`
* The logic to filter directories from the item list should be using the `isLeaf` property, i.e., use `items.filter(item => item.isLeaf)` instead of relying on the item's string description.

**Comment by innir** [comment]
Ah, I missed that. Here is a (hopefully) clean PR now: https://github.com/passff/passff/pull/298
[I can even omit the sorting as the array is already sorted.]
