### ISSUE TITLE
When PassFF is active Zimbra (webmail/calender/etc) doesn't load after succesful login

### ISSUE THREAD

**Issue by kingannoy** [passff/passff#286]
On logging in on my Zimbra webclient (Zimbra 8.7.11_GA_1854) it accepts my login but after that it keeps loading and I never get to the actual interface. I can choose the "Standard HTML version" and that one does work. When I disable PassFF it works just fine.

When I open the console in Firefox and have PassFF active I get the following error:
```
Error: Permission denied to access property "_lsListenerStructId"[Learn More] Startup1_1_all.js.zgz:117:20
	AjxCore.addOnloadListener https://office.example.com/zimbra/js/Startup1_1_all.js.zgz:117:20
	<anonymous> https://office.example.com/zimbra/:2923:5
```
This error does not show when I deactivate PassFF, so I think this is part of the problem.

I have no idea what is going on here but it sure would be nice if these two applications would play nice together :slightly_smiling_face: 

I can supply anyone that want's to look into this with a test account to do further troubleshooting. I'm also willing to test some stuff out if necessary. Really weird a plugin that doesn't really do anything on a page will break it...

**Comment by tuxor1337** [comment]
Would you please check with the most recent code from Github? We had an issue related to the `onload` event that was fixed recently: https://github.com/passff/passff/commit/e1b9570cc696457f6463edf9a0f926e24e162cac

**Comment by Peter4825** [comment]
I can confirm that it works with zimbra if you use the latest from github.  Can you please make a signed release with this fix - there are many more sites broken by this bug, and disabling/re-enabling the addon is tedious, so is loading an unsigned addon.

**Comment by tuxor1337** [comment]
A signed version (1.2b) is available from AMO beta channel.
