### ISSUE TITLE
sed fails on macOS

### ISSUE THREAD

**Issue by gajovy** [passff/passff#290]
Hi,

When run on macOS sed gives the following error:
`sed: 1: "/Users/<username>/Lib ...": invalid command code k`

one way to go around it is using GNU sed instead of BSD one that is shipped with macOS, e.g.:
`curl -sSL https://github.com/passff/passff/releases/download/1.1/install_host_app.sh | sed 's/sed/gsed/' | bash -s -- firefox`

--
gajovy

**Comment by tuxor1337** [comment]
This is pull request #268

**Comment by wezm** [comment]
Just got hit by this. Yep, the linked PR fixes it.

**Comment by tuxor1337** [comment]
PR is merged -> closing this.
