### ISSUE TITLE
Override do_submit per item

### ISSUE THREAD

**Issue by madduck** [passff/passff#293]
A few websites (such as Kiwibank, and currently Twitter) work fine with passff filling fields, but not if passff also submits. However, fill&submit is the default I want to use, and I frequently forget to manually intervene on those sites.

It occured to me that passff could read a field e.g. `x-passff_do_submit` from the password files and if set to `false`, then instead of auto-submitting the login form, it might visually animate the submit button instead, suggesting to the user that manual interaction is required.

Of course, fixing passff for such sites would be preferred (#276), maybe this is a viable workaround meanwhile?

**Comment by 5bentz** [comment]
The issue #276 has been fixed for me ;) 
Commit: https://github.com/passff/passff/commit/c946de2f8146d31286b879533fc15662724d20eb

What about you?

**Comment by tuxor1337** [comment]
Closing this because the OP mentions that fixing #276 is preferred (i.e., renders this request obsolete).
