### ISSUE TITLE
passff prints debug information to browser console

### ISSUE THREAD

**Issue by acabal** [passff/passff#297]
Currently passff 1.1 prints debug information to FF's console, like this:

````
[PassFF] 8 matches for https://example.org
util.js:35:7
[PassFF] Best fit item example.org for https://example.org
util.js:35:7
[PassFF] Start pref-auto-fill
util.js:35:7
[PassFF] Start auto-fill using example.org undefined
util.js:35:7
[PassFF] Fill depth 0
````

This is a little annoying when doing web development, when we're looking at the console for other reasons.

#32 notes the same issue but it's from 2015.

Great work on this addon, thanks!

**Comment by tuxor1337** [comment]
Probably we should go back to having an option in the preferences for switching the logging on/off (this was the case in an older version of PassFF) that is turned off by default.
