### ISSUE TITLE
Ability to reference password in another record

### ISSUE THREAD

**Issue by madduck** [passff/passff#300]
Coming back to my `aspsms.com` and `smsblaster.com` example from #299, the symlinks are somewhat of a viable solution, but they are not ideal. Specifically, the `url` is different for both records, and I can only store either one or the other, unless I choose to remove the symlink and duplicate the password into a second record.

For that case, wouldn't it be great if instead of a password in `smsblaster.com/username`, I could just specify e.g.

```
$aspsms.com/username
```

in the first line? Or maybe leave the first line empty and provide a new field `use-pw-of:`?

**Comment by tuxor1337** [comment]
We could support something like a `-> /path/to/entry` syntax to have PassFF retrieve the required information from that other entry. So for example, there could be an entry `/stuff/example` containing the following:

    superSafePW
    login: -> /more_stuff/example2
    url: https://www.example.com

And then there's an entry `/more_stuff/example2` containing this:

    Another_SafePassword
    login: alice
    url: https://www.example2.org/signup

If PassFF sees the `->` while reading `/stuff/example` it will take the output of `pass /more_stuff/example2` and retrieve the login information (`alice`) from there.

For the alternative format that you are using: If the file `/aspsms.com/bob` contains `-> /smsblaster.com/alice` the password is taken from `/smsblaster.com/alice`. However, in your case it makes more sense to have a "real" symlink called `/aspsms.com/bob` pointing to `/smsblaster.com/alice`... This will already work with the current implementation of PassFF
