### ISSUE TITLE
install of py app fails

### ISSUE THREAD

**Issue by sp2004c** [passff/passff#303]
py file gets truncated to 2 bytes

path in JSON is wrong

one must do it all manually

**Comment by tuxor1337** [comment]
Would you please give step by step instructions on how to reproduce your issue.

Furthermore, I don't seem to understand what's the problem. Which py file are you talking about and how and when it is truncated?

**Comment by tuxor1337** [comment]
Closing this due to a lack of information. Reopen with requested info if you wish.
