### ISSUE TITLE
Syntax to ignore an input field?

### ISSUE THREAD

**Issue by MeisterP** [passff/passff#308]
Is it possible to use the `<other_inputfield_name>: <value>` syntax to ignore an input field?

The site in question requires `name="p_username"` and `name="p_passw"`, those are mandatory. Additionally, there's `name="p_userid"` which is optional.

The autofill feature uses `login:` for both, `name="p_username"` and `name="p_userid"`. I'd like to have it ignore `name="p_userid"`.

**Comment by tuxor1337** [comment]
Did you try adding a line

    p_userid:

i.e., without `<value>`?

**Comment by MeisterP** [comment]
yes, I've tried:
```
p_userid: ""
p_userid: " "
p_userid: ''
p_userid: ' '
p_userid:
```

**Comment by MeisterP** [comment]
The solution is to omit `login:` and use
```
mypassword
p_username: myusername
p_userid:
url: myurl
```
as soon as `login:` is set, it's used for `p_userid:` even if it's empty.

**Comment by tuxor1337** [comment]
Nice to here that you found a workaround. However, it should work as proposed in my previous comment. Have you tested with the latest code from GitHub?

**Comment by MeisterP** [comment]
I'm using version 1.1 from addons.mozilla.org
The latest version from git does indeed honour the empty `p_userid`: field, like you've mentioned in your comment.

**Comment by tuxor1337** [comment]
Ah, okay. Thanks for pointing that out!
