### ISSUE TITLE
Show notification/error message when pass cannot get a password

### ISSUE THREAD

**Issue by shtrom** [passff/passff#311]
In some cases (card not inserted, invalid passphrase, ...) pass is not able to get a decrypted password from the gpg-agent. In those cases, passff does... nothing.

It would be good for some feedback to be given to the user (both from the toolbar icon, or the added widgets in the `input` fields), so they know that something else than passff needs to be fixed.

IMO it would be best, though perhaps not very user friendly, to just show the error from pass (e.g., `gpg: decryption failed: No secret key`).

**Comment by tuxor1337** [comment]
The problem is that it's not clear where the best place for such a message is. Should we add an exclamation point to the toolbar icon? Should we inject a notification popup into the active tab's website?

Unfortunately, we cannot open the toolbar menu without user interaction.

**Comment by shtrom** [comment]
I think the notification popup is fine, something like a modal `alert`. Keeping in mind that we're dealing with `pass` users, I think some text along the line of “passff was not able to obtain a password from pass: <error from pass here>”, perhaps with the passff icon, would be sufficient.

**Comment by tuxor1337** [comment]
We have a notification popup now + optionally, a statusbar in the toolbar menu.

**Comment by tuxor1337** [comment]
I wanted to submit this update as a beta version 1.3b to AMO. Somehow it's now been released in the stable branch. I don't know what caused this, but it's not a big deal, right? I think this version is still pretty stable.

**Comment by 5bentz** [comment]
I have randomly found the reason why you failed to submit this update as a beta version:
https://blog.mozilla.org/addons/2018/02/28/discontinuing-support-for-beta-versions/

**Comment by shtrom** [comment]
Ah yeah, this works nicely with 1.3b from AMO. Cheers 👍
