### ISSUE TITLE
Shift does not work on manually selecting "Goto/fill/submit"

### ISSUE THREAD

**Issue by madduck** [passff/passff#313]
My preference is just "Fill&Submit" so that when I actually want to use "Goto", I have to navigate the record's options in the PassFF menu, and select "Goto, Fill, Submit" there.

When doing so, the Shift key does not yield a new tab being opened, which it does when the default preference includes "Goto".

**Comment by tuxor1337** [comment]
Yes, exactly. That's how it's supposed to work.

**Comment by madduck** [comment]
Please consider this a wishlist bug, i.e. if I manually select "Goto, Fill, Submit" with the Shift key pressed, then I want a new tab…
