### ISSUE TITLE
Goto: Inconsistent behaviour 

### ISSUE THREAD

**Issue by 5bentz** [passff/passff#314]
For more context, see #312 (and #221)

## Theory 
> tuxor1337 commented
> See #221 - if the user is already on the right URL, the page will not reload but only fill and submit on the current page. This applies to the setting "goto, fill, submit".

## Practice: does it really apply?
Please try to reproduce. Maybe I'm mistaken.

### Experiment 1

I tested on a website that does not alter the URL: https://www.centrale-carrieres.com/
I have this url entry in my password file: `url: https://www.centrale-carrieres.com/`

### Steps

0- Open the Dev Panel (F12) and go to the tab "Network" to see much easier the reload 
1- Go to the website (using Goto! :+1: )
2- Select the password file using the method you want to test 

### Experiment 2

Finally,
Let's test when there is not url entry, for example with this password file:
```
% pass show example.com
?6T]^*GMpT~&J:QDA/
login: mylogin
```
Same steps:

0- Open the Dev Panel (F12) and go to the tab "Network" to see much easier the reload 
1- Go to the website `example.com` (using Goto! :+1: )
2- Select the password file using the method you want to test 

### Results of both experiments

Debian 9
Firefox ESR
PassFF 1.3b

Method                              |   Reload? (theory says **no**)
----------------------------------|----------------
Goto, fill & Submit              |         **yes** <- EDIT: this is the submit (POST query)
Goto, fill & Submit (Enter)    |         **yes** <- EDIT: this is the submit (POST query)
Goto & fill (Enter)                 |        **no** if there is a URL entry, **yes** otherwise  
Goto                                    |         **no** if there is a URL entry, **yes** otherwise  

## Conclusion
Is this a bug or an undocumented feature ? :3

**Comment by tuxor1337** [comment]
I can't reproduce this on Firefox ESR with PassFF 1.3b. Maybe you miss-interpret the submit as a reload?

**Comment by 5bentz** [comment]
Pfff yes exactly. The submit has fooled me :( I verified it by running "fill & submit" and indeed, the first query is a POST for every *foobar & submit*.
Experiment 1 clearly shows that I'm was stupid this afternoon! Thanks! :+1: 

Can you reproduce experiment 2?

**Comment by tuxor1337** [comment]
If an entry doesn't have an `url` field, its name is used as url. This is documented in the README (https://github.com/passff/passff#password-configuration) - it's the example with `mysite.com`.

**Comment by 5bentz** [comment]
Oh sorry I wasn't clear:
1- Create a password named `mysite.com`
2- Go to `mysite.com`,
3- Open the network tab (F12)
4- Select the `mysite.com` password with passff, then `goto`

What I expect: No reload.
What happens: Passff reloads.

**Comment by tuxor1337** [comment]
Okay, interestingly enough, in this case, firefox adds a slash at the end of the tab's URL so that `mysite.com/` does not match `mysite.com`. Maybe we shouldn't be too strict about that and strip trailing slashes...
