### ISSUE TITLE
OS X: host app loops forever

### ISSUE THREAD

**Issue by linusr** [passff/passff#315]
Installed host application but modified passff.py to point to `/usr/local/bin/pass`

Extension does not list any pass entries not able to insert new record.

Only message in console in `[PassFF] Message Pass.executePass received in background`.

Not sure if any additional set up is required.

**Comment by tuxor1337** [comment]
Which version of Firefox, which version of PassFF and which version of the host app are you using?

**Comment by linusr** [comment]
No message in bottom status bar. 
<img width="456" alt="screen shot 2018-03-30 at 12 39 20 am" src="https://user-images.githubusercontent.com/761644/38108622-0f214726-33b3-11e8-9b2f-66937e827c23.png">
Weird thing, every time I use the extension new `bash` process gets created taking full CPU and needs to be killed.
<img width="287" alt="screen shot 2018-03-30 at 12 39 46 am" src="https://user-images.githubusercontent.com/761644/38108623-0f591534-33b3-11e8-9998-b61ea88cd4db.png">
Once `bash` process is killed got this pop up
<img width="494" alt="screen shot 2018-03-30 at 12 42 00 am" src="https://user-images.githubusercontent.com/761644/38108710-52d63490-33b3-11e8-872a-1394ab349bdb.png">
Problem is `pass` is in `/usr/local/bin` and `getopt` in `/usr/bin`.
Adding an link should resolve this?

**Comment by tuxor1337** [comment]
What is the setting for the `PATH` environment variable in your `passff.py`? Does it include  `/usr/bin`?

**Comment by pmarchwiak** [comment]
I've noticed this too. I'm on Firefox 59.0.2, PassFF 1.3b, and pass v1.7.1. The `PATH` environment variable was commented out for me in `passff.py` (which I installed using the `install_host_app.sh` script). Once I uncommented it, it started working.

**Comment by linusr** [comment]
@pmarchwiak Yes, uncommenting `PATH` environment variable in `passff.py` made it work. Thanks.

@tuxor1337 made two changes and extension works perfectly. Thanks.

```
# Default command for MacOS:
command = "/usr/local/bin/pass"
#command     = "/usr/bin/pass"
commandArgs = []
commandEnv  = {
    "TREE_CHARSET": "ISO-8859-1",
    # Default PATH for MacOS:
    "PATH": "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
}
```
