### ISSUE TITLE
Release 1.3b on AMO is not present in GitHub

### ISSUE THREAD

**Issue by 5bentz** [passff/passff#317]
Yes this is silly...

---
### What people are expecting
> Hey 1.3b is a regular release, let's check it on GitHub!

### What people are actually seeing
> Where is it?

### Solution

1. Create the 1.3b tag: ec1232d
2. Create a new release on GitHub:

Bug fixes:
2b735cc Fix typo in menu refresh button code.
586ed4a Check for ESR compat before HttpAuth handling

Features/improvements:
ec1232d Optionally show status line in toolbar menu, fix #311
0a23b8c Implement notification dialog in tab content

I used a git log command to generate that:

```
% git log 1.2..1.3b --oneline
ec1232d Optionally show status line in toolbar menu, fix #311
0a23b8c Implement notification dialog in tab content
2b735cc Fix typo in menu refresh button code.
586ed4a Check for ESR compat before HttpAuth handling
```

**Comment by tuxor1337** [comment]
Yes, you are right. The version 1.3b was supposed to be released to the AMO beta channel only. But now that there is no beta channel anymore, we have a regular release on AMO with version 1.3b. Thanks for the logs!
