### ISSUE TITLE
Connection to the host app failed or returned an unexpected result

### ISSUE THREAD

**Issue by kode9** [passff/passff#320]
Hello,

When I click on the passff button, I have the following message instead of the normal menu:

```
Connection to the host app failed or returned an unexpected result!

Make sure you have the latest version of the PassFF host app installed by following the installation instructions on GitHub.
```

I'm on `Arch Linux`, `Firefox 59.0.2 (64-bit)`, `pass v1.7.1`, `PassFF 1.3b`, `Host app 1.0.1.r9.bbf47a444`.

If I enable add-ons debugging, disable passff then enabled it again, I have this in the debug console :

```
[PassFF] Message Pass.loadItems received in background  util.js:36:9
[PassFF] Error executing pass script Error: An unexpected error occurred  util.js:36:9
	logPrototype moz-extension://87812f35-03bc-4333-951a-027f5598c0ce/modules/util.js:36:9
	PassFF.Pass.executePass</< moz-extension://87812f35-03bc-4333-951a-027f5598c0ce/modules/pass.js:207:13
[PassFF] loadItems failed!  util.js:36:9
[PassFF] Init auth module  util.js:36:9
[PassFF] Awaiting tab init... 50 about:addons  util.js:36:9
[PassFF] Tab init done 50 about:addons  util.js:36:9
[PassFF] Awaiting tab init... 50 about:addons  util.js:36:9
[PassFF] Tab init done 50 about:addons  util.js:36:9
```

I then have this every time I click on the passff button :

```
[PassFF] Awaiting tab init... 50 about:addons  util.js:36:9
[PassFF] 0 matches for about:addons  util.js:36:9
[PassFF] Tab init done 50 about:addons  util.js:36:9
[PassFF] Message Pass.loadItems received in background  util.js:36:9
[PassFF] Message Menu.getLastState received in background  util.js:36:9
[PassFF] Create menu list Array [  ]  util.js:36:9
[PassFF] Create children menu list Array [  ] true  util.js:36:9
[PassFF] Awaiting tab init... 50 about:addons  util.js:36:9
[PassFF] Tab init done 50 about:addons  util.js:36:9
```

Using the host app directly:

```
➤ echo -e "\x02\x00\x00\x00[]" | /usr/lib/mozilla/native-messaging-hosts/passff.py |  tail -c +4; ech

|{"exitCode": 0, "stdout": "Password Store\n

"stderr": "", "version": "1.0.1.r9.bbf47a4443"
```

with pass entries names in-between.

`pass` itself works correctly.

**Comment by tuxor1337** [comment]
How do you come to have this version string in your passff.py?! Currently supported version strings are "testing" and "1.0.1", nothing else.

**Comment by 5bentz** [comment]
I'm so cool that I'm reinstalling my desktop setup just for you! Kidding, it is a little happy accident. I have just carried out my plans. Let me upgrade my Arch & I'll see ;)

**Comment by kode9** [comment]
@tuxor1337 The version string is set by the packaging script [0].

Is installed the `git` version of the package to see if it would resolve the problem. 
I installed back the `stable` version of the package [1], now the version string is `1.0.1` but I still have the issue

```
➤ echo -e "\x02\x00\x00\x00[]" | /usr/lib/passff/passff.py |  tail -c +4; echo
{"exitCode": 0, "stdout": "Password Store\n

, "stderr": "", "version": "1.0.1"}
```

[0] https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=passff-host-git#n25
[1] https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=passff-host#n2

**Comment by 5bentz** [comment]
Cannot reproduce on updated Arch as of 20180401.

- PassFF: installed 1.3b from AMO
- Pass: 1.7.1
- Host: installed with the **official bash script** from https://github.com/passff/passff-host

EDIT: I see you have installed the host app with AUR, try with the official script (see above).
I'll tackle the AUR package.

**Comment by 5bentz** [comment]
Welcome to the Arch Way.

I removed the previous official passff-host installation. Verified that in PassFF. 
Then I tested:
```
% git clone https://aur.archlinux.org/passff-host.git/
% cd passff-host
% makepkg -si
```

The installation went fine and PassFF works.
```
% cat /usr/lib/mozilla/native-messaging-hosts/passff.json 
{
  "name": "passff",
  "description": "Host for communicating with zx2c4 pass",
  "path": "/usr/lib/passff/passff.py",
  "type": "stdio",
  "allowed_extensions": [ "passff@invicem.pro" ]
}
% ll /usr/lib/passff/passff.py 
-rwxr-xr-x 1 root root 3422 Apr  1 11:36 /usr/lib/passff/passff.py
% head /usr/lib/passff/passff.py
#!/usr/bin/env python3

"""
    Host application of the browser extension PassFF
    that wraps around the zx2c4 pass script.
"""

import os, sys, json, struct, subprocess

VERSION = "1.0.1"

% pass
Password Store
% echo -e "\x02\x00\x00\x00[]" | /usr/lib/passff/passff.py |  tail -c +4; echo
{"exitCode": 0, "stdout": "Password Store\n", "stderr": "", "version": "1.0.1"}
```
^ With an empty `.password-store`, or initialized (with `pass init; pass git init`). 

@kode9 
Make sure that:
- `/usr/lib/mozilla/native-messaging-hosts/passff.json` points to passff executable

Enable the status bar in the preferences & see its output in the toolbar menu.

Your passff.py has a weird output: 
```
➤ echo -e "\x02\x00\x00\x00[]" | /usr/lib/passff/passff.py |  tail -c +4; echo
{"exitCode": 0, "stdout": "Password Store\n

, "stderr": "", "version": "1.0.1"}
```
The string value of `stdout` is not even closed. Is your terminal or shell doing that? What is the output of `pass` ?

**Comment by kode9** [comment]
```
➤ pacman -Ql passff-host
passff-host /etc/
passff-host /etc/chromium/
passff-host /etc/chromium/native-messaging-hosts/
passff-host /etc/chromium/native-messaging-hosts/passff.json
passff-host /etc/opt/
passff-host /etc/opt/chrome/
passff-host /etc/opt/chrome/native-messaging-hosts/
passff-host /etc/opt/chrome/native-messaging-hosts/passff.json
passff-host /etc/vivaldi/
passff-host /etc/vivaldi/native-messaging-hosts/
passff-host /etc/vivaldi/native-messaging-hosts/passff.json
passff-host /usr/
passff-host /usr/lib/
passff-host /usr/lib/mozilla/
passff-host /usr/lib/mozilla/native-messaging-hosts/
passff-host /usr/lib/mozilla/native-messaging-hosts/passff.json
passff-host /usr/lib/passff/
passff-host /usr/lib/passff/passff.py

➤ ls -la /usr/lib/passff/passff.py
-rwxr-xr-x 1 root root 3422  1 avril 11:01 /usr/lib/passff/passff.py*

➤ head /usr/lib/passff/passff.py
#!/usr/bin/env python3

"""
    Host application of the browser extension PassFF
    that wraps around the zx2c4 pass script.
"""

import os, sys, json, struct, subprocess

VERSION = "1.0.1"

➤ cat /usr/lib/mozilla/native-messaging-hosts/passff.json
{
  "name": "passff",
  "description": "Host for communicating with zx2c4 pass",
  "path": "/usr/lib/passff/passff.py",
  "type": "stdio",
  "allowed_extensions": [ "passff@invicem.pro" ]
}
```
@5bentz No indeed, the `stdout` has not end quote, I checked with other shells/terminals. The head of the output looks like this

```
➤ echo -e "\x02\x00\x00\x00[]" | /usr/lib/passff/passff.py |  tail -c +4; echo
{"exitCode": 0, "stdout": "Password Store\n|-- \u001b[01;34msubfolder\u001b[00m\n|   |-- subentry\n|   &middot;-- subentry\n|-- entry\n

```

While the ouput of pass is:

```
➤ pass
Password Store
├── subfolder
│   ├── subentry
│   └── subentry
├── entry
```
I'm not sure about the status bar. I found a pasff option in the add-ons manager "Show a statusline in the toolbar menu" and in the firefox toolbar menu "Web Developer > Developer toolbar" which open a one line kind of console docked at the bottom of firefox but it stays empty.
There are a numbers of warning/errors though. Clicking on the error number opens the developper tools but nothing much in the console, on this page there is this:

```
[PassFF] Input search depth 0
util.js:36:9
[PassFF] 0 matches for https://github.com/passff/passff/issues/320#issuecomment-377776431
util.js:36:9
[PassFF] Input search depth 0
util.js:36:9
[PassFF] Start pref-auto-fill
util.js:36:9
[PassFF] Input search depth 0
util.js:36:9
```

**Comment by 5bentz** [comment]
The installation looks indeed fine. And the outputs are coherent.

Everything looks fine compared to my Debian:
```
% pass
Password Store
├── entry
└── subfolder
    ├── subentry2
    └── subentry

% echo -e "\x02\x00\x00\x00[]" | /usr/lib/mozilla/native-messaging-hosts/passff.py |  tail -c +4
{"version": "1.0.1", "stderr": "", "stdout": "Password Store\n|-- entry\n&middot;-- \u001b[01;34msubfolder\u001b[00m\n    |-- subentry2\n    &middot;-- subentry\n", "exitCode": 0}
```
Well, `entry` **is listed first**...

Wow, this developer toolbar is neat! However, by *toolbar menu* we mean the PassFF menu!
The status line is displayed at the bottom of the PassFF menu.

**Comment by kode9** [comment]
For the order of the entries they are in increasing alphabetical order, I just edited the names because I used an actual pass files, sorry for the confusion.

Now I did some more tests:

* clean system user: **works** (both empty pass file and w/ some data).
* back to my user with clean firefox profile: does not work
* clean firefox profile + clean password file: does **not** work

I'm not sure what's going on since it works with a new system user :/ I'm certainly missing something..

Again for the 'status' I look everywhere I really can't find anything. Just to clarify, when I click on the icon it look like this:

![passff-bug](https://user-images.githubusercontent.com/1242014/38177193-311c5a90-35fd-11e8-99b8-b52319c99fc8.png)

**Comment by 5bentz** [comment]
Oh yeah, my bad for the status line. Of course you don't have it x( Note for me: It might be possible & desirable to add it in this error menu though. :)

It is both nice and appalling...It is not even the Firefox's profile :/ Finally, we have narrowed the possible root cause to a (mis)configuration in your system user.

I have no idea either. You could check your `locale`

**EDIT: Other files could override your `passff.json`.**
- You have to check `.mozilla/native*` (and maybe `/usr/share/mozilla/native*`). Even run `find / -xdev -type f -name 'passff.json' or `locate passff.json` if you want. 
- Move and create a pristine .mozilla folder (reinstall required?)

It's high time for The Arch Way (Again). DIY now and good luck I guess.

**Comment by kode9** [comment]
@5bentz Here it is, I had a `passff.json` in `~/.mozilla/native-messaging-hosts/` from when I tried to use the official installer...
Just removed it and all is working as expected !

Well thanks a lot for pointing me in the right direction, I'm closing this I guess.

**Comment by 5bentz** [comment]
Good job!
I don't mean to be harsh, but as an Arch user you could have read the official script. Or at least remove the unnecessarily files before installing the AUR package...Next time maybe. KISS! <3

**Comment by 5bentz** [comment]
EDIT:
@kode9 
So, do you mean the official installer failed to install the host app?
If so, could you try to install it again with the official script, please?

As you have seen, the official installation overrides the AUR install, therefore you don't have to touch your AUR host app in order to test the official app ;)

**Comment by kode9** [comment]
@5bentz 
No I installed it from source before the split of the repositories, then I just forgot it..

Now to be sure, I just installed it again from scratch using the official repo and it works fine as well :+1:

**Comment by 5bentz** [comment]
Merci ! :+1:
