### ISSUE TITLE
Handle multiple HTTP auths in parallel

### ISSUE THREAD

**Issue by shtrom** [passff/passff#322]
### General information. Describe your environment

I have three pinned app tabs to subdirectories of the same server using the same HTTP Auth. Firefox asks for HTTP Auth separately for all three. When HTTP Auth support is enabled and Firefox starts, PassFF keeps popping up new, empty, dialog boxes (`moz-extension://...`) that overlap each other and the HTTP Auth windows, making it hard to enter the credentials. As the Passff's dialog boxes are empty, it is also useless in this situation.

Note that the empty dialog boxes seem to be similar to the empty dialog boxes I get when I try to `Display` the content of an entry---most of the time.

I guess it's a race condition where Firefox tries to actively pre-load all three tabs, and has to display 3 parallell HTTP Auth dialog, which means that PassFF has to do the same thing.

- Versions
  - Operating system:  ArchLinux x86_64
  - Browser: Firefox 59.0.2
  - PassFF: 1.3b (and all previous since HTTP Auth support was added)
  - Host app: 1.0.1

Status line output: `[20:03:16] show -> (0)`

- Your preferences
  - In PassFF: Handle HTTP Auth, Log to JS console
- Messages in the web console: nothing useful \:

---

### Actual behaviour
Firefox displays HTTP Auth windows one after the other; PassFF keeps popping up more `moz-extension://` windows, with no content, that overlap each other and the HTTP Auth dialog.

### Expected behaviour
Firefox displays the first HTTP Auth window, which gets handled by PassFF with its (hopefully non-empty) popup, then move on to the next, handled the same way, untill all pinned app tabs are logged in or cancelled.

### Steps to reproduce the behaviour
1. Pin 3 sites requiring HTTP Auth as app tabs
2. Restart Firefox

**Comment by tuxor1337** [comment]
The "empty" popup windows should have been fixed already: https://github.com/passff/passff/issues/257 But for some reason, the fix stopped working. I will commit a new workaround for that in a moment.

**Comment by shtrom** [comment]
Wow. Cheers for the quick fix!

**Comment by shtrom** [comment]
Hum, I just tried with the latest version from git. Installed in `addons:debugging` from the manifest.json, with the matching host script, but I still see a similar issue:
* it only opens 3 windows at a time, but seems to then be closing them then reopening them, at which point they sometime steal the focus,
* the window displayed is still empty.

**Comment by tuxor1337** [comment]
As for the second point: Sometimes, we will keep on having empty popups due to race conditions. That's because we can only try to workaround an upstream Firefox bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1408446 However, f73afa2 tries to improve the situation a bit.

Now for the first point: I cannot reproduce this behavior (especially the "reopening" part) and I'm not completely sure I understand what you mean. Of course the popups steal the focus, because they are modal dialogs. That's intended, right?

**Comment by shtrom** [comment]
Ok, actually, after restarting Firefox with the testing addon, I can see improvements.
The HTTP Auth dialog seems to be blocked, and the PassFF window shows up instead
  1. It has content more often, but resizing it makes it appear when it is initially missing
  2. Selecting the entry in the window does log in as expected, or
  3. Closing the PassFF window shows the HTTP Auth dialog
This feels pretty close to the expected, apart from the upstream bug, and the focus issue is gone. :+1: 

However, when starting with my three pinned tabs, I still do get multiple PassFF window for every site, and it seems I need to select the pass entry every time to eventually get somewhere. Eventually, the windows stop showing up, and I am indeed logged in, but it's a bit tedious.

Here a quick screen grab of what happens on start.
[Peek 2018-04-05 22-11.webm.zip](https://github.com/passff/passff/files/1879935/Peek.2018-04-05.22-11.webm.zip)

I wonder if something needs to be debounced, or Firefox has a time-based default back to the HTTP Auth dialog if nothing has been obtained from a password helper?

**Comment by tuxor1337** [comment]
Unfortunately, I can't reproduce this. When Firefox starts, it loads the tabs *before* PassFF finishes initialization, so that the HTTP auth requests are not handled by PassFF but by Firefox's default HTTP auth dialogs. But maybe this initialization race is also the reason for the strange behavior you experience.

**Comment by shtrom** [comment]
Ah! I think I just understood why I was receiving so many request on reload: I caught a glimpse of a password request for an image on one of those HTTP-protected sites, rather than the main site.

In essence, I suspect that Firefox has a cache of the old page, and tries to reload all the assets as it goes (maybe some prefetching optimisation?). As long as no HTTP-Auth has succeeded for the base URL, each request will trigger a new HTTP-Auth dialog, which will be captured by passff which will display a new dialog.

What is interesting is that Firefox itself doesn't do that, and seems to know that there is already an HTTP-Auth dialog up for the base URL, and doesn't display any other. Or maybe is it just because the HTTP-Auth dialog is modal? Maybe the passff HTTP-Auth dialog should also be modal.
