### ISSUE TITLE
Unable to get PassFF working on Mac OS - 99% CPU

### ISSUE THREAD

**Issue by nioerd** [passff/passff#323]
I tried installing the passff application one month ago, but there was an issue with "sed" between Mac OS and Linux - so I failed. Today I retried the installation and no error occurred, but it is still not working. I also discovered, that something seems to hang and then ramps up CPU usage to 99%.

pass version : 1.7.1 via homebrew
os: mac os 10.11.6
browser : Firefox 59.0.2
passFF : 1.3b
host app : version of 1.01

gpg : MacGPG2 - https://gpgtools.org/ - version -> GPG Suite 2018.1

### General information. Describe your environment
As written above, I'm running Firefox on Mac OS. I installed pass via homebrew, passff via Firefox addon page and the host app via curl.

### Status line output web console ###
[PassFF] 0 matches for https://www.packtpub.com/#
util.js:36:9
[PassFF] Input search depth 0
util.js:36:9
[PassFF] Inject icon edit-mail-1
util.js:36:9

This is one test page, where I added an entry to pass. Nothing is found / displayed inside Firefox. Using the refresh / other buttons don't help.

### Actual behaviour
After starting Firefox, a bash process starts running and rises to 99% cpu usage and stays there:
    bash /usr/local/bin/pass --

After killing this process, the following error message ist displayed in Firefox:

Script execution failed:
/usr/local/bin/pass: line 349: /usr/local/bin/getopt: No such file or directory

The error is reproduceable, each time i start Firefox.

### What it should do
From my understanding, the host app is the communication bridge between Firefox and Pass - so i would think, the python program should not rise up to 99% cpu usage and should terminate by itself.

**Comment by tuxor1337** [comment]
This is the typical result of a wrongly set PATH variable. Would you please post the contents of the `preferences section` in the installed file `passff.py` which should be located in `$HOME/Library/Application Support/Mozilla/NativeMessagingHosts`.

**Comment by tuxor1337** [comment]
For reference, when the `PATH` variable is not set correctly, `pass` will complain about not finding `getopt` and then loop forever. You can test this on the commandline:

    PATH="$(which bash | xargs dirname)" $(which pass)

**Comment by jfeick** [comment]
Could this be fixed during install time? The shell script could `sed` the current `PATH` variable from the environment.

**Comment by tuxor1337** [comment]
@jfeick That's exactly what the install script does.

**Comment by nioerd** [comment]
@tuxor1337 Thanks a lot, for your fast reply!

The content of passff.py :

# Begin preferences section #

# Default command for MacOS:
command = "/usr/local/bin/pass"
#command     = "/usr/bin/pass"
commandArgs = []
commandEnv  = {
    "TREE_CHARSET": "ISO-8859-1",
    # Default PATH for MacOS:
    #"PATH": "/usr/local/opt/icu4c/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin"
}
charset     = "UTF-8"

# End preferences section #

And an echo of $PATH:
/usr/local/opt/icu4c/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin

I hope this helps!

**Comment by tuxor1337** [comment]
Thanks! I was confused. Somehow I thought, you have the latest version from the source code. But of course, as you said, you have version `1.0.1`. I now updated the files in release 1.0.1 to include the changes to the install script. (I think we're good here without making a new release because the changes affect only the installation process, not the host app's behavior.)

@nioerd If you just follow the installation steps again with the updated files in release 1.0.1, your host app should be replaced by a working version now.

**Comment by nioerd** [comment]
@tuxor1337 Thank you 1000 times! Now i see the passwords form pass in Firefox!
