### ISSUE TITLE
Dialog not opening

### ISSUE THREAD

**Issue by schwabenchris** [passff/passff#330]
### General information. Describe your environment

- Versions
  - Operating system: Arch Linux
  - Browser: Firefox 59.0.2 
  - PassFF: 1.3
  - Host app: 1.0.1

Status line output: `[hh:mm:ss] show -> (0)`
[18:34:02] show -> gpg: Entschlüsselung fehlgesch... (2)

- Your preferences
  - In PassFF: 
  - In the host app `passff.py`: 
- Messages in the web console: 

---

### Actual behaviour
There is no dialog opening up to ask for my gnupg password.
Pass itself works slowly and is opening the password dialog after a while in the console.
No dialog shows up

**Comment by 5bentz** [comment]
PassFF requires a GUI pinentry, not a console pinentry.
Configure `gpg2` accordingly: https://wiki.archlinux.org/index.php/GnuPG#pinentry

I don't know why pass itself works slowly...does it try to run various pinentry programs before falling back to a console pinentry? I don't know.
I guess `gpg2` is working slowing under the hood.

**Comment by schwabenchris** [comment]
Solved the issue! don't know why that line was missing. Maybe a package update.

**Comment by 5bentz** [comment]
Nice :)

By default, gpg-agent uses `/usr/bin/pinentry` which is usually a symlink to a pinentry program.
Your symlink may be pointing to an incompatible pinentry program.
 
A package update shouldn't modify a custom configuration. That's what `*.pacnew` are for ;)
