### ISSUE TITLE
iframe seems to be ignored (aliexpress.com)

### ISSUE THREAD

**Issue by vejnar** [passff/passff#337]
- Versions
  - Operating system: Linux
  - Browser: Firefox 60.0.1
  - PassFF: 1.3
  - Host app: 1.0.1

I tried to login at https://login.aliexpress.com with parameter url: set to https://login.aliexpress.com. I also tried with https://passport.aliexpress.com. It doesn't work. Login fields are ignored.

The login is in iframe, which it-self is embedded in at least another iframe.

Back in 2015, PassFF.Preferences.iframeSearchDepth parameter existed and it was possible to recursively go through each iframe. It doesn't exists anymore.

Is that expected? If not, could iframe be scanned again in the new web extension?

Thanks

**Comment by tuxor1337** [comment]
Have you tested with the latest version from GitHub? https://github.com/passff/passff/blob/master/docs/INSTALLATION.md#latest-from-github

**Comment by vejnar** [comment]
The testing version is working indeed. Thanks. Maybe it's time to make a new release?

**Comment by tuxor1337** [comment]
I wanted to wait for @swarnk to complete the russian translation in #326 before making a new release. But he seems to be unavailable for quite a while now.

**Comment by vejnar** [comment]
After waiting one week, maybe it's time to release without the translation and release again when the translation is available.

**Comment by 5bentz** [comment]
@tuxor1337 As mentioned [earlier](https://github.com/passff/passff/pull/326#issuecomment-397075427), I suggest to merge the Russian translation PR and make a new release.
If you need a helping hand, I can *draft* a new release for you.

**Comment by tuxor1337** [comment]
Which version would that be? 1.3.1? 1.4? Remember, we have an ongoing discussion about semantic versioning here: https://github.com/passff/passff-host/issues/18

**Comment by tuxor1337** [comment]
Fixed in 1.4
