### ISSUE TITLE
Equivalent domains

### ISSUE THREAD

**Issue by alix-** [passff/passff#344]
Hello,

Is there an existing way to handle equivalent domains (which doesn't imply duplicating the pass entries ☺️)?
For instance, I would like to fill apple.com and icloud.com with my Apple credentials. Or amazon.com and amazon.fr.

Thanks,

**Comment by tuxor1337** [comment]
Instead of duplicating, you can create soft links.

**Comment by tuxor1337** [comment]
@alix- I assume my suggestion solves this issue for you. Otherwise, feel free to reopen.
