### ISSUE TITLE
Link on the AMO.org page is 404

### ISSUE THREAD

**Issue by JuBan1** [passff/passff#347]
Something I noticed when I found this project:

The [description on the addons.mozilla.org page](https://addons.mozilla.org/de/firefox/addon/passff/) links to `https://github.com/passff/passff/blob/master/docs/INSTALLATION.md` which leads nowhere as of db0c7f9871a3eda716bbc6ec7dc766d51818546f.

You'll probably want to link to either https://github.com/passff/passff#host-application or directly to https://github.com/passff/passff-host#passff-host.

**Comment by tuxor1337** [comment]
Thanks, very helpful feedback!
