### ISSUE TITLE
ESR: P button in the input fields not working.

### ISSUE THREAD

**Issue by swarnk** [passff/passff#348]
### General information. Describe your environment

- Versions
  - Operating system: Debian 9.4
  - Browser: Firefox (Iceweasel) 52.9.0 (ESR)
  - PassFF: 1.4
  - Host app: passf.py 1.0.1

Status line output: `[09:52:12] show -> (0) no error message`

---

### Actual behaviour
When i press "p" button in the fillable input field nothing happen. Context menu (right click) works normal. Toolbar menu works normal.

### Expected behaviour
The "p" icon should be clickable and pops up a menu to select the password. PassFF fills the input fields and optionally submit depending on your preferences. 

### Steps to reproduce the behaviour
1. Reproduce on any input fields

**Comment by tuxor1337** [comment]
I confirm this issue. For security reasons, we are now loading the popup menu in an `<iframe>`, but Firefox 52 seems to refuse loading the iframe contents. Unfortunately, there's no error output and I can't find any information on the web that explains or justifies this behavior.

**Comment by tuxor1337** [comment]
Next week, support for 52 ESR is dropped. Since more recent ESR versions are not affected, I'm closing this.
