### ISSUE TITLE
Preferred organizational scheme used by the author of pass

### ISSUE THREAD

**Issue by hyiltiz** [passff/passff#349]
The [Readme.md](https://raw.githubusercontent.com/passff/passff/master/README.md) in master mentions:

```
<the_password>
login: <the_login>
url: <the_url>
<other_inputfield_name> : <inputfield_value>
```

while in fact, the author recommends [here](https://www.passwordstore.org/):
```
Yw|ZSNH!}z"6{ym9pI
URL: *.amazon.com/*
Username: AmazonianChicken@example.com
Secret Question 1: What is your childhood best friend's most bizarre superhero fantasy? Oh god, Amazon, it's too awful to say...
Phone Support PIN #: 84719
```

The difference is mainly whether additional information can be added, and whether `Username` comes before `URL`. Additionally, whether it is called `login` and whether `url` is upper case. I understand that it is simply plain text file, but not sure which formats are supported.

Also, it would be great for the information to be accurate.

**Comment by phryneas** [comment]
Actually, just above that example from passwordstore.org, the paragraph says

> The password store does not impose any particular schema or type of organization of your data, as it is simply a flat text file, which can contain arbitrary data. 

and the quoted example is one of two different examples given.

So, officially there is no "supported format". Everything goes.


Out of the box, passff is configured to look for the username fields `login,user,username,id`, the password fields `passwd,password,pass` and the url fields `url,http`. All of those are case-independent if I'm not wrong.
Order of lines does not matter (except password being in the first line if no `key: value`-type password is given).

So, both of the above examples (and a lot more) are absolutely correct and even more can be configured in the preferences. Just organize it as you like ;)

**Comment by hyiltiz** [comment]
Nice! Didn't know the order doesn't matter. Is it possible to use it along with pass-tomb (so file names doesn't leak information) and pass-otp?

**Comment by phryneas** [comment]
I'm not 100% acquainted with pass-tomb, but I guess if you `open` it from the commandline before, it should work.

I guess a more sensible approach would be to use git-remote-gcrypt and just have the file structure unobfuscated on your pc. If an attacker already is on your machine the folder structure will be the least of your problems.

Pass-otp is unsupported as far as I know, you can read up on that here https://github.com/passff/passff/issues/200

**Comment by tuxor1337** [comment]
I close this. If you have an issue or a feature request feel free to open a new issue.
