### ISSUE TITLE
Cannot fill&submit at Kiwibank.co.nz

### ISSUE THREAD

**Issue by madduck** [passff/passff#354]
Over at the [Kiwibank Online Banking login](https://www.ib.kiwibank.co.nz/login/), I can fill and manually submit just fine, but if I fill&submit, then the page reloads, with the password cleared. I suppose this is a security feature of the site, but I was wondering if this could be worked around?

**Comment by tuxor1337** [comment]
In the page module, in the function `getSubmitButton`, the `querySelector` does not include the particular button type present on the Kiwibank login page, namely `input[type=button]`: https://github.com/passff/passff/blob/master/src/modules/page.js#L46 So PassFF tries to submit using `form.submit()`, which circumvents the button's JavaScript `onclick`.

Adding this button type to the `querySelector` might already fix your issue.

**Comment by tuxor1337** [comment]
Please try again using 794db83

**Comment by madduck** [comment]
Yes, that fixes it for this site. Awesome!!!
