### ISSUE TITLE
Cannot select the entry using the keyboard

### ISSUE THREAD

**Issue by PACordonnier** [passff/passff#362]
### General information. Describe your environment

- Versions
  - Operating system: Fedora 27
  - Browser: Firefox 61.0.2
  - PassFF: 1.5.1
  - Host app: 1.0.2

Status line output: [15:23:21] show -> (0) no error message

- Your preferences
  - In PassFF: Behaviour of enter key: Fill
  - In the host app `passff.py`: No modification
- Messages in the web console: Nothing

---

### Actual behaviour

On a website where I would like to fill the login/password.
I press ctrl+y (shortcut to open passff)
The first entry is not the one i'm looking for (I often have to impersonate users so multiple entries in my pass store, no problem here)
I cannot select and fill the correct entry. Using the Arrow keys move the selection, but pressing Enter does not do anything (fill or just go the menu where I can select what I want to do).

I have to use the mouse which is obviously the biggest problem in the world :scream:

When the correct entry is the first one of the list, pressing ctrl + y then 'Enter' correctly fill the fields -> working as expected

### Expected behaviour

Being able to do what I want without using the mouse. 
When there are multiple entries, the arrow keys + enter should be enough.
I'm pretty sure this feature was present in older releases and I lost it after an update of my system. I cannot be more specific since I don't know what versions I used :(

### Steps to reproduce the behaviour

1. Passstore with 2 entries: github1 and github2
2. Go to github.com on the login screen
3. Notice that is not possible to select the github2 without using the mouse

### Comment

I've been using passff for more than a year now, I'm a very happy user and I can see all the work and the features that has been released, thank you for your work ! 

Please let me know If I need to provide more infos or if I did something wrong in my issue

Regards

**Comment by tuxor1337** [comment]
I cannot reproduce this on Fedora 28 and Firefox 61.0.2 with PassFF 1.5.1.

Please enable the logging to the JavaScript console in the PassFF preferences, then have a look into the log output while reproducing your issue (go to about:debugging and click on 'debug').

**Comment by PACordonnier** [comment]
Hi,

Thank you for your reply.

I'm pretty confused right now, the behaviour is not the same I had yesterday and is now exactly the same as in #130. The selection is 'stuck' once I press the bottom key (The first entry is selected)

I don't see anything particular in the log output:

```
[PassFF.background] Awaiting tab init... 108 https://www.reddit.com/ util.js:36:9
[PassFF.background] Tab init done 108 https://www.reddit.com/ util.js:36:9
[PassFF.background] Awaiting tab init... 108 https://www.reddit.com/ util.js:36:9
[PassFF.background] 2 matches for https://www.reddit.com/ util.js:36:9
[PassFF.background] Tab init done 108 https://www.reddit.com/ util.js:36:9
[Show/hide message details.] Promise resolved while context is inactive
apply.js:56
[PassFF.background] Message Preferences.getBrowserCommand received in background util.js:36:9
[PassFF.background] Message Pass.loadItems received in background util.js:36:9
[PassFF.background] Message Menu.getLastState received in background util.js:36:9
[PassFF.menu] Create menu list 
Array [ {…}, {…} ]
util.js:36:9
[PassFF.menu] Create children menu list 
Array [ {…}, {…} ]
 true util.js:36:9
[PassFF.menu] Search keydown 40 util.js:36:9
[PassFF.menu] Select first child util.js:36:9 
```
Everything seems to be normal, but everything is stuck after 'select first child'

**Comment by tuxor1337** [comment]
* Are you in a Wayland or X11 session?
* Have you tried reproducing this with a clean Firefox profile?

**Comment by PACordonnier** [comment]
I'm using Wayland.

I created a clean Firefox profile and everything is working perfectly now.;
The problem is probably somewhere in my Firefox profile. It needs a good cleanup :)

I think we can close the issue, I don't think it's worth the time to find the cause of the problem.

Thank you

**Comment by tuxor1337** [comment]
Okay, feel free to reopen if the issue reappears in your new profile.
