### ISSUE TITLE
Script execution failed:  cancelled by user & decryption failed: No secret key

### ISSUE THREAD

**Issue by kierun** [passff/passff#367]
### General information. Describe your environment

- Versions
  - Operating system: CentOS7 7.5.1804 (Core)
  - Browser: Firefox 62.0.2 (64-bit)
  - PassFF: 1.5.1
  - Host app: 1.0.2

Status line output: `[hh:mm:ss] show -> (0)`

`show -> (2) gpg: cancelled by user gpg: decryption failed: No secret key `

- Your preferences

Those appear to be sane. The `pass` commands work fine from a shell.

- Messages in the web console: 

`[PassFF.content] Message Page.notify received in content`

---

### Actual behaviour

Every time I try to fill some password, I get a window saying:

```
Script execution failed:
gpg: cancelled by user
gpg: decryption failed: No secret key
```

### Expected behaviour

I expected a GPG prompt to enter my password.

### Steps to reproduce the behaviour

I suspect an error between keyboard and floor but am unsure where to start to look at what I am doing wrong.

**Comment by 5bentz** [comment]
Hey kierun,
1. When you try to fill a password with PassFF, are you prompted for a password?
2. When you use `pass`, does it prompt a pinentry in the terminal?

If the answers to those questions are *no* then *yes*, could it be a pinentry issue?

See https://github.com/passff/passff#nothing-happens-when-i-click-on-a-password-and-select-an-action

**Comment by kierun** [comment]
> When you try to fill a password with PassFF, are you prompted for a password?

No I am not. Just a result that something failed.

> When you use pass, does it prompt a pinentry in the terminal?

Yes, I am. Although it is the console version and not a GUI.

**Comment by kierun** [comment]
I installed all the pinentries I could find. I have not restart my machine but that should not matter. I am still getting the same problem.

I wonder if this is because the first thing that the code looks for is `pinentry` thus the console one…

If I run `pass …` in a console then the auto-fill works fine. I suspect pinentry caches the authentication for a little while so I can get around the issue but it's annoying. It works fine on my Fedora machine.

**Comment by 5bentz** [comment]
> I installed all the pinentries I could find. I have not restart my machine but that should not matter. I am still getting the same problem.

You probably have to configure gpg2 to use a GUI pinentry. Or maybe you have to reload the gpg-agent. Restart if you can.
See https://wiki.archlinux.org/index.php/GnuPG#pinentry

> If I run `pass …` in a console then the auto-fill works fine. I suspect pinentry caches the authentication for a little while so I can get around the issue but it's annoying

Yes, gpg-agent do caches your passphrase for a while, the duration of retention is configurable.

> I wonder if this is because the first thing that the code looks for is `pinentry` thus the console one…

This is indeed what gpg-agent looks for first. 
If `/usr/bin/pinentry` is a symlink on your system, you could also modify it, or configure `update-alternatives` to do it for you ;)

**Comment by kierun** [comment]
> You probably have to configure gpg2 to use a GUI pinentry.

And this was the solution! ☺

Many thanks indeed for taking the time and effort to help me debug this. It is much appreciated.

**Comment by 5bentz** [comment]
Nice, I'm glad the pinentry was the culprit ;)
I'm updating the README to explicitly document this dependency.

Thanks for using PassFF and supporting our work :+1:

**Comment by kierun** [comment]
> Thanks for using PassFF and supporting our work +1

You are most welcome. Thank you again for your time and support

**Comment by nrrkeene** [comment]
As another I also had this problem and none of the solutions worked for me. The passwords are present, git is set up, I installed the pinentry software, restarted, configured gpg-agent, and still the browser plugin says "decryption failed: No secret key." The problem having taken more than 100% of the time over my whole lifetime I want to dedicate to setting up a password manager, I am abandoning the attempt to use _pass_. I put in about three hours to the whole attempt, got the passwords imported, set up git, set up git online, got those to exchange passwords, and the command line worked. Zero browsers configured, zero mobile devices configured, zero passwords shared with another person. Three hours is too much to have only achieved that much, I don't have 30 more hours to finish the setup.
