### ISSUE TITLE
A record called "user" throws off filling

### ISSUE THREAD

**Issue by madduck** [passff/passff#369]
I'm running PassFF 1.5.1 on FF 62. If I create a file `netgear-ap/user` (I cannot change the username, on this old Netgear AP) with the right password, then the PassFF dialog will only show `netgear-ap` as option, and filling will result in the password being put into both, login and password fields.

In order to make this work, I need to put password and `login: user` into a file `netgear-ap`.

So a file named "user" throws something off in the filling logic.

**Comment by tuxor1337** [comment]
This is documented here: https://github.com/passff/passff#file-structure-format
