### ISSUE TITLE
Doesn't work on (new) reddit.com

### ISSUE THREAD

**Issue by alex3kov** [passff/passff#372]
### General information. Describe your environment

- Versions
  - Operating system: `Arch Linux`
  - Browser: `Firefox 63.0`
  - PassFF: `1.5.1`
  - Host app:  `1.0.2`

Status line output: `[10:42:44] show -> (0) no error message`

- Output of `pass`: 
pass show reddit.com 
pass$$w0rd
user: MyUserName
url: reddit.com

- Your preferences
  - In PassFF: `default` + enabled web console logging.
  - In the host app `passff.py`: `default`, didn't touch anything.
- Messages in the web console: 

```
[PassFF.content] 2 matches for https://www.reddit.com/ util.js:36:9
[PassFF.content] Best fit item reddit.com for https://www.reddit.com/ util.js:36:9
[PassFF.content] Start pref-auto-fill util.js:36:9
[PassFF.content] fillInputs: No password inputs found! util.js:36:9
[PassFF.content] 2 matches for https://www.reddit.com/login util.js:36:9
[PassFF.content] Best fit item reddit.com for https://www.reddit.com/login util.js:36:9
[PassFF.content] Inject icon loginUsername util.js:36:9
[PassFF.content] Inject icon loginOtp util.js:36:9
[PassFF.content] Inject icon loginPassword util.js:36:9
[PassFF.content] Start pref-auto-fill util.js:36:9
[PassFF.content] Start auto-fill using reddit.com undefined util.js:36:9
[PassFF.content] Set inputs... util.js:36:9
```
---

### Actual behaviour
Can't log in to new reddit.com interface:
![reddit](https://user-images.githubusercontent.com/3616242/47484170-c091f700-d843-11e8-90f5-177ecb4e7e18.png)

### Expected behaviour
Successful logon to new reddit.com interface.

### Steps to reproduce the behaviour
1. Go to reddit.com
2. Click "Login" button
3. Wait for PassFF to auto-fill data
4. Click "Sign in" or press Enter
5. Receive error

**Comment by madduck** [comment]
Same here.

**Comment by heyarne** [comment]
I have the same system and I can report the same behavior. My workaround is to fill in the username manually and copy and paste the password.

**Comment by heyarne** [comment]
To be clear: What it does is it fills out both fields correctly, but after clicking the login button the above message appears.

**Comment by heyarne** [comment]
This has been solved in the meantime; I don't know if it's a change in code or if reddit just works as it should now, but I don't have any problems with this anymore.

**Comment by heyarne** [comment]
This has been solved in the meantime; I don't know if it's a change in code or if reddit just works as it should now, but I don't have any problems with this anymore.

**Comment by alex3kov** [comment]
@heyarne thanks for letting us know, works for me too. I've been logging in to old.reddit.com all this time.

**Comment by madduck** [comment]
I can also confirm fixing.
