### ISSUE TITLE
URL Matching: use metadata files to store fields like 'url'

### ISSUE THREAD

**Issue by bloeys** [passff/passff#375]
Hello,

So I understand that it isn't practical to use the fields of a password since that would require decrypting the whole database #374. But I have a suggestion for matching by using the user provided 'url' field or similar (which should give more accurate suggestions).

Maybe we can have **unencrypted** metadata files (optional; user enabled) for each gpg file that contains for example the URL field, which can then be used to match.

Would like to hear your input on this.
Thanks.

**Comment by tuxor1337** [comment]
This has been suggested several times already and deemed impossible:

About unencrypted metadata (https://github.com/passff/passff/issues/346):

> I can't see any note in the pass documentation about unencrypted entries and it doesn't sound to me like they suggest to have unencrypted .meta files.

About a global (encrypted) metadata/index file (https://github.com/passff/passff/issues/124#issuecomment-200542665):

> just as a heads up: such a mapping file has been suggested a few dozen times in the two years I've been reading the mailing list.
> nobody there thinks that it is a good idea.

If you don't come up with a new approach to these concerns, please close this issue.

**Comment by bloeys** [comment]
I see. Thank you for referencing the other issues.
