### ISSUE TITLE
Cannot select the entry using the keyboard arrows

### ISSUE THREAD

**Issue by movd** [passff/passff#383]
*similarities to to #362, but new Firefox profile doesn't help*
### General information. Describe your environment

- Versions
  - Operating system: Ubuntu 18.04.1 LTS
  - Browser: Mozilla Firefox 65.0
  - PassFF: 1.5.1
  - Host app: 1.0.2

Status line output: `[12:55:15] ls -> (0) no error message`

- Output of `pass`: *(works just fine)*
```
Password Store
├── [REDACTED] 
├── [REDACTED] 
├── [REDACTED] 
[...]
```
- Your preferences
  - In PassFF: *Logging to Console and status line turned on*
  - In the host app `passff.py`: `Default`

- Messages in the web console: 

```
[PassFF.content] 13 matches for https://[REDACTED] util.js:36:9
[PassFF.content] Best fit item [REDACTED]  for https://[REDACTED]  util.js:36:9
[PassFF.content] Inject icon Ecom_User_ID util.js:36:9
[PassFF.content] Inject icon Ecom_Password util.js:36:9
```

### Actual behaviour

Pressing CTRL+Y brings up the selection of multiple login/password combinations for a website.
Entries from the list can be selected by using the mouse or after pressing Tab-key with the arrows up/down on the keyboard . 

They can only be selected by using the mouse or pressing 
On a website where I likt to fill a password

### Expected behaviour
Using the arrow directly. This was possible before.

### Steps to reproduce the behaviour
1. Passstore with 2 entries: github1 and github2
2. Go to github.com on the login screen
3. Notice that is not possible to select the github2 without using the mouse or pressing Tab first

### Troubleshooting steps already taken:
1. Created a clean Firefox profile like in issue #362

**Comment by tuxor1337** [comment]
This is because we are listening to the `keypress` event which has been deprecated for a while (https://developer.mozilla.org/en-US/docs/Web/Events/keypress) and, starting from Firefox 65, is only supported for character keys (https://bugzilla.mozilla.org/show_bug.cgi?id=968056). Fix coming soon...
