### ISSUE TITLE
autofill puts password in the username-field on thingiverse

### ISSUE THREAD

**Issue by logpig** [passff/passff#386]
when i try to use this addon on the thingiverse side, it puts my password into username field and i guess vice versa.

**Comment by tuxor1337** [comment]
You are referring to this page, right? https://accounts.thingiverse.com/

Please inform the admins of that page that the `<label>` tag for the "Password" field has a wrong `for` attribute, namely `<label id="password-label" for="username">Password</label>`. I don't know how PassFF should know that it's not a password field as long as there is a label for it that says "Password".

**Comment by logpig** [comment]
sorry that i bothered you with such a noob request...

shame on me... -.-'

**Comment by tuxor1337** [comment]
No reason to apologize :+1: 

Your submission was an inspiration for me to improve the detection of input field types. After an update to 1.6.1 (from addons.mozilla.org), your problem with thingiverse.com should be resolved (despite the misleading labelling).

**Comment by logpig** [comment]
oh man, you are great...
works like a charm, now...
only thing i realized is, that it doesn't automatically push the login button anymore...
no big deal for me, because your addon keeps me off typing long unmemorable passwords...
Thank you for making the web a safer place...

**Comment by tuxor1337** [comment]
Yeah, I'm sorry, I messed up that submit feature, it's fixed in the latest commit. Version 1.6.2 will be available in a few minutes.

**Comment by logpig** [comment]
you really don't have a reason to apologize!!! 
thank you very much...
