### ISSUE TITLE
Password loading fails when file contains a otpauth:// field

### ISSUE THREAD

**Issue by jarhill0** [passff/passff#387]
### General information. Describe your environment

- Versions
  - Operating system: macOS 10.14.2 (18C54)
  - Browser: Firefox 65.0.1 (64-bit)
  - PassFF: 1.6.2
  - Host app: "testing" (not sure; pre 1.1.0)

Status line output: `[14:12:50] show -> (0) no error message`

- Output of `pass`: 
  ```
  [password censored]
  login: jarhill0
  url: https://github.com/login
  otpauth://totp/GitHub:jarhill0?secret=[secret censored]&issuer=GitHub
  ```
- Your preferences
  - In passff:
    - "OTP Auth field names": otpauth
  - In the host app `passff.py`: 
  ```
  # Default command for MacOS:
  COMMAND = "/usr/local/bin/pass"
  #COMMAND      = "/usr/bin/pass"
  COMMAND_ARGS = []
  COMMAND_ENV  = {
      "TREE_CHARSET": "ISO-8859-1",
      # Default PATH for MacOS:
      "PATH": "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
  }
  CHARSET      = "UTF-8"
  ```
- Messages in the web console: 

```
[PassFF.content] 3 matches for https://github.com/login/ util.js:66:9
[PassFF.content] Best fit item personal/github for https://github.com/login/ util.js:66:9
[PassFF.content] Inject icon login_field util.js:66:9
[PassFF.content] Inject icon password util.js:66:9
[PassFF.content] Runtime port has crashed: Pass.executePass Error: "Invalid Version: testing" util.js:66:9

    logPrototype moz-extension://34ea875d-5229-3d4f-a750-ba9916e699b3/modules/util.js:66
    background_exec moz-extension://34ea875d-5229-3d4f-a750-ba9916e699b3/modules/util.js:137 

```
---

### Actual behaviour
When I attempt to fill (or fill and submit, or display) the password, nothing happens and the error seen above is displayed in the console. This *only* happens for sites which have a line like `otpauth://totp/GitHub:jarhill0?secret=[secret censored]&issuer=GitHub` (OTP, not necessarily GitHub OTP), and it happens for all of them.

### Expected behaviour
The password should be filled (or filled and submitted, or displayed).

See below for description of my hypothesis about the cause. If the new version of passff has some incompatibility with passff-host, I would expect it to (a) fail gracefully and still fill the password if at all possible, or (b) alert the user that the host application needs to be updated.

### Steps to reproduce the behaviour
1. Create a `pass` entry with an `otpauth` line as seen above.
2. Attempt to perform any operation in PassFF with it, such as Display.

### Possible cause
This issue wasn't present until the last week or two. It makes the most sense to me that it was introduced with Version 1.6, since that version introduced features related to OTP.

### My solution
Unsetting the default value (`otpauth`) of the "OTP Auth field names" preference causes passff no longer to recognize the field that gives it trouble, solving my issue. Alternatively:

I have upgraded to passff-host version 1.1.0 and restored the default value of that field. Now, when viewing or filling a password with an `otpauth` field, the operation succeeds, but I *also* get an error message:

> Script execution failed:
> Error: otp is not in the password store.

Presumably this is because I haven't installed [pass-otp](https://github.com/tadfisher/pass-otp). Since I use the `otpauth` field with [passforios](https://github.com/mssun/passforios) and not passff, it would be nice to have an option to not see this error message.

---

## Summary

Passff version 1.6 seems to have introduced an incompatibility with older versions of passff-host around OTP features which causes it to fail without any warning or error message.

**Comment by tuxor1337** [comment]
There is no official support for passff-host version "testing" because there never was a recommended way of installing the host app that ended up having such a version. So I will ignore the part about "testing".

Now you say that you still get an error message with host app version 1.1.0. And officially, there shouldn't be. So, I will look into that...

**Comment by tuxor1337** [comment]
Okay, confirmed, somehow I thought we already dealt with this case.

**Comment by tuxor1337** [comment]
I remember now that this was a conscious design decision. We somehow expected that somebody who has a line with otpauth in her password store would naturally also use the pass-otp plugin. That's obviously wrong. But I hope it's still a rare case. 

In version 1.6.3, we make sure that PassFF silently fails when trying to call the pass otp plugin. It will still continue calling `pass otp ...` whenever a line starting with `otpauth` is in your pass entry. So you will see warnings in the logs, but it shouldn't interfere with the UI.

**Comment by jarhill0** [comment]
Thanks! I'm impressed by the quick fix.
