### ISSUE TITLE
Ctrl-y does not work when focus is in address bar

### ISSUE THREAD

**Issue by patrickrst** [passff/passff#388]
### General information. Describe your environment

- Versions
  - Operating system: Debian buster/sid
  - Browser: Firefox 65.0
  - PassFF: 1.6.3
  - Host app: 1.1.0

---

### Actual behaviour
When the cursor is focused in Firefox address bar (Awesome Bar), the passff shortcut to open the menu (Ctrl-y) does not work.

### Expected behaviour
The passff menu should open.

### Steps to reproduce the behaviour
1. Open new tab (Ctrl-t)
2. Press Ctrl-y
3. Nothing happens

**Comment by tuxor1337** [comment]
Yes, this is known and we won't fix it: https://github.com/passff/passff/issues/352 Please choose a different shortcut in the preferences of PassFF that doesn't conflict with internal shortcuts of Firefox.

**Comment by patrickrst** [comment]
Ah thanks. Didn't catch that issue when searching.
