### ISSUE TITLE
Fails to fill form for bitcoin.de, possibly OTP related

### ISSUE THREAD

**Issue by madduck** [passff/passff#389]
I just encountered a problem similar to #387 on bitcoin.de, using PassFF 1.6.3, as well as passff-host at commit a37d504b9035d7fc7c04fea1d05835e18a3cee6d, i.e. master after 1.1.0 was released:

```
fishbowl:…a/native-messaging-hosts% grep otp passff.py       #(pts/6) 20 11:44:48.127
    elif receivedMessage[0] == "otp" and len(receivedMessage) == 2:
        opt_args = ["otp"]
```

The login form at bitcoin.de is not being filled in while the `otpauth://` line is present in the data file. It works when I remove the line.

Here is the log output:

```
11:36:03.814 [PassFF.background] 2 matches for https://www.bitcoin.de/en/login util.js:66:9
11:36:04.887 [PassFF.background] Awaiting tab init... 88 https://www.bitcoin.de/en/login util.js:66:9
11:36:04.903 [PassFF.background] Tab init done 88 https://www.bitcoin.de/en/login util.js:66:9
11:36:05.717 [PassFF.background] Awaiting tab init... 88 https://www.bitcoin.de/en/login util.js:66:9
11:36:05.833 Error: WebExtension context not found!
ExtensionParent.jsm:1039:13
11:36:06.272 [PassFF.background] Message Preferences.getBrowserCommand received in background util.js:66:9
11:36:06.553 [PassFF.background] Message Pass.loadItems received in background util.js:66:9
11:36:06.659 [PassFF.background] Message Preferences.getKeyboardShortcut received in background util.js:66:9
11:36:06.675 [PassFF.background] Tab init done 88 https://www.bitcoin.de/en/login util.js:66:9
11:36:07.504 Error: WebExtension context not found!
ExtensionParent.jsm:1039:13
11:36:09.070 [PassFF.content] 2 matches for https://www.bitcoin.de/en/login util.js:66:9
11:36:09.073 [PassFF.content] Best fit item bitcoin.de/XXXXXX for https://www.bitcoin.de/en/login util.js:66:9
11:36:09.078 [PassFF.content] Inject icon login_username util.js:66:9
11:36:09.079 [PassFF.content] Inject icon login_password util.js:66:9
11:36:09.100 [PassFF.background] Message Page.goToAutoFillPending received in background util.js:66:9
11:36:09.238
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:3
```

### General information. Describe your environment

- Versions
  - Operating system: Linux
  - Browser: Firefox 65
  - PassFF: 1.6.3
  - Host app: 1.1.0+ (master)

Status line output: [11:45:12] show -> (0) no error message

**Comment by LucidOne** [comment]
### Debugging
Which linux distro are you running?
Do you have `pass-otp` installed?
Does it work for other sites?
Which hardware token are you using?
Is is submitting the form?
Does the light on the hardware token flash?
What other extensions do you have installed?
Are there any trailing characters in the otpauth:// ?

### Possible bugs
`11:36:05.833 Error: WebExtension context not found!`
https://bugzilla.mozilla.org/show_bug.cgi?id=1447806
https://bugzilla.mozilla.org/show_bug.cgi?id=1390715#c9

Feel free to @LucidOne for OTP related issues.

**Comment by madduck** [comment]
Hey @lucidone, thank you for taking the time to respond.

I am running Debian unstable.

OTP works from the command line.

It does not work for any site for which there is an otpauth line in the record.

I do not have a hardware token on this machine

It is not submitting and not even filling the form.

I do have lots of extensions installed. However if I remove the otpauth line, then it works. Please save me the trouble of disabling all extensions.

There are no trailing spaces on the otpauth line.

**Comment by LucidOne** [comment]
> Host app: 1.1.0+ (master)

Can you provide the output of 
grep VERSION ~/.mozilla/native-messaging-hosts/passff.py
or the equivalent.

> Hey @LucidOne, thank you for taking the time to respond.

I just wish github had better issue tagging and notifications

> I am running Debian unstable.

I'm out of the office at the moment but if we can't figure this out by Monday, I'll try replicating your environment.

> OTP works from the command line.

with `pass-otp` correct?

> It does not work for any site for which there is an otpauth line in the record.
> 
> I do not have a hardware token on this machine
> 
> It is not submitting and not even filling the form.
> 
> I do have lots of extensions installed. However if I remove the otpauth line, then it works. Please save me the trouble of disabling all extensions.
> 
> There are no trailing spaces on the otpauth line.

This along with the error message you provided makes me thing it is an issue with the connection to the host app.

Can you try something like the example below, replacing 0x19 with the number of characters in the pass file you are trying to open. 0x19 -> 25 characters in `["otp","/www/github.com"]`
```
$ echo -e "\x19\x00\x00\x00[\"otp\",\"/www/github.com\"]" | /path/to/passff.py | tail -c +4; echo
{"exitCode": 0, "stderr": "", "stdout": "123456\n", "version": "1.0.1"}
```

**Comment by madduck** [comment]
> grep VERSION ~/.mozilla/native-messaging-hosts/passff.py

VERSION = "testing"

> with pass-otp correct?

Yes.

Here is the output of the direct interaction with the host app you were asking for:

```
% echo -e "\x1c\x00\x00\x00[\"otp\",\"github.com/madduck\"]" | ~/.mozilla/native-messaging-hosts/passff.py | tail -c +4; echo 
{"stdout": "123456\n", "version": "testing", "stderr": "gpg: WARNING: server 'gpg-agent' is older than us (2.1.18 < 2.2.12)\n", "exitCode": 0}
```

I do not think that the `stderr` output is a problem. I was running Debian stable previously, but I just upgraded, which is why this error now pops up.

The thing that makes me wonder is that if this were a problem between Firefox and the host app, then why does it work in all cases, except for those where the record has an `otpauth://` line? And if I remove this line, then login/password filling works again. This makes me think that the issue is actually in the host app…

**Comment by LucidOne** [comment]
Try setting `VERSION = "1.6.3"`, I'm not sure the semver check returns true for "testing" > "1.6.3"

I'm not sure about the gpg warning, but there may be a codepath that checks that stderr=="", even if the exit code is 0.

**Comment by madduck** [comment]
I can confirm that setting the Version explicitly does seem to fix this. Great spot!

**Comment by 5bentz** [comment]
The semver module raises an error for "testing" (and that's correct behavior). See PR #393 for the fix.
