### ISSUE TITLE
Possible problem with leaking data through autofill

### ISSUE THREAD

**Issue by heyarne** [passff/passff#396]
I am using Nextcloud News as my RSS feed reader and noticed my password leaking to feeds that I subscribed to. I voiced this issue in the Nextcloud News repository and they pointed towards a potential problem with PassFF that has caused this. The relevant issue is here: https://github.com/nextcloud/news/issues/419

The details are unfortunately a bit complicated; on question that arose and might be easy to answer is: Is it possible that PassFF filled forms that were not in the DOM?

Thanks in advance! Also thanks for the addon, I use and enjoy it a lot. 🙌

**Comment by tuxor1337** [comment]
The auto-fill feature is a security issue since it will fill in all form fields that look like fields from a login form. That's why this feature is deactivated by default. And that's why there's an anti-phishing option that warns you before data is filled in on URLs that don't match the exact URL stored in the password store.

If you don't like that, don't activate the auto-fill feature.

**Comment by heyarne** [comment]
I didn't mean the auto-fill feature, I am talking about Ctrl+Y or Right-Click-and-Fill. I'm not auto-filling forms.

**Comment by tuxor1337** [comment]
If auto-fill is disabled no data is filled in without explicit user interaction. Especially when you are already logged in to your NextCloud, you wouldn't want to fill in your credentials anywhere, would you?

**Comment by gutierri** [comment]
But CTRL + Y, would not it be the same as auto-fill, but without the step of clicking the password?
For PassFF, it will search its respective fields to fill, clicking on the password or with the auto-fill-in.

**Comment by tuxor1337** [comment]
As I said, please provide step by step instructions on how to reproduce the issue that you describe.

**Comment by tuxor1337** [comment]
I'm closing this due to missing information and inactivity. Please reopen with clear step by step instructions how to reproduce if this is still an issue for you.
