### ISSUE TITLE
Changing keyboard shortcut through "Manage Extension Shortcuts" does not keep setting

### ISSUE THREAD

**Issue by patrickrst** [passff/passff#397]
### General information. Describe your environment

- Versions
  - Operating system: Debian buster/sid
  - Browser: Firefox 66.0
  - PassFF: 1.6.3
  - Host app: 1.1.0

---

### Actual behaviour

In Firefox 66, there is a new way to manage extension shortcuts from the `about:addons` page. When changing passff shortcut from there, the shortcut is reverted back to the one defined in the settings. If will only work once, then revert.

### Expected behaviour

The shortcut defined in "Manage Extension Shortcuts" should be synchronize or replace the one in passff settings.

**Comment by 5bentz** [comment]
I tested 1.7.0 (after the fix) and 9e9d6163 (before the fix).
I confirm it fixed the problem for me.

Firefox 67.0b12
