### ISSUE TITLE
PassFF disabled in Firefox 66

### ISSUE THREAD

**Issue by pbryan** [passff/passff#404]
### General information. Describe your environment

- Versions
  - Operating system: Linux 4.19.0-4-amd64
  - Browser: Firefox 66.0.1
  - PassFF: 1.7.0

### Issue

Under about:addons, PassFF is now listed as Unsupported. "PassFF could not be verified for use in Firefox and has been disabled." Contains link to: https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

**Comment by tuxor1337** [comment]
Cannot reproduce. Please produce step by step instructions on how to reproduce.

**Comment by pbryan** [comment]
Attempted to install PassFF from https://addons.mozilla.org/en-US/firefox/addon/passff/, got error "Download failed. Please check your connection. Suspected bad Firefox build; reverted to Firefox-ESR 60.0.1esr-1; same problem downloading. Suspect this is on my side or my distro. Closing.

**Comment by tuxor1337** [comment]
Maybe this is related to this Firefox bug in the Add-On signing process: https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

**Comment by 5bentz** [comment]
> A formal post-mortem [will be released] next week

* [Technical Details on the Recent Firefox Add-on Outage](https://hacks.mozilla.org/2019/05/technical-details-on-the-recent-firefox-add-on-outage/)
