### ISSUE TITLE
Auto-fill icon does not list any entry

### ISSUE THREAD

**Issue by xttjsn** [passff/passff#405]
### General information. Describe your environment

- Versions
  - Operating system: 
  - Browser: Linux xttjsn-Surface-Book-2 4.19.18-surface-linux-surface
    #48 SMP Mon Jan 28 19:30:08 EST 2019 x86_64 x86_64 x86_64
    GNU/Linux

  - PassFF: 1.7.0
  - Host app: 1.1.0

Status line output:
  [14:21:49] ls -> (0) no error message

- Output of `pass`:
Password Store
├── <item1>
├── <item2>
...

- Your preferences
  - In PassFF:
  Autofilling:
     - [Checked] Try to auto fill page login forms
     - [Unchecked] Try to submit page login forms
     - Don't auto fill is tab's URL contains one of the strings
       [Empty]
     - [Checked] Warn about potential..

  - In the host app `passff.py`:
     Default preference (honestly I don't know I can change preference
     of the host app)
- Messages in the web console: 
  Nothing related to passff

---

### Actual behaviour
I added the following entry using the QtPass front end
```
<password>
login: <login>
url: <url>
```
I verified later by decrypting the .gpg file that the content is
indeed such format.

When I go to the login page (i.e. the URL matches exactly, including
https://), I click the passff icon for the login field, and it shows
`No entries matching this URL.` I click the passff icon for the
password field, and it shows `No entries matching this URL.`.

### Expected behaviour
It shouls show my login and password.

### Steps to reproduce the behaviour
1. Create the login, url, password entry using pass (or front end for pass).
2. Go to the web page.
3. Click the passff icon for either the login and password field.

**Comment by tuxor1337** [comment]
The suggestions are based on the password store entry's name (and not the URL field inside the entry) unless you activate the preference "Index URL fields on startup". Note that this preference requires you to update the host app to 1.2.0.

**Comment by tuxor1337** [comment]
Closing this with regard to the docs: https://github.com/passff/passff#improve-suggestions
