### ISSUE TITLE
Support for OTP using File-structure format

### ISSUE THREAD

**Issue by cole-h** [passff/passff#407]
Hello! I'm in the process of switching from KeePassXC to `pass`, but I plan on having my logins organized in a slightly strange manner. I have a few categories of logins (eg Gaming, Internet, etc.) and will then organize those based on domain name. Each login will then have its folder name be the username, and have sub-files such as `password`, `notes`, etc., to closely mimic the organization of my KeePass database.

According to the README, "The file structure approach does not support custom input fields or OTP Auth" (and I can vouch for the fact that it does not seem to work for me). I wonder if there's any technical reason for that, and if not, how I can try to convince somebody to fix this? I'd give it a shot myself, but Javascript is way outside my knowledgebase.

Maybe support could be added for an `otp` file, if it is too difficult to get the `otpauth://` from the `password` file?

**Comment by tuxor1337** [comment]
There's already a PR for that and we are looking for a tester! Please have a look here: https://github.com/passff/passff/pull/406

**Comment by cole-h** [comment]
Will get right on that! Just to clarify: do you know if that supports the `otpauth://` being in the `password` file, or does it have to be a separate file, e.g. `otp`?

**Comment by tuxor1337** [comment]
It has to be a separate `otp` file, since it is assumend that the two things are not mutually exclusive.

**Comment by tuxor1337** [comment]
Closed by #406

**Comment by cole-h** [comment]
@tuxor1337 If you aren't already in the process of it, would it be possible to get a release so I don't have to continue loading the `manifest.json` manually?

**Comment by tuxor1337** [comment]
Version 1.8 is on AMO ;)
