### ISSUE TITLE
Blacklist files/folders in database

### ISSUE THREAD

**Issue by cole-h** [passff/passff#409]
Once again, my unorthodox organizational pattern strikes again.

Would it be possible to blacklist certain paths in the password database? I imported everything from my KeePass database, but don't necessarily want suggestions for my `notes` file, or files in my imported `attachments/*` folder cluttering up the login dropdown.

Sorry for being so needy, but I appreciate the help!

**Comment by tuxor1337** [comment]
I merge this with #401 if you don't mind....

**Comment by cole-h** [comment]
I guess I need some glasses. I swear I looked for duplicates.
