### ISSUE TITLE
Displaying password window while in OS X fullscreen

### ISSUE THREAD

**Issue by rnkn** [passff/passff#411]
### General information. Describe your environment

- Versions
  - Operating system: macOS Mojave 10.14.5 (18F132)
  - Browser: Firefox 67.0 (64-bit)
  - PassFF: 1.8
  - Host app: 1.1.0

Status line output: `[15:33:03] show -> (0) no error message`

- Output of `pass`: haha nice try.

---

### Actual behaviour

When in fullscreen in Firefox, clicking PassFF icon > hostname > Display results in the popup going fullscreen in another space.

### Expected behaviour

It would be great if the popup would only hover above the fullscreen window, like Firefox's Download (⌘J) or Page Info (⌘I) popup windows. Not sure if this is a Firefox limitation though.

### Steps to reproduce the behaviour
1. buy a Mac
2. open Firefox
3. enter fullscreen
4. navigate to a website with a password save in pass
5. click PassFF > website hostname > Display

**Comment by 5bentz** [comment]
> buy a Mac

haha nice try.
Cannot reproduce on Debian testing, Firefox 68.0b4 (64-bit) :(

**Comment by rnkn** [comment]
Yeah I think this is likely related to the OS X fullscreen behaviour. I don't suppose there are any obvious flags for window creation that prohibit that window going fullscreen?

**Comment by rnkn** [comment]
I had a thought... what about if the password display was shown within PassFF's same menu popup? That would look quite nice.

**Comment by tuxor1337** [comment]
The menu popup is not permanent. When the user clicks anywhere else, it's destroyed. If the user wants to display an entry to copy several parts of it, he will have to invoke the display again and again. 

Alternatively, we would need to restore the entry display after the popup is destroyed. But then the user has to consciously quit that display view. However, most users will expect the sensitive data view to be closed together with the popup. And then that's a possible breach.

**Comment by rnkn** [comment]
> With the current solution, the display dialog is always on top and therefore it's unlikely that the user forgets to close it.

Ah I see. This isn't actually the case on macOS, the window just displays like any other, and when you click back on the main browser window to enter the password, the window with the password data is necessarily hidden by the main window. This is compounded when using Firefox in fullscreen, as per the original issue, because the window with password data will *also* display in fullscreen, albeit in another desktop space, which, once you switch away from it, remains unseen until specifically navigating back to that desktop space, making it quite easy to forget about.

So I guess if security is the concern with the window display, this issue should become a security issue too?

**Comment by tuxor1337** [comment]
The documentation doesn't really guarantee that popups remain on top and there doesn't seem to be an alternative way to enforce that. Hence, the "official" behavior is that the dialog is not forced to be on top - and the behavior on Mac is according to that "official" behavior. ;-)

**Comment by tuxor1337** [comment]
I don't think that there is anything we can do about this unless something changes upstream.

Feel free to reopen if you know a different extension which has a nice UI from which we could learn.
