### ISSUE TITLE
Different sort for toolbar menu and input popup

### ISSUE THREAD

**Issue by shtrom** [passff/passff#413]
### General information. Describe your environment

- Versions
  - Operating system: OSX / Linux
  - Browser: Firefox latest
  - PassFF: 1.9
  - Host app: 1.2.1

### Actual behaviour
* With `Index URL fields on startup`
* In the toolbar menu, some entries that have the URL for the currently visited site in the file are shown higher up than others, as expected
* In the P popup menu on `input` fields, the entries don't seem to have been sorted in the same way.

### Expected behaviour
* The P popup menu on `input` fields should have the same suggested entries and sort as the contextual list in the toolbar menu

### Steps to reproduce the behaviour
1. Check`Index URL fields on startup` in the config
2. Have a few entries in `pass`, some of them without a close match to a URL, but with a `url: ` field in that file
3. Restart everything
4. Visit that particular URL
5. The toolbar menu shows the entry towards the top of the list, the P popup menu doesn't

**Comment by tuxor1337** [comment]
This should have been fixed with the latest commit.
