### ISSUE TITLE
Focus stuck to status line after pressing the down arrow key

### ISSUE THREAD

**Issue by tillschaefer** [passff/passff#414]
### General information. Describe your environment

- Versions
  - Operating system: Gentoo Linux 
  - Browser: Firefox 67.0.4
  - PassFF: 1.9
  - Host app: 1.0.1

Status line output: [18:55:16] show -> (0) no error message

---

### Actual behaviour
When pressing the down arrow after calling pass with ctrl+y, the focus moves to the status line. A cursor is visible in the status line which can be moved to the left and right with the arrow keys. Pressing the up or down arrow does not move the focus to the entry list again, i.e., the focus is stuck. The problematic part is, that the entry selection is not possible (with keyboard) while the focus is stuck in the status line. 

### Expected behaviour
The up an down arrows should only select the entries and the focus should never move to the status line.

**Comment by tuxor1337** [comment]
Hm, I can't reproduce this with Firefox 67.0.4 on Fedora 30 with Wayland. Are you running Firefox on X or on Wayland? And are you able to reproduce this on a clean Firefox profile?

**Comment by tillschaefer** [comment]
The error is not reproducible using a clean profile. 

Still, I wonder what is causing the Problem, since the error occurred on 4 different machines (all synced via Firefox sync). Thus, fixing the problem would also mean to abandon all my sync data.

**Comment by tuxor1337** [comment]
You are saying that the focus is in the status bar? So, did you try deactivating the status bar in the PassFF preferences? Since the status bar is a pure HTML `<div>` element that is not editable, it should never get the focus anyway. That's really strange...

**Comment by tillschaefer** [comment]
Disabling the status bar did not resolve the issue (but hides the blinking cursor)

**Comment by tuxor1337** [comment]
Please try deactivating all other extensions.

**Comment by tillschaefer** [comment]
disabling all other extensions does not resolve the issue

**Comment by tuxor1337** [comment]
Thanks for your feedback! Unfortunately, I'm running out of ideas for a remote diagnosis. If you happen to run into this problem in a reproducible setup, let us know!

**Comment by tuxor1337** [comment]
@tillschaefer Is this still an issue? Have you been able to reproduce this?

**Comment by tillschaefer** [comment]
I am no linger using passff. Thus, I am no longer able to provide feedback here. Closing for this reason.

**Comment by ZerdoX-x** [comment]
@tuxor1337 i have encountered this issue today after upgrading all of my system packages :(

Hyprland WM (wayland)
Gentoo (+Asahi) Linux on M1 laptop
LibreWolf 118.0.2 (interesting thing that i did not update browser, but issue appeared)

**Comment by ZerdoX-x** [comment]
Issue was caused by my profile. I wanted to debug extension using web-ext and saw that in clean profile issue disappears

I did huge cleanup of my profile, config options and my configurations and it's all good now. Sadly I was too lazy to determine which option caused this bug ;)
