### ISSUE TITLE
PassFF dropdown fails to fill content

### ISSUE THREAD

**Issue by cole-h** [passff/passff#417]
### General information. Describe your environment

- Versions
  - Operating system: Linux
  - Browser: Firefox Nightly 70.0a1 (2019-07-20 and 2019-07-27)
  - PassFF: 1.9
  - Host app: 1.2.1

- Status line output:
`[17:31:49] otp -> (0) no error message`

- Messages in the web console:
(cleared before force-refreshing the page and trying to fill in login credentials)
```
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Error: WebExtension context not found!
Security Error: Content at https://github.com/login may not load or link to moz-extension://--%<----/content/content-popup.html.
```

---

### Actual behaviour
Logins no longer fill when selecting from the dropdown.

### Expected behaviour
Usernames, passwords, and OTP codes should be filled.

### Steps to reproduce the behaviour
0. Launch Firefox Nightly and verify PassFF is installed
1. Navigate to any login page you have credentials saved for
2. Attempt to fill the username and password fields
3. Fail

For what it's worth, I fresh-installed both the host application and the
extension, and this problem still exists. My thinking is that it's somehow
related to the new, built-in password manager Firefox Nightly is shipping with.
The issue is still present on a fresh Nightly profile.

**Comment by tuxor1337** [comment]
The warning about content security policy is alarming. Currently, we are injecting an iframe to render the icon menu: https://github.com/passff/passff/blob/master/src/modules/page.js#L327 This didn't cause a Security Error up to now - but this seems to have changed in Firefox Nightly.

However, the actual issue that you describe may well be caused by something completely different.

**Comment by cole-h** [comment]
FWIW, I don't think it's related to Content Security Policy (CSP), because toggling `security.csp.enable` to `false` doesn't fix the problem. The Security Error is always there, but the CSP error only is there sometimes.

The iframe, however, does seem to be the issue. Filling username and password works from the `C-y` menu, but it doesn't fill OTP codes (at least on GitHub).

----

Somewhat unrelated, but since we support OTP, could I ask you to add a "Copy otp" to the entry interactions, similar to the already-present "Copy login" and "Copy password"? Otherwise I have to whip up a terminal to `pass otp <entry>` instead of just copying it while the dropdown is broken.

**Comment by tuxor1337** [comment]
Regarding "Copy OTP": Technically a good idea. However, either you implement it yourself or you open a new issue. Otherwise it will move out of sight soon since this is not the right place to ask.

**Comment by cole-h** [comment]
As of version `71.0a1 (2019-10-14)`, the popup now consists of only a thin line (see attached picture).

![image](https://user-images.githubusercontent.com/28582702/66795715-4a562c80-eeba-11e9-88b9-5a21005848c1.png)

Console output is similar, but has slightly changed:
```
Security Error: Content at https://github.com/login may not load or link to moz-extension://--%<----/content/content-popup.html.
SecurityError: The operation is insecure.
```

The last line of the above log links to https://github.com/passff/passff/blob/17ca3df8b96d4c72ed0d70602a2c8221b7b45c35/src/modules/page.js#L362

**Comment by tuxor1337** [comment]
For the empty dropdown, see here: https://github.com/passff/passff/issues/421

**Comment by smoyer64** [comment]
71 will be going GA soon ... is there a time-line for cutting a release with this fix?

**Comment by tuxor1337** [comment]
Thanks for the reminder! Version 1.9.1 is now available.

**Comment by smoyer64** [comment]
Wow, that was fast! ... I just didn't want to see all the non-ESR users break at once but I will definitely take advantage of it immediately since you've tagged/released it.
