### ISSUE TITLE
Prompt to save just inserted credentials

### ISSUE THREAD

**Issue by alxlg** [passff/passff#418]
When I login into a website with new credentials I don't get any prompt to save them into Pass. It is expected? Do I have to insert them manually in Pass specifying the URL scope?

**Comment by tuxor1337** [comment]
Yes, you have to manually add new credentials and specify the URL manually.

I'm interpreting this as a feature request.

**Comment by alxlg** [comment]
Also if it's not possible to get the credentials, just adding the current domain when clicking "add new password" would be very useful. At the moment I use an external app to add a password specifying the domain.

**Comment by tuxor1337** [comment]
There already exists a feature request for prefilling the "add new password" dialog: https://github.com/passff/passff/issues/380

**Comment by tuxor1337** [comment]
Closing as duplicate of #380 (and due to inactivity).

It seems to me like generally intercepting the form data whenever a login form is submitted would not be a very desirable feature for PassFF. This might affect security and trustworthiness of the extension.
