### ISSUE TITLE
passff select dropdown draw issues (0 height box?) on newest firefox-developer-edition

### ISSUE THREAD

**Issue by mschrupp** [passff/passff#421]
### General information. Describe your environment

- Versions
  - Operating system:  arch linux / gnome 3.34.1
  - Browser: Firefox Developer Edition 71.0b1 (64-Bit)
  - PassFF: 1.9
  - Host app:  1.7.3

Status line output: `[07:54:37] show -> (0) no error message`

Web console:

```
[PassFF.content] 1 matches for http://192.168.0.1/ util.js:66:14
[PassFF.content] Best fit item 192.168.0.1 for http://192.168.0.1/ util.js:66:14
[PassFF.content] Inject icon uiPass util.js:66:14
```
---

### Actual behaviour
The dropdown at the input form doesn't show up - it only shows a single line where the box should appear. It looks like a zero-height box.

See the image [here](https://i.imgur.com/YXiLfVh.png). The dark grey line below the form field looks like the selection box, but with 0 height.

I can't find any error anywhere.

When I select an item from the dropdown directly at the addon icon next to the URL bar, it works.

**I think the error occured after an upgrade from `firefox-developer-edition` 70.0b14 to 71.0b1, but I'm not 100% sure**

I didn't update `pass` and `passff-host` since may or so (all up-to-date still)

### Expected behaviour
The select box should be drawn correctly. 

### Steps to reproduce the behaviour
1. Install everything in the newest version
2. Try to select an item on any website
3. The box doesn't get drawn (or only with 0 height)

**Comment by xomit** [comment]
I can confirm, that the behavior described by mschrupp has started with the update to Firefox 71.0. I'm currently running Firefox 71.0b3 (64-bit) on Debian Testing, Passff (1.9, June 25, 2019) and passff.py 1.2.1

**Comment by felix** [comment]
After today's update to Firefox 71.0b5 (64-bit) it seems to have fixed itself and now displays the dropdown correctly.

**Comment by cole-h** [comment]
This issue is gone for me as well on Firefox Nightly 72.0a1 (2019-11-25). Dropdowns now properly list matching logins.

**Comment by tuxor1337** [comment]
Okay, thanks for the reports! Closing this until further notice.
