### ISSUE TITLE
Fill-from-menu does not work for OTP fields

### ISSUE THREAD

**Issue by madduck** [passff/passff#423]
### General information. Describe your environment

- Versions
  - Operating system: Debian unstable
  - Browser: Firefox 70
  - PassFF: 1.9
  - Host app: 1.2.1 (967803b03e0de919cf6fe3a099afe6561ac8199d)

Status line output: `[14:01:49] otp -> (0) no error message`

---

### Actual behaviour
Filling in a form from the menu works for login name and password, but not for OTP fields. Using the (P) icon on those does fill in the OTP token.

### Expected behaviour
OTP fields should be filled with the OTP token if I select "Fill" from the menu.

### Steps to reproduce the behaviour
Login in to e.g. `bitcoin.de` and when asked to provide the OTP code, navigate the pass menu, and select "Fill". Observe nothing happening. Click on the (P) in the field and select the right entry, and watch the OTP code being entered.

**Comment by lkhd** [comment]
Can confirm it does not autofill OTP like it does usernames and passwords.

**Comment by tylerwolf35** [comment]
Just installed PassFF and I am having this same error. Is there a fix by any chance?

**Comment by tylerwolf35** [comment]
I have noticed that with an incorrect URI token, you get the error while displaying, yet no error with a correct URI token.

**Comment by tuxor1337** [comment]
Fixed by #548
