### ISSUE TITLE
Autofill Fails When There Are Two Entries With Same URL but Different Ports

### ISSUE THREAD

**Issue by JiaHong-Lee** [passff/passff#424]
### General information. Describe your environment

- Versions
  - Operating system: `lsb_release -a`:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

  - Browser: 70.0.1 (64-bit)
Mozilla Firefox for Ubuntu
canonical - 1.0

  - PassFF: 1.9

  - Host app: v1.7.1

---

### Actual behaviour
Given that I have two entries on same url but different ports, e.g. local-server:5000 and local-server:8384, PassFF fails to autofill the username and password form.

### Expected behaviour
PassFF should be able to differentiate between two websites on different ports even though they are on the same URL.

**Comment by tuxor1337** [comment]
Please provide step by step instructions on how to reproduce.

**Comment by tuxor1337** [comment]
I'm closing this due to missing information and inactivity. Please reopen with clear step by step instructions how to reproduce if this is still an issue for you.
