### ISSUE TITLE
Passff shows empty password store

### ISSUE THREAD

**Issue by alexDarcy** [passff/passff#426]
### General information. Describe your environment

- Versions
  - Operating system: Archlinux with kernel  5.3.12
 - Browser: firefox 70.01 64-bits
  - PassFF: 1.9.1
  - Host app: 1.2.1

Status line output: `[12:06:14] ls -> (0) no error message`

- Output of `pass`: 
- Your preferences : i did not modify this. 
  - `passff.json` for reference
    {
      "name": "passff",
      "description": "Host for communicating with zx2c4 pass",
      "path": "/home/alex/.mozilla/native-messaging-hosts/passff.py",
      "type": "stdio",
      "allowed_extensions": [ "passff@invicem.pro" ]
    }
  - `passff.py` for reference
    VERSION = "1.2.1"
    ###############################################################################
    ######################## Begin preferences section ############################
    ###############################################################################
    COMMAND = "/usr/bin/pass"
    COMMAND_ARGS = []
    COMMAND_ENV = {
        "TREE_CHARSET": "ISO-8859-1",
        "PATH": "/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/alex/.local/bin:/home/alex/.emacs.d/bin/:/home/alex/.local/bin:/home/alex/.emacs.d/bin/:/home/alex/.local/bin:/home/alex/.emacs.d/bin/"
    }
    CHARSET = "UTF-8"
    
    ###############################################################################
    ######################### End preferences section #############################
    ##############################################################################
  - In PassFF: 
  - In the host app `passff.py`: 
- Messages in the web console: 
[PassFF.content] 0 matches for https://zimbra.free.fr/ util.js:66:14
[PassFF.content] Inject icon login util.js:66:14
[PassFF.content] Inject icon password util.js:66:14
[PassFF.content] Start pref-auto-fill
---

### Actual behaviour
The list of password in passff is empty.
`Pass show` works in my terminal. There is no error on pass-ff side inside firefox.
Result of `echo -e "\x02\x00\x00\x00[]" | ~/.mozilla/native-messaging-hosts/passff.py  |  tail -c +4`

    {"exitCode": 0, "stdout": "Y7g@Of\"-'6#*+KwA\n", "stderr": "", "version": "1.2.1"}⏎ 

There is no auto-filling, nor any results using the search methods.
I've installed passff using the official instructions (curl and latest version, that is 1.2.1). There is no other install of passff.

### Expected behaviour
List all the passwords in my pass wallets.

### Steps to reproduce the behaviour
1. Start firefox
2. Search a password in the popup menu

Thanks !

**Comment by Eragonfr** [comment]
Same but with ArtixLinux(Archlinux based), Linux Kernel : 5.4.2
Browser: firefox nightly 73.0a1 (2019-12-08)
PassFF : 1.9.1
Host app : 1.2.0

**Comment by dziq** [comment]
Working after upgrade to firefox-71.0_2 on Void Linux.

**Comment by tuxor1337** [comment]
Do I understand correctly, that the command `echo -e "\x02\x00\x00\x00[]" | ~/.mozilla/native-messaging-hosts/passff.py | tail -c +4` does not contain the contents of your password store?

**Comment by alexDarcy** [comment]
@tuxor1337 It returns a generated password, identical to the output of the `pass` command in a terminal without any arguments.

I do not know how to test my store using `passff.py`  on the command line unfortunately.

**Comment by tuxor1337** [comment]
According to the documentation, `pass` is equivalent to `pass ls`, so it should not return a generated password. Or am I missing something?

**Comment by Eragonfr** [comment]
It return exactly 
`{"exitCode": 0, "stdout": "om#/-;!\\n5FgE6.6Qlbtvx\n", "stderr": "", "version": "1.2.1.r0.967803b"}`
and `om#/-;!\\n5FgE6.6Qlbtvx\n` is not in any password file in my password store

**Comment by alexDarcy** [comment]
@tuxor1337 `pass`, `pass ls` and `pass show` without argument return a generated password on my system. With an argument, it returns the password for the given website.

**Comment by tuxor1337** [comment]
Which version of pass is this? I cannot confirm this with pass 1.7.3.

**Comment by Eragonfr** [comment]
I'm using 1.7.3

**Comment by tuxor1337** [comment]
Then you are using a modified version of pass. According to the source code, running "pass show" will return the password store tree (unless you have a file called `.gpg` at the root of your password store): https://git.zx2c4.com/password-store/tree/src/password-store.sh#n366

**Comment by Eragonfr** [comment]
I'm using the official build from Archlinux repository, but... i have a `.gpg` at the root of my password store.

**Comment by tuxor1337** [comment]
In that case, you should remove that file.

**Comment by Eragonfr** [comment]
It still not working, but now `echo -e "\x02\x00\x00\x00[]" | /usr/lib/mozilla/native-messaging-hosts/passff.py | tail -c +4` return a list of all files in my password store

**Comment by tuxor1337** [comment]
Did you restart firefox?

**Comment by Eragonfr** [comment]
Yes

**Comment by tuxor1337** [comment]
Okay, but you said you are on Firefox 73, right? This doesn't seem to be the case for @alexDarcy and we can't be sure that we're still talking about the original issue.

**Comment by alexDarcy** [comment]
@tuxor1337 After removing all `.gpg`files, it works fine for me (I even had a `.gpg` without a basename...). Thanks for the follow-up !

**Comment by Eragonfr** [comment]
It's clearly not the same bug, i'm on Firefox 73 yes. Do i need to open a new  issue ?

**Comment by tuxor1337** [comment]
@Eragonfr I tried PassFF 1.9.1 with Firefox 73.0a1 and everything is working fine. I'm closing this. Please open a bug report with more information about the exact setup.

**Comment by Eragonfr** [comment]
@tuxor1337 I've an old version of passff host app, so I have updated it and now all work fine
