### ISSUE TITLE
Empty name whene generating a new password breaks the password store.

### ISSUE THREAD

**Issue by RobinVanhove** [passff/passff#429]
### General information. Describe your environment

- Versions
  - Operating system: Linux
  - Browser: Mozilla Firefox 71.0
  - PassFF: 1.9.1
  - Host app: 1.2.0 (AUR package)

### Actual behaviour
When generating a new password using the passff add-on the default for the name is `/`. The generating process calls `pass generate ls` (or something similar) which creates a file `.gpg` in the password store dir. 
This file essentially breaks pass since `pass ls` will just return the generated password and not the list. As a result also the passff.

### Expected behaviour
Generating a new password should never break the pasff or pass itself.

### Steps to reproduce the behaviour
1. Create a new password using passff
2. Ensure `/` is used as name
3. Passff is no longer usable

**Comment by tuxor1337** [comment]
I can confirm this behavior, but it's an upstream bug. Please report to the pass project.

**Comment by tuxor1337** [comment]
Fixed upstream https://lists.zx2c4.com/pipermail/password-store/2019-July/003692.html

**Comment by valentino-sm** [comment]
> I can confirm this behavior, but it's an upstream bug. Please report to the pass project.

Is this correct behaviour ?
Having `/` in name input everywhere.

Seems like there should be url autofilling.
