### ISSUE TITLE
Filling with pass file structure ask to unlock more than once

### ISSUE THREAD

**Issue by kayceegb** [passff/passff#430]
### General information. Describe your environment

- Versions
  - Operating system: Slackware 14.1
  - Browser: FF 68.3.0esr
  - PassFF: 1.9.1
  - Host app: 1.2.1

Status line output: [13:41:54] show -> (0) no error message

- Output of `pass`:
pass cat/site/
cat/site
|-- login
`-- passwd
- Your preferences
  - In PassFF: Default except just "Fill"
  - In the host app `passff.py`: Default
- Messages in the web console: 
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.
login
[PassFF.content] 0 matches for http://rt/login?page_ref=/state/wan util.js:66:14
[PassFF.content] Inject icon login util.js:66:14
[PassFF.content] Inject icon password util.js:66:14
[PassFF.content] Message Page.fillInputs received in content util.js:66:14
[PassFF.content] Start auto-fill using web/rt_1 false util.js:66:14
[PassFF.content] Set inputs... util.js:66:14
---

### Actual behaviour
PassFF with a pass file structure format is asking for unlocking twice with 2 (maybe with more too, not tested) input fields to fill.

### Expected behaviour
Ask to unlock key once to fill all input fields

### Steps to reproduce the behaviour
1. pass structure
- cat/site/login
- cat/site/passwd
2. Go to site
3. Try to fill fields with locked store

**Comment by tuxor1337** [comment]
I can't reproduce this with my current setup (Firefox 71.0 on Fedora 30). Maybe it's a problem with gpg-agent? Usually it should cache passwords for a certain amount of time. Would you please try
```
$ pass /cat/site/login 
$ pass /cat/site/passwd
```
and report back whether you are asked for your credentials twice.

**Comment by kayceegb** [comment]
Hi,

There is no problem using pass in direct. I am asked to unlock for site/login and can see site/password without being asked to unlock again. Caching is working. 

If the store is unlocked, passFF fills the input fields without asking anything. 

I can also add that with store locked, when filling site's inputs, if I enter my key the first time and cancel the second ( I have a "script execution failed" here, for me that seems normal)  then redo the filling, it is working fine without asking anything. So it seems that passFF unlocks the store with the first prompt.

**Comment by tuxor1337** [comment]
Internally, PassFF is calling the two commands I listed above. Nothing more, nothing less. So I can't see a reason why it should behave differently from calling these commands directly from the command line. Furthermore, since I can't reproduce the described behavior, I'm afraid, I can't help you any further at the moment.

**Comment by kayceegb** [comment]
Yes I imagine it is calling those commands. 

But after analysis, isn't passFF calling the second command to quickly ? I mean the first prompt is not completed, so cache is no working yet, and the second command is called without caching, so the second prompt appears after the first one ? 

Isn't it possible to delay the call of the second command after the first one is finished ?

**Comment by kayceegb** [comment]
I retried with debugging enabled for passFF

> [PassFF.menu] Create menu list 
Array(4) [ {…}, {…}, {…}, {…} ]
util.js:66:14
[PassFF.menu] Create children menu list 
Array(4) [ {…}, {…}, {…}, {…} ]
 true util.js:66:14
[PassFF.background] Message Menu.backupState received in background util.js:66:14
[PassFF.menu] Search keydown 40 util.js:66:14
[PassFF.menu] Select first child util.js:66:14
[PassFF.menu] List item keydown 13 util.js:66:14
[PassFF.background] Message Menu.onEnter received in background util.js:66:14
[PassFF.background] Enter press on item web/rt_1 false util.js:66:14
[PassFF.background] Awaiting tab init for Page.fillInputs util.js:66:14
[PassFF.background] Awaiting tab init... 6 http://rt/login?page_ref=/state/wan util.js:66:14
[PassFF.background] Tab init done 6 http://rt/login?page_ref=/state/wan util.js:66:14
[PassFF.background] Executing Page.fillInputs in content script util.js:66:14
[PassFF.background] Message Pass.executePass received in background 2 util.js:66:14
[PassFF.background] Awaiting tab init... 6 http://rt/login?page_ref=/state/wan util.js:66:14
[PassFF.background] Tab init done 6 http://rt/login?page_ref=/state/wan util.js:66:14
[PassFF.background] Awaiting tab init... 6 http://rt/login?page_ref=/state/wan util.js:66:14
[PassFF.background] 0 matches for http://rt/login?page_ref=/state/wan util.js:66:14
[PassFF.background] Tab init done 6 http://rt/login?page_ref=/state/wan util.js:66:14
[PassFF.background] Script execution failed 2 gpg: annulé par l'utilisateur
gpg: échec du déchiffrement : Pas de clef secrète

That shows that Pass.executePass is spawned 2 times  in "background", and from what I have seen, before any prompt is shown. That could explain that behaviour. 

But, you say you are not affected. Do you have any automatic unlocking somewhere maybe ?

**Comment by tuxor1337** [comment]
Yes, PassFF is running the two commands concurrently. A race condition is possible, but the gpg-agent pinentry interface should take care and prevent multiple dialogs from popping up. The behavior of PassFF should be equivalent to this:

```
$ pass /cat/site/login & pass /cat/site/passwd
```

With my setup (pinentry dialog provided by gnome-shell), this does only invoke a single password prompt.

**Comment by kayceegb** [comment]
I agree with the behaviour of passFF exec calling. It is not one command after the other, it is all commands at the same time. 

I come initialy from an old version of passFF. For different reasons, I had to stay with an older version of FF for a time, 52.9.0esr, one with support of old extensions format, so before web extensions. At this time, I used passFF version 0.1.32. With the same pass file structure, for the same site, I remember that to fill both fields, I had just one password prompt. 

I'll try to verify that again. 

But what changed since this time, upgrade of FF, passFF, and that's all if I remember correctly.

**Comment by kayceegb** [comment]
Tested with FF 52.9.0esr and passFF 0.1.32. With that combo, I have only one prompt.

**Comment by tuxor1337** [comment]
The PassFF versions prior to 1.0.0 used a synchronous API for calling commands. But this API is not available in current versions of Firefox.

1. Which pinentry dialog does gpg-agent use in your setup?

2. Would you please test with your setup whether the following command line invokes a single or multiple password prompts?
```
$ pass /cat/site/login & pass /cat/site/passwd
```

**Comment by kayceegb** [comment]
When I started investigating, I was affraid of that asynchronous API with web extensions. :/

1. pinentry-gtk-2 version 0.9.7. 
2. sad to say twice, but in the other hand, that's what I would expect. 

With what you say, it seems that it couldn't be changed from the firefox side. 
In my opinion, the problem is not with pinentry, it is just the last component in the process. With debug informations from gpg-agent, pinentry is not called when the store is unlocked (cache available). 

Which version of gpg do you have ?

**Comment by tuxor1337** [comment]
I'm using GnuPG 2.2.17 and pinentry-gnome3 version 1.1.0.

**Comment by kayceegb** [comment]
There is a difference with my config. I have GnuPG 2.0.22. 

Looking for asynchronous/concurrent execution of gpg/gpg-agent don't let me find anything relevant for the moment. 

I'll retry to bump gnupg version, but last time I had problem making it work.

**Comment by kayceegb** [comment]
I succeeded in installing GnuPG 2.0.31 from Slackware 14.2 without any luck. There were still two prompts. Installing higher from current, ask to make to many changes and potentially to break a lot of things. I will stay with my current setup at this time. 

To mitigate the asynchronous mode, I created a little wrapper to pass then configured passFF to use the wrapper. That is doing the job for the moment.

**Comment by tuxor1337** [comment]
Would you please confirm that the latest commits fix this issue by forcing sequential calls to pass for hierarchical style items?

**Comment by kayceegb** [comment]
Great. I am asked once now :D

FYI, there still remains a little "couac". If you cancel the first prompt, you have a "script execution failed" from firefox and you have the second prompt that comes too. I don't know how it could be managed.

**Comment by tuxor1337** [comment]
You are right. The latest commit deals with this by stopping sequential execution if one call to pass fails.

**Comment by kayceegb** [comment]
Seems good for me ! Thanks
