### ISSUE TITLE
Allow 'right-arrow' to select the fill option

### ISSUE THREAD

**Issue by andrewferguson** [passff/passff#436]
I use passff all the time to manage all my online passwords, and the keyboard shortcuts are really useful to avoid moving from the keyboard to the mouse when searching for a service then clicking on it.

I've noticed that there are a number of websites where the "Fill and submit" option doesn't work - it fills the fields then redirects to an error or 404 page. (Probably an issue with pass miss-identifying the submit button on the website, or the website using poorly-labelled HTML). This isn't a major pain for me, all I need to do is select the 'Fill' option rather than 'Fill and Submit', then manually click the submit button on the login form.

What is a pain, however, is that the passff pop-up allows selection of a service from the "start typing a service name to filter the results" screen using the right-arrow key, but doesn't then allow selection of a Fill option ("Fill", "Fill and Submit", "Goto, fill and submit", etc...) using the right-arrow key. Instead the enter / return key must be used (pressing the right arrow moves the selection up instead).

I know it's a minor thing, but I find myself pressing right-arrow on the Fill option screen all the time. I'd love if the right-arrow was mapped to select the option in that screen as it seems intuitive to me, given that it selects the option in the previous screen.

**Comment by tuxor1337** [comment]
Yes, that sounds reasonable. Thanks for the report!
