### ISSUE TITLE
Extension always says "No entries matching this URL"

### ISSUE THREAD

**Issue by RalfJung** [passff/passff#439]
### General information. Describe your environment

- Versions
  - Operating system: Linux (Debian testing)
  - Browser: Firefox 77.0b6 (64-bit)
  - PassFF: 1.9.1
  - Host app: 1.2.1

Status line output: (not shown even though I have Show a status bar in the toolbar menu enabled)

- Output of `pass`: 
```
Password Store
└── web
    ├── discord.com
    │   └── EMAIL
    └── www.reddit.com
        └── USERNAME
```
- Messages in the web console: 
```
[PassFF.content] 0 matches for https://www.reddit.com/r/rust/
```

---

### Actual behaviour
I added my reddit account as pass file `web/www.reddit.com/$USERNAME`.
Then I went to the reddit website and clicked "log in" and then the PassFF icon.
It just says "No entries matching this URL".

Reddit is just an example here, so far I have not found a website where the extension actually does anything. However, I was able to insert new entries to pass with the extension just fine. (But I am not sure if I did that right -- I expected the extension would automatically fill in the URL for me or so, but nothing like that happened.)

### Expected behaviour
It should offer to fill in my login data.

### Steps to reproduce the behaviour
1. Create `web/www.reddit.com/USERNAME` pass entry with password.
2. Go to reddit.com and click "log in".
3. Click PassFF icon in the login box.

Note: The box when I click the pass icon in the Firefox toolbar is empty except for a few buttons at the bottom -- not sure if that is expected.

**Comment by tuxor1337** [comment]
Thanks for your report. Possibly, it's an incompatibility with Firefox 77. Can you reproduce this with Firefox 76?

> The box when I click the pass icon in the Firefox toolbar is empty except for a few buttons at the bottom -- not sure if that is expected.

This is not expected.

> I expected the extension would automatically fill in the URL for me or so, but nothing like that happened.

Related: https://github.com/passff/passff/issues/380
