### ISSUE TITLE
Fill form without password field (e.g. paypal.com)

### ISSUE THREAD

**Issue by kayceegb** [passff/passff#445]
### General information. Describe your environment

- Versions
  - Operating system: Slackware 14.2 or Manjaro
  - Browser: FF 60.9.0esr or 74
  - PassFF: 1.10.1
  - Host app: 1.2.1

Status line output: `[hh:mm:ss] show -> (0)`

[23:25:23] ls -> (0) no error message

- Output of `pass`: 
- Your preferences
  - In PassFF: defaults except just fill
  - In the host app `passff.py`: defaults
- Messages in the web console: 

[PassFF.content] Message Page.fillInputs received in content
util.js:66:9
[PassFF.content] fillInputs: No password inputs found!
util.js:66:9
[PassFF.content] Message Page.fillInputs received in content
util.js:66:9
[PassFF.content] fillInputs: No password inputs found!
util.js:66:9
[PassFF.content] Message Page.fillInputs received in content
util.js:66:9
[PassFF.content] fillInputs: No password inputs found!
util.js:66:9
[PassFF.content] Message Page.fillInputs received in content
util.js:66:9
[PassFF.content] fillInputs: No password inputs found!
util.js:66:9
[PassFF.content] Message Page.fillInputs received in content
util.js:66:9
[PassFF.content] fillInputs: No password inputs found!
util.js:66:9

---

### Actual behaviour
Describe *objectively* your problem. What happened?

Pass entries do not contain full website names but random names that help me to identify the entries. 

On paypal's login form it's not possible to fill the email form via ctrl-y/select entry/ENTER. See the log below. 
After rename to have a valid paypal.com entry in pass, it's still not possible to fill the form. The same log as above.

### Expected behaviour
What should happen instead?

Form be filled when selecting an entry from pass with a "scrambled" name. 

### Steps to reproduce the behaviour
1. go to https://www.paypal.com/fr/signin
2. add email field to passff's emails fields 
3. try to fill with an entry that do not have website's name in path

Regards,

**Comment by kayceegb** [comment]
Hi,

Oh, I have not been notified for activity on this one :/

I see you marked it as incompatible. Since last time I had time to play a little about this issue. With an entry valid for a domain name, passff seems to be able to trigger something for filling. 
If I click the icon in the field, it's possible to fill the field and even it's possible to go to step 2 automatically. 

How different are these two filling methods ? 

Here come's the log
------ LOG ------
[PassFF.content] 1 matches for https://c.paypal.com/v1/r/d/i?js_src=https://c.paypal.com/da/r/fb.js
util.js:66:9
[PassFF.content] Best fit item web/paypal.com-test for https://c.paypal.com/v1/r/d/i?js_src=https://c.paypal.com/da/r/fb.js
util.js:66:9
XML Parsing Error: no root element found
Location: https://www.paypal.com/auth/verifygrcenterprise
Line Number 1, Column 1:
verifygrcenterprise:1:1
[PassFF.content] Fill active element 
<input id="email" class="hasHelp  validateEmpty   " name="login_email" required="required" value="" autocomplete="username" placeholder="Email ou numéro de mobile" aria-describedby="emailErrorMessage" style="background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 16px; background-position: calc(100% - 4px) 50%; background-image: url(\"moz-extension://17b06039-690c-4801-9c78-a444e1b00de6/skin/icon-light.png\"); cursor: auto;" passff-autocomplete="username" type="email">
util.js:66:9
[PassFF.content] Set inputs...
------ LOG ------

For other's 2 step auth methods, manual filling is working (for example outlook). 

k.

**Comment by kayceegb** [comment]
Hi,

Oh, I have not been notified for activity on this one :/

I see you marked it as incompatible. Since last time I had time to play a little about this issue. With an entry valid for a domain name, passff seems to be able to trigger something for filling. 
If I click the icon in the field, it's possible to fill the field and even it's possible to go to step 2 automatically. 

How different are these two filling methods ? 

Here come's the log
------ LOG ------
[PassFF.content] 1 matches for https://c.paypal.com/v1/r/d/i?js_src=https://c.paypal.com/da/r/fb.js
util.js:66:9
[PassFF.content] Best fit item web/paypal.com-test for https://c.paypal.com/v1/r/d/i?js_src=https://c.paypal.com/da/r/fb.js
util.js:66:9
XML Parsing Error: no root element found
Location: https://www.paypal.com/auth/verifygrcenterprise
Line Number 1, Column 1:
verifygrcenterprise:1:1
[PassFF.content] Fill active element 
<input id="email" class="hasHelp  validateEmpty   " name="login_email" required="required" value="" autocomplete="username" placeholder="Email ou numéro de mobile" aria-describedby="emailErrorMessage" style="background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 16px; background-position: calc(100% - 4px) 50%; background-image: url(\"moz-extension://17b06039-690c-4801-9c78-a444e1b00de6/skin/icon-light.png\"); cursor: auto;" passff-autocomplete="username" type="email">
util.js:66:9
[PassFF.content] Set inputs...
------ LOG ------

For other's 2 step auth methods, manual filling is working (for example outlook). 

k.

**Comment by kayceegb** [comment]
Some addition, trying to fill the login field without password field does not work, however, trying to fill the password field without login field works (in second step) ? Does it sounds ok ?

And, looking closer and after a, for sure, very dirty hack, I'm able to fill the login field. I commented the "return null;" from fillInputs.
I do not have any expertise in this, so what would be the consequences of this modification, in a case where there is no autoSubmit and no autoFill ? 

I have this in logs when filling.
`[PassFF.content] Message Page.fillInputs received in content
util.js:66:9
[PassFF.content] fillInputs: No password inputs found test!
util.js:66:9
[PassFF.content] Message Page.fillInputs received in content
util.js:66:9
[PassFF.content] fillInputs: No password inputs found test!
util.js:66:9
[PassFF.content] Message Page.fillInputs received in content
util.js:66:9
[PassFF.content] fillInputs: No password inputs found test!
util.js:66:9
[PassFF.content] Message Page.fillInputs received in content
util.js:66:9
[PassFF.content] fillInputs: No password inputs found test!
util.js:66:9
[PassFF.content] Message Page.fillInputs received in content
util.js:66:9
[PassFF.content] fillInputs: No password inputs found test!
util.js:66:9
[PassFF.content] Start auto-fill using web/pp false
util.js:66:9
[PassFF.content] Set inputs...
util.js:66:9
[PassFF.content] Start auto-fill using web/pp false
util.js:66:9
[PassFF.content] Set inputs...
util.js:66:9
[PassFF.content] Start auto-fill using web/pp false
util.js:66:9
[PassFF.content] Set inputs...
util.js:66:9
[PassFF.content] Start auto-fill using web/pp false
util.js:66:9
[PassFF.content] Set inputs...
util.js:66:9
[PassFF.content] Start auto-fill using web/pp false
util.js:66:9
[PassFF.content] Set inputs...`

Data is put into field between fillInputs and Start auto-fill. 

K.

**Comment by kayceegb** [comment]
Some addition, trying to fill the login field without password field does not work, however, trying to fill the password field without login field works (in second step) ? Does it sounds ok ?

And, looking closer and after a, for sure, very dirty hack, I'm able to fill the login field. I commented the "return null;" from fillInputs.
I do not have any expertise in this, so what would be the consequences of this modification, in a case where there is no autoSubmit and no autoFill ? 

I have this in logs when filling.

> [PassFF.content] Message Page.fillInputs received in content
> util.js:66:9
> [PassFF.content] fillInputs: No password inputs found test!
> util.js:66:9
> [PassFF.content] Message Page.fillInputs received in content
> util.js:66:9
> [PassFF.content] fillInputs: No password inputs found test!
> util.js:66:9
> [PassFF.content] Message Page.fillInputs received in content
> util.js:66:9
> [PassFF.content] fillInputs: No password inputs found test!
> util.js:66:9
> [PassFF.content] Message Page.fillInputs received in content
> util.js:66:9
> [PassFF.content] fillInputs: No password inputs found test!
> util.js:66:9
> [PassFF.content] Message Page.fillInputs received in content
> util.js:66:9
> [PassFF.content] fillInputs: No password inputs found test!
> util.js:66:9
> [PassFF.content] Start auto-fill using web/pp false
> util.js:66:9
> [PassFF.content] Set inputs...
> util.js:66:9
> [PassFF.content] Start auto-fill using web/pp false
> util.js:66:9
> [PassFF.content] Set inputs...
> util.js:66:9
> [PassFF.content] Start auto-fill using web/pp false
> util.js:66:9
> [PassFF.content] Set inputs...
> util.js:66:9
> [PassFF.content] Start auto-fill using web/pp false
> util.js:66:9
> [PassFF.content] Set inputs...
> util.js:66:9
> [PassFF.content] Start auto-fill using web/pp false
> util.js:66:9
> [PassFF.content] Set inputs...

Data is put into field between fillInputs and Start auto-fill. 

K.

**Comment by tuxor1337** [comment]
> what would be the consequences of this modification, in a case where there is no autoSubmit and no autoFill ?

The consequence would be that stuff is filled in even if there is no login form on the page. But that seems okay to me since the user explicitly requested the fill operation. I decided to go for this option. Thanks for the suggestion!

**Comment by kayceegb** [comment]
Tried the last commit. That seems good for me. It is even faster than what I have seen for my test. 

The log says

> [PassFF.content] Message Page.fillInputs received in content
> util.js:66:9
> [PassFF.content] fillInputs: Warning: no password inputs found!
> util.js:66:9
> [PassFF.content] Message Page.fillInputs received in content
> util.js:66:9
> [PassFF.content] fillInputs: No relevant login input elements recognized.
> util.js:66:9
> [PassFF.content] Message Page.fillInputs received in content
> util.js:66:9
> [PassFF.content] fillInputs: No relevant login input elements recognized.
> util.js:66:9
> [PassFF.content] Message Page.fillInputs received in content
> util.js:66:9
> [PassFF.content] fillInputs: No relevant login input elements recognized.
> util.js:66:9
> [PassFF.content] Message Page.fillInputs received in content
> util.js:66:9
> [PassFF.content] fillInputs: No relevant login input elements recognized.
> util.js:66:9
> [PassFF.content] Start auto-fill using web/paypal.com-test false
> util.js:66:9
> [PassFF.content] Set inputs...

Ok for the warning message
Good point for "Set inputs..." done once. 
But what about the "No relevant login ... " ? Is it necessary to be looping 4 times ? 

In fact, the question about the hack, was for personnal use, I don't thought it could be added so quickly. So maybe, some information somewhere about the 2 step login process, only working with manual filling and submitting, would be a plus. 

And last, is the submit option, from "fill and submit" on ENTER key press, in any way an autosubmit option ? I can't make it go to step 2 with the new possibility for alternate ENTER key. For example with ctrl-ENTER. 

K.
