### ISSUE TITLE
Graphics problem in search/text boxes

### ISSUE THREAD

**Issue by akissz** [passff/passff#449]
Maybe this was already reported but there is a problem with pages with form search fields. The plugin is reading it as a username maybe and drawing these partial circles in the css code of the textbox I think. See attached image.
![searchbox](https://user-images.githubusercontent.com/23090286/92418894-bd4e3e80-f12f-11ea-8a64-f8ba117a28d4.png)

**Comment by akissz** [comment]
Here is the code and more detail in this image.
![csserrorpassff](https://user-images.githubusercontent.com/23090286/92419165-4fa31200-f131-11ea-81cd-ea00d4a49cff.png)

**Comment by akissz** [comment]
The Firefox is 80.0.1
The operating system is MacOS.
Did not test in other OS.

**Comment by akissz** [comment]
Also if you need this info, this happens when the host app is not installed. I did not have the host app installed on the MacOS and I noticed the graphics problem. Maybe that is connected or maybe not.

**Comment by akissz** [comment]
And here is the html if you want that...
![textboxpassfferror](https://user-images.githubusercontent.com/23090286/92419339-9ba28680-f132-11ea-94fb-5c94bc8cbd78.png)

**Comment by akissz** [comment]
Tested with FreeBSD and Firefox 80, the graphics bug is not there with FreeBSD. So seems to be with MacOS partly but not FreeBSD. But the P icon does still show in the search form in the text box. Shouldn't the P icon for PassFF NOT show in normal text boxes that are not in the named type of text boxes that are set in settings of PassFF?

**Comment by akissz** [comment]
I tested with a new fresh Firefox profile on MacOS to confirm, its still there yup. It shows the small P in the text box, then it expands in the text box, and the partial circles are clickable too. Strange.

**Comment by marcelbuesing** [comment]
I have the same issue, especially with the mail.google.com search input field. Firefox 84.0.2 (64-bit) / Linux 5.10.7-3-MANJARO.

**Comment by tuxor1337** [comment]
Solved by #469 (78cf0a7)
