### ISSUE TITLE
Breaks post composer in a phpBB forum

### ISSUE THREAD

**Issue by xerus2000** [passff/passff#450]
### General information. Describe your environment

- Versions
  - Operating system: KDE Neon 18
  - Browser: Firefox
  - PassFF: 1.10.1
  - Host app: 1.2.1

Status line output: `[16:58:17] grepMetaUrls -> (1) Usage: pass grep search-string `

---

### Actual behaviour
I wanted to write a new post in a phpBB forum. All formatting buttons were obscured by the passff-logo:
![image](https://user-images.githubusercontent.com/13354331/93355019-e8c2de80-f83d-11ea-8bce-59a3e319d2ef.png)

They were still clickable, but hovering over each of them to find the right one to click is quite a hassle.

### Expected behaviour
Disabling the extension and then reloading the page brought desired behavior, all the formatting buttons visible and usable as usual:

![image](https://user-images.githubusercontent.com/13354331/93355611-8e764d80-f83e-11ea-8c72-6ca5350aaa05.png)

**Comment by tuxor1337** [comment]
Link to a forum where the issue applies would be good. Otherwise, at least phpBB version and theme are necessary to reproduce this.

**Comment by xerus2000** [comment]
Unfortunately, the forum is private. I will stay on the lookout for more details.
The only thing I could find out so far is that it runs the "Lucid Lime style".

**Comment by tuxor1337** [comment]
Can you maybe inspect the code and see whether the buttons have names that contain some of the "input names" in your PassFF preferences? This would mean that #451 is related.

**Comment by xerus2000** [comment]
Looks like it! I'm on 1.10.2 now and the issues seems to be gone :)
