### ISSUE TITLE
About addition of (P) icon to type="button"

### ISSUE THREAD

**Issue by OGAWAHirofumi** [passff/passff#451]
### General information. Describe your environment

- Versions
  - Operating system: Linux 5.8.1
  - Browser: firefox 81.0
  - PassFF: 1.10.1
  - Host app: 1.2.1

Status line output: `[hh:mm:ss] show -> (0) no error message`

---

### Actual behaviour
Describe *objectively* your problem. What happened?

"OTP input names" config is including "otp".

```html
<input type="button" name="imgNewOtpw" value="run" onclick="location.reload()">
```
So, if html is including above for example, (P) icon is added to button.  By addition of (P) icon, the background image of button seems to be broken (background image by css was not used).

Additionally, (P) icon looks like useless for button type. Because if clicked (P) icon, onclick="..." ran.

### Expected behaviour
What should happen instead?

If adding (P) icon to type="button" is not intent, it would be good to exclude if type="button"?

**Comment by tuxor1337** [comment]
It's true that, so far, the input type is only checked for the login and password input fields. For OTP input fields, the input type is not a necessary condition. I just now pushed an update (1.10.2) to fix this. Would you please check?

**Comment by OGAWAHirofumi** [comment]
Thank you. I confirmed latest git was fixed my use case.
