### ISSUE TITLE
Setting custom shortcut is not persisted

### ISSUE THREAD

**Issue by comatory** [passff/passff#460]
### General information. Describe your environment

- Versions
  - Operating system: Mac OS 10.15.7
  - Browser: Firefox 82.0.2 
  - PassFF: 1.10.3
  - Host app: 1.2.1

Status line output: `[09:51:43] ls -> (0) no error message`
---

### Actual behaviour
I set up shortcut key in extension settings. I then restarted browser and settings show original shortcut instead of the new one.

### Expected behaviour
Shortcut key should be persisted.

### Steps to reproduce the behaviour
1. Open extension settings, open Preferences tab
2. Change value for "Keyboard shortcut for toolbar menu"
3. Restart browser

**Comment by tuxor1337** [comment]
I can't reproduce your problem on Fedora 33, Firefox 82.0.2, PassFF 1.10.3.

1. Which shortcut are you trying to set?
2. For comparison, please try to set the shortcut following this guide: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

**Comment by comatory** [comment]
1. I am trying to set it from `CTRL + G` to `CTRL + ,`.
2. OK using that menu it actually works. But what's more interesting is that I noticed the actual shortcut detected by FF is `CMD + G`. So not sure if this is a problem of Firefox or not. Anyway using the method above for changing the shortcut actually worked.

Firefox extension shortcut view:
![Screenshot 2020-11-10 at 08 34 03](https://user-images.githubusercontent.com/5990424/98643770-c629df00-232f-11eb-92e3-1b0df306fea9.png)

Pass FF preferences view:
![Screenshot 2020-11-10 at 08 34 25](https://user-images.githubusercontent.com/5990424/98643805-d2ae3780-232f-11eb-90a0-988d89b1e0b1.png)

**Comment by tuxor1337** [comment]
I'm not familiar with MacOS, but this doesn't sound like a bug in PassFF to me.
