### ISSUE TITLE
Support multiple URLs for a single entry

### ISSUE THREAD

**Issue by tadhgmister** [passff/passff#466]
### General information. Describe your environment

- Versions
  - Operating system: Linux guix 5.10.7-gnu
  - Browser: icecat 78.6.1
  - PassFF: 1.10.5
  - Host app: 1.2.1

Status line output: `[02:24:19] show -> (0) no error message`

- Output of `pass`: lists password store, works as intended
- Your preferences
  - In PassFF: index URL fields on startup enabled, auto-fill but not auto-submit (not relevant for issue)
  - In the host app `passff.py`: all default
- Messages in the web console: none relevent

---

### Description of problem
There are cases where there are multiple domains that are part of the same service and should login with the same credentials, for instance:
- https://facebook.com and https://messenger.com
- https://steamcommunity.com/login and https://store.steampowered.com/login

In cases like this, I would rather have only a single pass entry for all applicable domains to reduce redundancy. 
This can be accomplished in either of the following ways:
- enable the setting "index URL fields on startup" and have multiple URL fields in the pass files
- or making one "main" credential entry and creating symlinks in the password store for the other domains linking to the main entry.

With either of these setups passff offers the correct entries for autofill but the option to `warn about potential phishing sites when the domain listed in the database differs from the current page` raises false positives for all but the last URL entry in the pass file.  This also prevents auto-fill from working correctly on those sites.

### Expected behaviour

Have some way to specify multiple URLs for a given entry, either by having multiple URL fields either all using `url:` or possibly by just registering multiple entries from URL fields specified in preferences. (so could have `url:` and `http:` fields using default settings, or could set `url1` and `url2` as recognized URL fields)

### Steps to reproduce the behaviour
1.
2.
3.

**Comment by tadhgmister** [comment]
when a pass file speifies multiple fields with the same name this loop ends up overriding the same key multiple times so the last one is the only one that survives:
https://github.com/passff/passff/blob/c3456219d204c7df4b9230ba267da4ece6e8810d/src/modules/pass.js#L520

So one possibility is to have a way to capture a list of fields with the same name although that feels really weird, with the second option of allowing multiple URL fields with different names we are currently setting "the URL of the password" like this:
https://github.com/passff/passff/blob/c3456219d204c7df4b9230ba267da4ece6e8810d/src/modules/pass.js#L44-L49
so of the URL tags specified in the preferences it finds the first applicable one and uses that as the URL, if we modify this to keep a list of all present tags instead of just the first then the other places that use the URL would just need to apply it to all the URLs instead:
https://github.com/passff/passff/blob/c3456219d204c7df4b9230ba267da4ece6e8810d/src/modules/page.js#L746
Although I haven't looked thoroughly enough to figure out all the updates needed, particularly I haven't figured out all the cases for the how it parses the structure of the pass database.

**Comment by tuxor1337** [comment]
I don't think it would be very elegant to have explicit names for url1, url2 etc, because that would limit the number of URLs to the number of names defined. I like the idea to store the values of all lines starting with an URL field name as a list. With this feature, we could approach #457 at the same time.

Having multiple URL values would require quite some restructuring. We would need to replace `passwordData.url` by `passwordData.urls` and make sure that we are treating it as a list. Then we would need a logic to decide which of the URL entries to use in a particular instance (especially for the `Go to` feature). Feel free to work on this and discuss your ideas in this issue or create a PR.

**Comment by tadhgmister** [comment]
well the current behaviour is that if multiple fields of the same name are present the last one is the one used in the goto, and when multiple recognized keys are present (`url` and `http`) the order in the preferences dictates the priority, I see no reason to change this behaviour, the main thing is that the loop that finds the url to use would still have the first element of this list be the goto target.

I'm not sure I'm on board with using glob since that would make it really easy to mistakenly trust phishing sites, the last thing I want is to auto-fill and submit a form on a phishing site because someone didn't have strict enough glob pattern. A discrete list of trusted domains makes far more sense to me.

**Comment by xeruf** [comment]
I dunno is this is related, but I have an entry `www/matrix.org/xerus` with `url: app.element.io` in the content - but despite indexing at startup, it does not recognize this entry in Element. Is it because I have two schemes and thus two matchable URLs?

**Comment by dreirund** [comment]
> *With either of these setups passff offers the correct entries for autofill but the option to `warn about potential phishing sites when the domain listed in the database differs from the current page` raises false positives for all but the last URL entry in the pass file.*

I‌ have this issue, too, and I‌ also have

> *I have an entry `www/matrix.org/xerus` with `url: app.element.io` in the content - but despite indexing at startup, it does not recognize this entry in Element.*

this issue, too (but the latter issue is a different one than the opening issue, so I suggest you create a seperate ticket for it, @xeruf).
