### ISSUE TITLE
Autofill password only into type="password" inputs

### ISSUE THREAD

**Issue by st31ny** [passff/passff#467]
### General information. Describe your environment

- Versions
  - Operating system: Debian Testing (aka Bullseye)
  - Browser: Firefox 78.6.1esr (64-Bit)
  - PassFF: 1.10.5
  - Host app: 1.2.1

- PassFF preferences
  - Autofill Login pages enabled
---

### Actual behaviour
An input box that is not a password box is filled with my password for a site in clear text.

The input box's html code is: 
```
<input type="text" name="url" id="url" class="form-control js-mirror-url js-repo-url qa-mirror-repository-url-input gl-field-error-outline" placeholder="Enter your repository URL" required="required" pattern="(http|https|ssh|git)://.+" autocomplete="new-password" style="background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 16px; background-position: calc(100% - 4px) 50%; background-image: url(&quot;moz-extension://ae5fa375-25b2-4392-9f27-730501114161/skin/icon-light.svg&quot;); cursor: auto;">
```

I guess the phrase `new-password` is a trigger for passff to fill the field?

### Expected behaviour

Since this field is not hidden, my password is visible in clear text. This behaviour has actually led me to disable the option "autofill login pages". I believe that a password should only ever be filled in a input box of *type* `password` such that it is not exposed in clear text.

### Steps to reproduce the behaviour
1. Store a password for a site with an input box like cited above.
2. Enable "autofill login pages".
3. Open site.

**Comment by tuxor1337** [comment]
This is intended behavior. If you don't want PassFF to fill any non-password inputs with passwords, you can set the "Names for password input fields" in the preferences to an empty string.

**Comment by st31ny** [comment]
Thanks for clarifying that, this works for me!

I had wrongly assumed that both the box has to be ticked and the "Names for password input fields" must match.
