### ISSUE TITLE
Request/Suggestion: allow arbitrary host for passff-host

### ISSUE THREAD

**Issue by stupid-genius** [passff/passff#470]
Use case: keep password store on single computer on network and be able to point passff extension to it from multiple machines on network.

**Comment by tuxor1337** [comment]
passff-host is not some kind of server. It's a local interface to the pass command line tool. This project only provides a browser user interface for the pass command line tool. Unless pass implements a server infrastructure at some point in the future, this feature request is completely out of scope.
