### ISSUE TITLE
Keyword search is too fuzzy, or order of results is bad

### ISSUE THREAD

**Issue by kayceegb** [passff/passff#476]
Hello,

I have found a case where the returned result is empty with an existing entry in password-store.

### General information. Describe your environment

- Versions
  - Operating system: Slackware 14.2 amd64
  - Browser: Firefox 68.12 esr
  - PassFF: 1.10.6
  - Host app: 1.2.1

Status line output: `[hh:mm:ss] show -> (0)`
[22:00:14] show -> (0) no error message

- Output of `pass`: returns correct data
- Your preferences
  - In PassFF: default except autofilling disable and some custom field detection names
  - In the host app `passff.py`: default iirc
- Messages in the web console: 
No errors returned

---

### Actual behaviour
Searching for an existing entry do returns nothing

### Expected behaviour
Entry should be listed and selection allowed

### Steps to reproduce the behaviour
1. create an entry, with pass in hierarchy mode, as category/zlog/{login,password}. You should have also at least 6 entries before this one. 
2.update passff, search for "log"
3.nothing returned

Additionnaly, I found that renaming the entry to category/alog, the search is successfull. 
Looking at console in details I see this

```
[PassFF.menu] Create children menu list 
(6) […]
​
0: Object { id: 46, key: "login", depth: 2, … }
​
1: Object { id: 49, key: "login", depth: 2, … }
​
2: Object { id: 52, key: "login", depth: 2, … }
​
3: Object { id: 55, key: "login", depth: 2, … }
​
4: Object { id: 60, key: "login", depth: 2, … }
​
5: Object { id: 63, key: "login", depth: 2, … }
​
length: 6
​
<prototype>: Array []
```

And once renamed, we have this:
```
[PassFF.menu] Create children menu list 
(6) […]
​
0: Object { id: 43, key: "alog", depth: 1, … }
​
1: Object { id: 44, key: "login", depth: 2, … }
​
2: Object { id: 45, key: "passwd", depth: 2, … }
​
3: Object { id: 49, key: "login", depth: 2, … }
​
4: Object { id: 52, key: "login", depth: 2, … }
​
5: Object { id: 55, key: "login", depth: 2, … }
​
length: 6
​
<prototype>: Array []
```

K.

**Comment by tuxor1337** [comment]
This is a problem of the keyword search feature being too fuzzy and/or search results not being ordered by match quality. I would really prefer to use something like https://github.com/farzher/fuzzysort to generate our search results. However, that library would add hundreds of lines of code just for that feature which seems exaggerated to me.

**Comment by kayceegb** [comment]
By fuzzy you mean that searches match each caracter entered in search field?  Not necessarily exact pattern ?

Currently if you enter "cl" in search field it can match "cat/link". "c" and "l" are not touching themselves. 

Isn't it possible to make searches match  exact search pattern ? 

Or alternatively, isn't it possible to exclude from search, objects that match "login" and "password" fields defined in options ? 

K.

**Comment by tuxor1337** [comment]
Pass entries that correspond to fields are already excluded from search.

I now changed the ordering of search results in 2c08ce0 to list exact matches higher than fuzzy matches. This is still not as useful as `fuzzysort` but should at least solve this issue.

**Comment by kayceegb** [comment]
> Pass entries that correspond to fields are already excluded from search.

Sorry maybe I am wrong in my terms. Actually I thougth about "menu list"/"children menu list" (as posted at issue create time) and not "searches". 
Entries does not seem to be excluded from these arrays. 

And after refresh and build of passff as of 10 minutes ago, it is even worst than before. 
Searching for log with the same example as above, does not even return the alog entry. 

> [PassFF.menu] Search keyup 
> keyup { target: input#passff-search-box
> , key: "g", charCode: 0, keyCode: 71 }
> util.js:66:14
> [PassFF.menu] Create menu list 
> (6) […]
> ​
> 0: Object { id: 4, key: "login", depth: 2, … }
> ​
> 1: Object { id: 7, key: "login", depth: 2, … }
> ​
> 2: Object { id: 10, key: "login", depth: 2, … }
> ​
> 3: Object { id: 13, key: "login", depth: 2, … }
> ​
> 4: Object { id: 16, key: "login", depth: 2, … }
> ​
> 5: Object { id: 19, key: "login", depth: 2, … }
> ​
> length: 6
> ​
> <prototype>: Array []
> util.js:66:14
> [PassFF.menu] Create children menu list 
> (6) […]
> ​
> 0: Object { id: 4, key: "login", depth: 2, … }
> ​
> 1: Object { id: 7, key: "login", depth: 2, … }
> ​
> 2: Object { id: 10, key: "login", depth: 2, … }
> ​
> 3: Object { id: 13, key: "login", depth: 2, … }
> ​
> 4: Object { id: 16, key: "login", depth: 2, … }
> ​
> 5: Object { id: 19, key: "login", depth: 2, … }
> ​
> length: 6
> ​
> <prototype>: Array []
>  true util.js:66:14
> [PassFF.background] Message Menu.backupState received in background

And in addition, when previously searching for another term gave correct and only result, now returns entries that have nothing to do with the search.

**Comment by tuxor1337** [comment]
Ah okay, that's true, the field entries used to be filtered only in the menu list setup. I fixed this in 5e53c76

**Comment by kayceegb** [comment]
That's better for search results. Seems to return correctly but it adds dirty results too.

I've done some tests and the dirty results seems to come from your draft (b3c7728e286177bad582d8e5c52558af59d0099d). 

I rollbacked to 1.10.6 and tried this:

```
diff --git a/src/modules/pass.js b/src/modules/pass.js
index 12872b0..a5f5c0a 100644
--- a/src/modules/pass.js
+++ b/src/modules/pass.js
@@ -620,7 +620,7 @@ PassFF.Pass = (function () {
           let flags = PassFF.Preferences.caseInsensitiveSearch ? 'i' : '';
           let regex = new RegExp(searchRegex, flags);

-          if ((item.isLeaf || item.hasFields) && item.fullKey.search(regex) >= 0) {
+          if (!item.isLeaf && !item.isField && item.hasFields && item.fullKey.search(regex) >= 0) {
             matches.push(item);
           }

```

And I am very close to what I am looking after. Searching for "log" returns "category/alog". Renaming "category/alog" to "category/zlog" and searching again for "log" returns "category/zlog" correctly. And in addition, this does not populate "menu list"/"children menu list" with garbage entries so in my opinion there is more room for cases with  many results.

```
[PassFF.menu] Search keyup 
keyup { target: input#passff-search-box, key: "g", charCode: 0, keyCode: 71 }
```
```
[PassFF.menu] Create menu list 
(1) […]
​
0: Object { id: 115, key: "zlog", depth: 1, … }
​
length: 1
​
<prototype>: Array []
util.js:66:14

```
```
[PassFF.menu] Create children menu list 
(1) […]
​
0: Object { id: 115, key: "zlog", depth: 1, … }
​
length: 1
​
<prototype>: Array []
 true util.js:66:14
```

I will stay with this for a moment I think and see how it runs. As I said above, I am with a pass store in hierarchy mode, so I don't know what could be the drawbacks for others. Any idea ?

**Comment by tuxor1337** [comment]
I don't understand what a "dirty result" is supposed to be.

**Comment by kayceegb** [comment]
A result that matches partially entered pattern or even not matching at all :/

**Comment by tuxor1337** [comment]
It's correct that non-matching entries might be included in the result. But matching entries are always listed first. However, I see that this might be confusing, so I changed the behavior for you: 55a37bb

**Comment by kayceegb** [comment]
In 1.10.6, non matching were not included so yes it may confuse. And I prefer when it's clean ;)

As of your last change, seems to do the job.
