### ISSUE TITLE
Matching problem with url with ports

### ISSUE THREAD

**Issue by raven2cz** [passff/passff#477]
Hi,
I have a lot of url for local network with ports in the url. For example: `192.168.1.78:3000`, `192.168.1.120`.
My actual password store structure was:
```
local/192.168.1.78:3000.gpg
local/192.168.1.78.gpg
local/192.168.1.120.gpg
```

I open web in firefox with 192.168.1.78:3000. And passff correctly shows 192.168.1.78:3000 as the first choice. The matching works correctly.
The problem is that ":" is forbidden for windows, and I have developers which is using windows. So, I tried to rename ":" to "-" according to your guide and insert the key "url: 192.168.1.78:3000" inside to gpg file.
But I'm surprised, the 192.168.1.78:3000 is not matched, it is in the last place, the first is matched:
192.168.1.120 which doesn't include 192.168.1.78 and not have 3000 too.
There has to be some bug with last release.
I'm using last release. 
passff 1.10.6
passff-host 1.2.1

Do you have some tip how to match ports without using ":"? It means relevant for windows.
Thanks for help.

**Comment by tuxor1337** [comment]
I updated the matching algorithm in 5735614 so that it should perform better with your example.
