### ISSUE TITLE
PassFF window empty and shows no passwords for no clear reason

### ISSUE THREAD

**Issue by stephen304** [passff/passff#478]
### General information. Describe your environment

- Versions
  - Operating system: Arch linux
  - Browser: Firefox 89.0.1
  - PassFF: 1.10.6
  - Host app: 1:1.2.1-3

Status line output: `[13:58:14] grepMetaUrls -> (0) no error message`

- Output of `pass`: `?R],g|?k.....` I'm not sure what this is, it doesn't look like a password of mine. The output is also exactly the same if I run `pass ls`, it doesn't show a list of passwords, however `pass search steam` does work:

```
pass search steam
Search Terms: steam
├── Forums
│   └── forums.steampowered.com
└── Games
    └── steamcommunity.com

```
- Your preferences
  - In PassFF:
  
![image](https://user-images.githubusercontent.com/981915/122976732-b2813500-d362-11eb-9005-9f78916788b1.png)
![image](https://user-images.githubusercontent.com/981915/122976789-c3ca4180-d362-11eb-96b3-486c31438bb0.png)
![image](https://user-images.githubusercontent.com/981915/122976821-ccbb1300-d362-11eb-91b1-76acc5beb74d.png)
![image](https://user-images.githubusercontent.com/981915/122976851-d3e22100-d362-11eb-9f16-1c23584be6f5.png)

  - In the host app `passff.py`: 
  
  ```
  COMMAND = "pass"
COMMAND_ARGS = []
COMMAND_ENV = {
    "TREE_CHARSET": "ISO-8859-1",
    "PATH": "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
}
CHARSET = "UTF-8"


  ```
- Messages in the web console: 

![image](https://user-images.githubusercontent.com/981915/122977279-3804e500-d363-11eb-99df-2962f8d57a8f.png)
![image](https://user-images.githubusercontent.com/981915/122977539-8914d900-d363-11eb-81f4-53615595ad52.png)

---

### Actual behaviour
Describe *objectively* your problem. What happened?

PassFF shows nothing in the addon window, clicking on top level, contextual, or refresh doesn't do anything, even after reloading the extension or restarting the browser and entering the password for the gpg prompt. No entries matching this url when I try to fill a site. However, adding a new password DOES work, for example I add 'test' and can see it via `pass show test`, though after adding it, the passff window remains empty despite it being added successfully.

![image](https://user-images.githubusercontent.com/981915/122977734-beb9c200-d363-11eb-9631-4a9c1bb505b5.png)

### Expected behaviour
What should happen instead?

It should show all the passwords I have saved and have been using

### Steps to reproduce the behaviour
1. Use passff for a long time
2. Passff stops working for some reason
3. ???

**Comment by stephen304** [comment]
I solved the issue, I think I accidentally generated a password in PassFF without entering a name. I now have a pass entry named `/` and I guess that breaks things. Although it seems that entry is invisible on Android.

```
stephen@Jupiter ~ (git)-[master] % pass show /
?R],g|?kcUQ:7N+#
stephen@Jupiter ~ (git)-[master] % pass edit /
Password unchanged.
1 stephen@Jupiter ~ (git)-[master] % pass ls /
?R],g|?kcUQ:7N+#
stephen@Jupiter ~ (git)-[master] % pass rm /
Are you sure you would like to delete /? [y/N] y
rm: cannot remove '/home/stephen/.password-store/': Is a directory
```

```
stephen@Jupiter ~/.password-store (git)-[master] % rm .gpg
stephen@Jupiter ~/.password-store (git)-[master] % pass git add .gpg    
stephen@Jupiter ~/.password-store (git)-[master] % pass git commit
[master 85d31f3] Remove ./ from store.
 1 file changed, 0 insertions(+), 0 deletions(-)
 delete mode 100644 .gpg
```

**Comment by tuxor1337** [comment]
Thanks for posting the fix yourself :+1:
