### ISSUE TITLE
New icon for passff. Not visible for many dark themes. 

### ISSUE THREAD

**Issue by raven2cz** [passff/passff#479]
New Firefox default and dark theme design has exact color as passff icon. The icon is not visible. 

In addition, the color of passff is not designed correctly, it is almost invisible in other older color schemas, like dracula themes, which is used very often.

Please consider changing the color of the icon.

For example variants:
#65b2e3
#9580ff
#ffca80
#70a99f

**Comment by tuxor1337** [comment]
I can't confirm this with Firefox 89:
![image](https://user-images.githubusercontent.com/1518387/124122021-dd137200-da75-11eb-9727-7d8989133305.png)
We already have different icons for light/dark themes, see #253

**Comment by raven2cz** [comment]
Yes, but it is reality. It doesn't work in arch, awesomewm, qtile, xmonad etc. Maybe it is driven some property which is not set, but other icons works correctly, not pass. 

In kde, gnome, it works.

![image](https://user-images.githubusercontent.com/20504243/124146489-56629300-da7d-11eb-8f8d-e5fe3ab07024.png)

Is there some possibility to check which property is controlled? I can provide more details, but I have to know what is important for your switch between dark and light icon.

**Comment by tuxor1337** [comment]
We already use the single officially supported way (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action#theme_icons) for light/dark themed icons: https://github.com/passff/passff/blob/e40d8671f73e0b7f1b5ad719ce9c480c43c4c58d/src/manifest.json#L14-L19 I don't think that there is anything we can do on PassFF's side to fix this. This is an upstream issue.

**Comment by raven2cz** [comment]
I checked independent on windows platform, firefox 89, extension actually download from firefox store. The bug is still present, it is doesn't true that it works in firefox 89. You have to use some specific build of passff, the extension doesn't work from store.

![obrazek](https://user-images.githubusercontent.com/20504243/124296671-8469d500-db5a-11eb-858c-0d9b77daf90e.png)

**Comment by tuxor1337** [comment]
As I said, this must be an upstream issue. Please post it on the [Firefox bug tracker](https://bugzilla.mozilla.org/).
