### ISSUE TITLE
Only fill the first field

### ISSUE THREAD

**Issue by mowgli** [passff/passff#484]
I have a bank account where the login provides p_username and p_userid fields but only p_username is valid for login, if p_userid is filled too, the login fails so I cannot use the auto login.

Do you see any way to only one form field? Maybe adding a preference to do so or a option stored inside of the pass record.

Ps. This is a enhancement request so I deleted the info as it doesn't provide additional info.

**Comment by tuxor1337** [comment]
Filling only the first field might be relevant for your particular web site. On other web sites it might be only the second or the last field. It would be a bit more flexible to have a blacklisting of input fields, maybe even per website. An option to right-click on a form field and then select "don't use this as an input field" (or something similar).
