### ISSUE TITLE
Use optional information to fill optional form fields

### ISSUE THREAD

**Issue by mowgli** [passff/passff#485]
There are some pages that needs not only username and password than also additional fields like company.

I suggest to readout additional fields from pass record to fill them too.

Possible solutions would be:
1. Use the full id as selector
2. Have a mapping inside the pass record or an special name to mark that optional fields (`o_company: xyz` to match `*company*`)

**Comment by tuxor1337** [comment]
This feature exists already, see https://github.com/passff/passff#multi-line-format

**Comment by mowgli** [comment]
Cool, thanks, I didn't know that this could be used to match the id exactly.

For me that is perfect. But just be curious, @tuxor1337, can you also match partial field name/id? I tried with just a part and it didn't work but maybe you have implemented some globing or regex?

**Comment by tuxor1337** [comment]
No, there is no globbing or regex applied currently, the `id` or `name` attribute must match exactly. Maybe, this would be a compromise for #378, because I don't see anybody implementing a sophisticated solution for #378 anytime soon.
