### ISSUE TITLE
Fills out domain name instead of email

### ISSUE THREAD

**Issue by TobTobXX** [passff/passff#488]
### General information. Describe your environment

- Versions
  - Operating system: Arch Linux
  - Browser: FF (developer edition) 91.0b6
  - PassFF: 1.11.2
  - Host app: 1.2.1

- Status line output: `[16:39:31] show -> (0) no error message`

- Output of `pass`: ... works?
- Your preferences
  - In PassFF: No custom i think (unsure)
  - In the host app `passff.py`: None (arch package default)
- Messages in the web console: 
```
[PassFF.content] 1 matches for https://login.ag.ch/sls-ng/auth util.js:66:14
[PassFF.content] Best fit item www/ag.ch for https://login.ag.ch/sls-ng/auth util.js:66:14
[PassFF.content] Inject icon username util.js:66:14
[PassFF.content] Start pref-auto-fill util.js:66:14
[PassFF.content] fillInputs: No relevant login input elements recognized. util.js:66:14
TypeError: can't access property "then", PassFF.Page.fillInputs(...) is null
```

<details>
<summary>Problematic input tag</summary>

```
<input
    class="form__input "
    name="userid"
    id="username"
    type="text"
    value=""
    required=""
    aria-required="true"
    autofocus=""
    style="background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 16px; background-position: calc(100% - 4px) 50%; background-image: url(&quot;moz-extension://959d0046-25f1-4421-9af0-25aeb1b01112/skin/icon-light.svg&quot;); cursor: auto;">
```

</details>
---

### Actual behaviour
This is in `pass show www/ag.ch` (password & email changed ofc):
```
passwd123
email: user@example.com
url: https://login.ag.ch/
```
I'd want to login into the website at ag.ch (gov website, [Login](https://login.ag.ch/sls-ng/auth)), and passff fills the email with `ag.ch` (the domain name).

### Expected behaviour
PassFF fills in the email from the store

### Steps to reproduce the behaviour
1. Create a pass entry like the one above
2. Go to https://login.ag.ch/sls-ng/auth
3. Let PassFF fill out the login field

**Comment by TobTobXX** [comment]
Ugh, I added `email` to the list of login field names, and now passFF fills out the correct login data.

Closing, since it isn't an issue anymore, but I still wonder:
 - (a) why does it fill in `ag.ch` and not the full url from the password store (heck, why does it even use the url in the first place?)
 - (b) does PassFF use the fields in order of the setting of the addon, or in which order?

**Comment by tuxor1337** [comment]
This is explained in the README:

> If there is only a single line, or none of the provided fields matches a login field name, the username is taken from the filename, e.g. example.com/janedoe will have a default username of janedoe.

(a) If your pass entry (filename) is `ag.ch` and PassFF doesn't know `email` is a login field name, then it will assume that `ag.ch` is the username.

(b) If your file contains several lines that match login field names, PassFF will prefer the login field name that is listed first in your PassFF settings (this is not mentioned in the README currently).
