### ISSUE TITLE
personalcapital.com login issue

### ISSUE THREAD

**Issue by sdfsdfsdfsdfsdfsdfsdfsdffwewerwrwerwer** [passff/passff#493]
### Versions
- Operating system:  macOS 11.6
- Browser:  FF 92.0
- PassFF:  1.12.1
- Host app:  not sure how to tell

Status line output: `[hh:mm:ss] show -> (0)`
 [08:51:57] show -> (0) no error message

### Observations

- Output of `pass`:   works fine
- Your preferences
  - In PassFF: 
  - In the host app `passff.py`: 
- Messages in the web console:   Nothing comes up in js console when attempting to log in

---

### Steps to reproduce the issue
1.  go to personalcapital.com
2.  click the p in username box, select personalcapital.com, this will take you to the password page  (they have user and password on separate pages)
3.  click the p in password box, select personalcapital.com

### Actual behaviour

it goes right back to the username page again

### Expected behaviour

should log me in
This used to work fine, but a couple of weeks ago stopped logging me in.  If I use the passFF menu "Fill" option to insert the pass and then click the "Sign In" button everything works fine.  I reported this issue to them but they said since I had logged in then I didn't have a problem.

**Comment by tuxor1337** [comment]
Unfortunately, I can't test this because I don't have an account on that website.
