### ISSUE TITLE
other_inputfield_name should have preference over other fields

### ISSUE THREAD

**Issue by vandepitte** [passff/passff#494]
### Versions
- Operating system: Mac Os X
- Browser: Firefox 92.0
- PassFF: 1.12.1
- Host app: ?

### Actual behaviour
When adding other_inputfield_names in my pass vault with keys like 'usercompany', an input field with the same name is filled with the "user"/"username"/.... value

### Expected behaviour
when an other_inputfield_name exactly matches an input field, then I would expect the app to fill the input field with that value, even if the input field contains words like user, id, email, ....

**Comment by tuxor1337** [comment]
This is already the default behavior: https://github.com/passff/passff/blob/80b453aedaf5393c074cfe644121c87926b95074/src/modules/page.js#L242-L254

**Comment by vandepitte** [comment]
My bad, I got confused while testing my other issue (colons)
