### ISSUE TITLE
"Script execution failed" dialog when cancelling input

### ISSUE THREAD

**Issue by ripaul** [passff/passff#496]
### Versions
- Operating system: Ubuntu 20.04.1 LTS
- Browser: Firefox 93.0
- PassFF: 1.13
- Host app: 1.7.3

Status line output: `[12:54:54] show -> (2) gpg: decryption failed: No secret key `

### Observations

- Output of `pass`: 
- Your preferences
  - In PassFF: Autofilling: Try to autofill page login forms.
---

### Steps to reproduce the issue
1. Open any page that requires a password or has a password field that will trigger passff to autofill
2. pinentry will open, querying master password
3. Hit Escape

### Actual behaviour
After hitting Escape, a dialog opens telling you that your password could not be decrypted.
```
Script execution failed:
gpg: decryption failed: No secret key
```
![image](https://user-images.githubusercontent.com/45046088/137896265-55b4613a-2390-4c5e-9a4f-9394c6f17b16.png)

### Expected behaviour
The pinentry should close and passff should "fail silently". It may very well be intended behaviour to not autofill on a particular page. Moreover the dialog that appears cannot be closed with Escape, so you have to really click "OK" with the mouse.

This is really just a minor "issue", more like a mini enhancement.

Thanks anyways for this awesome browser plugin!

**Comment by madduck** [comment]
What's the status of this issue? I think it'd be great to be able to disable this dialog box.

**Comment by tuxor1337** [comment]
As far as I know, the proposed solution would still be valid, and nobody is working on it. So, if you or somebody else is interested, feel free to create a PR :)

**Comment by ripaul** [comment]
Unfortunately I have no clue about programming firefox extensions so when I tried doing something about it I figured it'd cost me too much time, so I kinda learned to live with it. But now I just came up with a super hacky solution: In case you are using uBlock Origin (or presumably any other adblocker), you can add a filter to just block the corresponding `<div id="passff_notification">...</div>`.

For uBlock Origin you just add 
```
###passff_notification
```
to `uBlock - Dashboard > My filters`.

Definitely not a clean solution and surely will have negative side effects (like e.g. the notification still popping up on pages which are not blocked by uBlock). But for the moment the best I can come up with.

**Comment by madduck** [comment]
Nice hack @ripaul, but it doesn't work for me. I will have to look into this a bit more I guess.

**Comment by tuxor1337** [comment]
With https://github.com/passff/passff/issues/544 fixed, we are now in a much better situation where this could be fixed rather easily.
