### ISSUE TITLE
New icon for passff. Not visible for many dark themes.

### ISSUE THREAD

**Issue by raven2cz** [passff/passff#499]
I already wrote this issue and it was closed as upstream issue. Please check this issue correct way. Actual standard firefox themes cause that the icon is not visible anymore, because it has exact same color as standard theme.

![passFF-icon-invisble](https://user-images.githubusercontent.com/20504243/143488503-0ccb1937-2a3d-49ca-a074-20e9c13b57c0.png)

Your passff icon is on right side from vimium plugin. If for example vimuim plugin icon haven't these problems why your icon has it? (if it is a upstream issue?) 

Please check correctly it and change the colors according these problems. Dark themes are much more used against light themes. Or add some possibility to change it by user configuration of your plugin, some switcher light/dark/auto. Thanks for help.

**Comment by tuxor1337** [comment]
I just checked several dark themes and didn't found any for which the background color exactly agrees with the icon color. So I don't think that this is a big issue. You can solve this by adding transparency to the icon. Feel free to make a PR with this kind of change. I currently don't have time to deal with it, sorry.

**Comment by Alexey104** [comment]
Confirm (Firefox 109.0):
![passff](https://user-images.githubusercontent.com/38672094/214206390-9a6e5592-f1ce-4b87-ace9-086d008f7187.png)

**Comment by tuxor1337** [comment]
Fixed in 1.14.1

**Comment by Alexey104** [comment]
Confirm, thank you!
