### ISSUE TITLE
Password prompt on firefox startup (after system update)

### ISSUE THREAD

**Issue by max-ishere** [passff/passff#500]
## Environment

What am I supposed to put here?

### Versions
- Operating system: Manjaro Linux i3 minimal community edition
- Browser: Mozilla Firefox 94.0.1
- PassFF: Version 1.13; Last Updated October 30, 2021
- Host app: pass

Status line output: `[08:42:27] ls -> (0) no error message`

### Observations

- Output of `pass`: +Tmx>vJdu*e//ycO
- Your preferences
  - In PassFF: 
  - In the host app `passff.py`: 
```
COMMAND = "/usr/bin/pass"
COMMAND_ARGS = []
COMMAND_ENV = {
"TREE_CHARSET": "ISO-8859-1",
"PATH": "/home/mkr/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/home/mkr/.config/composer/vendor/bin"
}
CHARSET = "UTF-8"
```
Also I have recently updated firefox and that seems to break a lot of things: My homepage became manjaro.com After I chose that I want the new green theme it forgot to reenable dark mode and this prompt seems to appear on start up after the update.

- Messages in the web console: 

---

### Steps to reproduce the issue
1. Start firefox
2. Input password in prompt
3. Everything seems fine
4. If I cancel the prompt the extension wont work unless I restart it by disabling and re-enabling it,

### Actual behaviour

After I start firefox I get a prompt for my gpg key password and if I wont input it the extension gives me an error message that no key was found

### Expected behaviour

gpg key prompt should only appear when I am trying to fill in passwords or view passwords. And it was that way before.

**Comment by tuxor1337** [comment]
This sounds like a duplicat eof #429. Do you have a file called `.gpg` at the root of your password store directory? Then please delete it and restart Firefox.

**Comment by max-ishere** [comment]
That did fix it and also pass now outputs the entire tree and not some garbage like `+Tmx>vJdu*e//ycO`. And firefox also now works. Can yo explain please what the issue was with this file? Why does deleting it make the issue go away>

**Comment by tuxor1337** [comment]
As explained in #429, this is an upstream bug in `pass` that has already been fixed in https://lists.zx2c4.com/pipermail/password-store/2019-July/003692.html:

> Saving a password with an empty name could happen (by doing `pass insert "$passname"` for example) and would break `pass show` as it would show this passworld instead of listing them all. This behavior would break some third party integrations like passff.
