### ISSUE TITLE
Do not read all password database entries on startup

### ISSUE THREAD

**Issue by madduck** [passff/passff#501]
### Versions
- Operating system: Debian unstable
- Browser: Firefox 93
- PassFF: 1.13
- Host app: 

Status line output: `[20:31:00] grepMetaUrls -> (0) no error message`

### Steps to reproduce the issue
1. Start Firefox

### Actual behaviour
I have a couple hundred entries in the database, and they are encrypted to a Yubikey. Every time I start Firefox, the Yubikey just starts blinking for close to half an hour, as PassFF seems to iterate the entire database. I don't understand why it would need to do that, and I consider this a bit of a security problem too.

### Expected behaviour
Please do not do this. All you need is a list of database entries, and then decrypt the specific one the user asks you to decrypt.

**Comment by tuxor1337** [comment]
There is an optional feature to index all URL fields on startup (https://github.com/passff/passff/pull/402) which obviously requires to decrypt the whole database. This is optional, and disabled by default, so you must have activated it at some point in the preferences. It's noted in the preferences that this feature requires to decrypt the whole database.

**Comment by madduck** [comment]
Your correct @tuxor1337, although frankly, I have not touched the preferences in years. Maybe there was a time when this was turned on by default? Or a test build? Anyway, sorted, and sorry for the issue…
