### ISSUE TITLE
options to always "fill and submit" without asking me?

### ISSUE THREAD

**Issue by jpritikin** [passff/passff#508]
### Versions
- Operating system: Ubuntu 21.10
- Browser: Firefox
- PassFF: 1.13
- Host app: ?

### Actual behaviour
I have to select "fill and submit"

### Expected behaviour
Is there a preference setting so I can always "fill and submit" without being asked every time?

**Comment by tuxor1337** [comment]
In the preferences, you can select the action to take when pressing "enter" on one of the entries.

**Comment by jpritikin** [comment]
I tried adjusting the preferences. Maybe I'm missing something?

Check out https://www.youtube.com/watch?v=WD5O77RkeFc

At 4 seconds into the video, it shows 
![Screenshot from 2022-03-31 15-50-00](https://user-images.githubusercontent.com/2002771/161162183-c08d625b-c22a-4713-99f7-64f3b78c8219.png)

Is there any way to skip this screen and always choose "Fill and submit" ?

**Comment by tuxor1337** [comment]
As I said, you can use the keyboard to do just that. There is a shortcut to open the PassFF menu, with arrow-down you can navigate to the entry you'd like to select, and with enter you can execute the action you have set in the preferences.

Alternatively, if you insist on mouse navigation, you can use the icon menu in the login form. Click on the "P", then on the entry or on the icon next to it.

**Comment by jpritikin** [comment]
> with arrow-down you can navigate to the entry you'd like to select

Ah, that's the piece that I was missing. Happy now!

> Alternatively

Neat!
