### ISSUE TITLE
Auto-fill won't work if file is named login.gpg

### ISSUE THREAD

**Issue by aubertc** [passff/passff#513]
_I am making this bug report short as I don't think that the particular environment changes anything. I will adjust if required._

If I visit `login.com` (the `.com` domain is random) and try to have passff fills my `random/login.gpg`, then it
1. does not suggest it by default,
2. does not list it if I explicitly search for "login".

**Comment by tuxor1337** [comment]
This kind of structure is the "file-structure format" and will be interpreted differently by PassFF: https://github.com/passff/passff#file-structure-format So, this is not a bug, but a feature. If you want to change this, please clarify how you would like to change PassFF's current behavior without breaking other user's setups.

**Comment by aubertc** [comment]
Thanks for the answer. Yes, I use the file structure format, but my issue here is that the specific website `login` is not correctly recognized as an url and not displayed by passff.

**Comment by aubertc** [comment]
I think I didn't do a good job at explaining my issue. Maybe this video will do:

https://user-images.githubusercontent.com/16466689/181914829-a4a9c20a-f45d-4fd5-87e5-fc7066caf52d.mp4

**Comment by tuxor1337** [comment]
Why not call the file `login.gov.gpg` then?

**Comment by aubertc** [comment]
Ok, that works. Thanks.
