### ISSUE TITLE
PassFF failed to execute the host app in LibreWolf

### ISSUE THREAD

**Issue by nonogakhi** [passff/passff#517]
### Versions
- Operating system: Ubuntu 20.04
- Browser: LibreWolf V 105.0.1 Linux 86_64
- PassFF: 1.14
- Host app: passff-host 1.2.3

[05:51:13] ls -> (-1) PassFF failed to execute the host app

### Observations
- Output of `pass`: works fine
- Your preferences
  - In PassFF: -
  - In the host app `passff.py`: 
- Messages in the web console: it says fields were added
passff status line message:

> Connection to the host app failed or returned an unexpected result!

---

### Steps to reproduce the issue
1. Install passff-host
2. Install passff on firefox
3. Click on PassFF addon

### Actual behaviour
I get an error in when click on passff addon Icon.
Issue #506 had a similar problem but it was resolved.
I don't know what I'm missing

### Expected behaviour
I expect LibreWolf passff show correctly the dialog like in firefox.

**Comment by tuxor1337** [comment]
1. How did you install LibreWolf?
2. You write that you installed "passff on firefox", so how do you expect it to work in LibreWolf?
3. Make sure to install the host app using the keyword "librewolf" instead of "firefox".

**Comment by nonogakhi** [comment]
1. I installed LibreWolf through flatpak
2. I have Firefox and LibreWolf installed in parallel
3. That's the command I used

**Comment by tuxor1337** [comment]
For browsers installed via flatpak, the same applies as for browsers installed via snap, please continue here: https://github.com/passff/passff-host/issues/56
