### ISSUE TITLE
Error: / is not in the password store

### ISSUE THREAD

**Issue by rixx** [passff/passff#521]
### Versions
- Operating system: Arch Linux
- Browser: Firefox Nightly 109.0a1 (2022-11-15) (tested with 108 too)
- PassFF: 1.14, installed via addons.mozilla.org
- Host app: 1:1.2.3-1, installed via `pacman`

Status line output: `[09:21:28] ls -> (1) Error: / is not in the password store.`

### Observations
- Output of `pass`: pass output works as expected
- Your preferences
  - In PassFF: default preferences
  - In the host app `passff.py`: default preferences

Tried to make sure `passff-host` works as expected by running `echo -e "\x02\x00\x00\x00[]" | python /usr/share/passff/passff.py| tail -c +4; echo`:

```
{"exitCode": 0, "stdout": "\n|-- \u001b[01;34mAccounts\u001b[0m\n|   |-- \u001b[00mtestaccount\u001b[0m\n[REMOVED for privacy reasons]"stderr": "", "version": "1.2.3"}
```

### Steps to reproduce the issue

I installed passff-host via pacman, installed passff itself from addons.mozilla.org, and then tried to fill in passwords. I'm a long time pass user, so pass is working as expected.

I have the suspicion that passff is not picking up my `PASSWORD_STORE_DIR` for some reason, or is unhappy with my directory structure? `PASSWORD_STORE_DIR` is set, though, to `/home/rixx/.local/share/password-store`. Its directory structure looks like this:

```
├── Accounts
│   ├── account1.gpg
│   ├── account2.gpg
│   ├── account3.gpg
```

I'm sure there's something off configuration-wise, any help finding the problem would be appreciated.

**Comment by tuxor1337** [comment]
I have no clue. So, the list of your entries shows up correctly in the PassFF pop-up menu, but when you select some entry and select any "display" or "fill" action, it will do nothing?

**Comment by rixx** [comment]
No, the pop-up menu doesn't show anything, either. I cannot get any part of passff to work – the working part is calling the `passff.py` manually.

I'm running pass v1.7.4.

**Comment by tuxor1337** [comment]
Why do you think that this is related to not picking up the `PASSWORD_STORE_DIR` variable? If the variable is not set, pass should show the following output:
```sh
$ PASSWORD_STORE_DIR="" pass 
Error: password store is empty. Try "pass init".
```
I have no idea how you would willingly produce the output `/ is not in the password store`.

**Comment by drmoose** [comment]
@tuxor1337 I've run into this before. Passff says `/ is not in the password store` when `$PASSWORD_STORE_DIR` points to an extant, but empty, folder.

```
$ PASSWORD_STORE_DIR="$(mktemp -d)" pass
Password Store
```

Sadly I don't know how to solve @rixx problem for real, as I haven't been able to get environment variables to pass through Firefox either. My workaround was to just `ln -sT ~/.local/share/password-store ~/.password-store`.

**Comment by tuxor1337** [comment]
You can set environment variables in your `passff.py` host script. But this should only be a last resort. Usually, it's supposed to use the same environment where Firefox lives.

@drmoose I don't understand your comment about the `/ is not in the password store` output because it obviously isn't reproduced by the commandline that you quote.

**Comment by drmoose** [comment]
`/ is not in the password store` is an error message from passff, rather than pass. But it turns out I was wrong and it's "nonexistant folder" rather than "empty folder" (sorry; misremembered).

![image](https://user-images.githubusercontent.com/5732028/202202869-48c5c9b7-e4a0-4e53-a85d-caebede03f41.png)

I have no idea how to get this error message from `pass` itself. In this condition `pass` shows the "store is empty" error in your example.

**Comment by drmoose** [comment]
Aha: 

```
$ PASSWORD_STORE_DIR=/nowhere pass ls /
Error: / is not in the password store.
```

Sorry again about the bad info above.

**Comment by tuxor1337** [comment]
Okay, thanks for double-checking!

@rixx Then please try to manually set the correct `PASSWORD_STORE_DIR` in the `COMMAND_ENV` dict in your `passff.py` and see whether this will at least work around this issue.

**Comment by xeruf** [comment]
Please reopen this, as this issue has bugged me for months! An available workaround is not a fix. Thank  You :)

**Comment by xeruf** [comment]
I guess the fix should be added into https://github.com/passff/passff-host/blob/main/src/passff.py

**Comment by xeruf** [comment]
Interestingly enough, I only have this issue on Manjaro Sway (Wayland), not on my Arch+KDE machines...

**Comment by xeruf** [comment]
And don't forget to include `o+rx` rights on the PASSWORD_STORE_DIR - or is there a group I may use for more precise permissions?

**Comment by tuxor1337** [comment]
I don't think there is anything we can do on our side. If the PASSWORD_STORE_DIR environment variable isn't set or is set to a wrong value, there is no way that we can decide whether this is intentional or not. We already do the best we can by forwarding the pass error message.

**Comment by xeruf** [comment]
well, but is there no way to pass the PASSWORD_STORE_DIR from the environment on to the script automatically?

**Comment by tuxor1337** [comment]
If the variable is set (and to the right value) in the environment where the script is executed, then the script will work as intended. If the variable isn't set (or to the wrong value), then there is nothing that the script can do about it.

**Comment by nsailor** [comment]
Hi, I think I'm having the same issue. Modifying `passff.py` works.
Interestingly, I'm also running Sway on Arch, something strange is going on here.

**Comment by nsailor** [comment]
@xeruf After a bit of troubleshooting, I was able to figure out what was going on on my system.

I am using fish, and was setting the `PASSWORD_STORE_DIR` environment variable in my `.config/fish/config.fish` file. However, I was launching sway from a login manager (greetd), and therefore the environment variables where not available to sway.

As a result, when starting Firefox from a terminal passff worked fine, but when starting it with `sway exec firefox` I would get `/ is not in the password store`. The obvious fix is to set any needed environment variables in `~/.profile`.

No issue to fix with passff at all.

**Comment by tuxor1337** [comment]
@nsailor Thanks a lot for the investigation! :pray:
