### ISSUE TITLE
Mac OS Ventura

### ISSUE THREAD

**Issue by ChauhanT** [passff/passff#522]
## Environment
Mac OS Ventura
Firefox 107.0.1

### Versions
- Operating system: Mac OS Ventura
- Browser: Firefox 107.0.1
- PassFF: 1.14
- Host app: 1.2.3

Status line output: `[01:37:03] ls -> (-1)`
---

### Steps to reproduce the issue
1. Install passff in Firefox 107.0.1 on Mac OS Ventura.
2. Try to click the 'P' icon. Normally, this gives you a list of possible logins.
3. Instead get 'No entries matching this URL.'

### Actual behaviour
Despite installing the host app, and adjusting all parameters, it still refuses to pick up any passwords. I've been using passff on Debian for many years now and it has never failed me. Mac OS is very special...

### Expected behaviour
I should get a list of suggestions for each username/password field.

**Comment by tuxor1337** [comment]
Please continue here: https://github.com/passff/passff-host/issues/25
