### ISSUE TITLE
Extension icon is not visible with dark themes since Firefox 109+

### ISSUE THREAD

**Issue by Alexey104** [passff/passff#525]
- Operating system: ArchLinux
- Browser: Firefox 109.0.1 (64-bit)
- PassFF: 1.14
- Host app: 1.2.3

Status line output: [13:28:28] ls -> (0) no error message

I apologize for a duplicate, I have seen #499 and #479 and don't want to spam here, but those reports are from 2021, and my is newer. I didn't have issues with `passff` icon previously, but since Firefox 109.0 the icon used for dark themes is really hard to see (previously it used to be almost white and well-distinguishable):

![passff_light](https://user-images.githubusercontent.com/38672094/218306298-90a0dc45-4ae1-41cc-a38e-2cbf329d4b8d.png)
![passff2](https://user-images.githubusercontent.com/38672094/218306306-1418bf2d-5146-48e8-a2db-3c48730def88.png)
![passff](https://user-images.githubusercontent.com/38672094/218306304-0011ba1e-df78-4e49-bb64-b7bfb0209672.png)
![passff5](https://user-images.githubusercontent.com/38672094/218306788-42c28d60-cf13-48ca-a7a7-b052c13c7a06.png)

**Comment by tuxor1337** [comment]
Apparently more recent Firefox version ignore the theme icon entries in the manifes.json file that are for icon size 16 and only use size 32 entries instead. Fixed in 1.14.1

**Comment by Alexey104** [comment]
Thank you!
