### ISSUE TITLE
“Goto, fill and submit” does not work for me (goes to homepage instead)

### ISSUE THREAD

**Issue by OlivierNicole** [passff/passff#532]
### Versions
- Operating system: NixOS unstable
- Browser: Firefox 112.0.2
- PassFF: 1.14.1
- Host app: 1.2.3

Status line output:

`[16:27:34] show -> (0) no error message`

### Observations

- Messages in the web console: When I try to log in e.g. to https://zestedesavoir.com/membres/connexion/, I get only the console message `HTTPS-Only Mode: Upgrading insecure speculative TCP connection “http://zestedesavoir.com/” to use “https”.`.

---

### Steps to reproduce the issue

I don’t know.

### Actual behaviour

I have set the action of the Enter key to “Goto, fill and submit” (I believe it was the default). Instead of doing that, it redirects to the homepage of the website, for every site.

### Expected behaviour

It should fill the form and submit it.

**Comment by OlivierNicole** [comment]
There is no `url` entry. Does there need to be one?

**Comment by tuxor1337** [comment]
> There is no `url` entry. Does there need to be one?

There doesn't need to be an url entry, but if it's missing, the `Goto` part will use the entry's name to determine the URL and that might be the URL of the homepage or some other page that doesn't have the login form.

Anyways, thanks for clarifying and nice that you found the solution.
