### ISSUE TITLE
Handling groups of single-digit OTP fields

### ISSUE THREAD

**Issue by madduck** [passff/passff#533]
### Versions
- Operating system: Debian unstable
- Browser: Firefox 110
- PassFF: 1.0.4linux-295-g96fc733
- Host app: HEAD @ 91ae64fd5f639a0f5fd96281fa518b2147f48399

[09:19:32] otp -> (0) no error message

### Observations

Paypal, probably others, have split the OTP input field into six single digit fields. I wouldn't even know why, seems like such a waste of dev resources. Anyway, the result is that OTP filling no longer works. Here is what it looks like:

![image](https://github.com/passff/passff/assets/195073/6e3b971e-4c45-4b84-a9f0-7539b640a8be)

I can copy the OTP code and paste it, that works, but if I try to auto-fill using PassFF, then the result for a OTP code 086055 is this:

![image](https://github.com/passff/passff/assets/195073/185c8b00-2012-45b9-a791-d1a12089cc6a)

Not sure if this can be fixed other than more heuristics. Fact is there is no `maxlen==1` on the `<input>` field. But PassFF recognises it, presumably as OTP field?

So maybe, if PassFF finds a multiple of 6 OTP fields on a given page, it could go into single-digit mode?

PS: Curious if anyone knows what might have led Paypal to invest money into making the OTP entry more complicated.

**Comment by tuxor1337** [comment]
Fixed in aae6469

**Comment by madduck** [comment]
I can't wait to test this. Thank you!

**Comment by madduck** [comment]
It works like a charm, @tuxor1337. Thank you so much!
