### ISSUE TITLE
Show only domains that could plausibly match the site I'm viewing

### ISSUE THREAD

**Issue by bkazez** [passff/passff#535]
### Versions
- Operating system: macOS 13.4 (22F66)
- Browser: 114.0.2 (64-bit)
- PassFF: 1.14.1
- Host app: 

Status line output: [18:37:44] show -> (0) no error message

### Steps to reproduce the issue
1. Add items www/digitalocean.com and www/digital.mybank.com
2. Navigate to digital.mybank.com

### Actual behaviour
"Context" in passff shows both www/digitalocean.com and www/digital.mybank.com

### Expected behaviour
passff should match domains in reverse DNS order and therefore show only digital.mybank.com.

### Implications
This could create a situation where a user accidentally fills a bank password into an insecure site, just because the bank has "digital" as a subdomain and the insecure site includes that word in its domain name.

### Related
https://github.com/passff/passff/issues/519

**Comment by tuxor1337** [comment]
Thanks for the suggestion! An option to have a stricter entry matching based on the domain only sounds reasonable and I will be happy to look into PRs in that direction.

**Comment by bkazez** [comment]
For example, my Home Depot password isn't relevant when looking at Nest:
![Screenshot 2023-11-19 at 20 02 13](https://github.com/passff/passff/assets/64005/30ce92d1-e2aa-4d22-a677-ef390c7a7d79)

**Comment by bkazez** [comment]
This also comes up anytime a URL contains a common word. E.g. when viewing console.cloud.google.com, I get matches for soundcloud, cloud.elastic.co, matomo.cloud, etc. Same is true for URLs like online.somecorp.com - this also matches online.mybank.com and so on.

Related: https://github.com/passff/passff/issues/361

**Comment by bkazez** [comment]
Another common example: forum.example.com matches like 5 sites in pass.

**Comment by tuxor1337** [comment]
Actually, with the security checks in place, I don't see any disadvantage from making more suggestions to users. The current scheme allows to have useful matches when an entry is called `/path/to/example` and the user wants to use those credentials for `example.org`, `example.com` and `example.us`. If the user accidentally chooses the entry for `digital.mybank.com` while on `digitalocean.com` the security checks will prevent the filling. So, that's a non-issue for me.

**Comment by bkazez** [comment]
> I don't see any disadvantage from making more suggestions to users.

Seeing unnecessary information increases the cognitive load for users.  What is the use case for someone needing to see digitalocean.com when viewing digital.mybank.com?

**Comment by tuxor1337** [comment]
I did not say that there is a use case for seeing `digitalocean.com` when the user is on `digital.mybank.com`. The whole point of fuzzy matching is that you do not expect all of the suggestions to be useful, it's just narrowing down and ranking the available data. Since "pass" does not enforce a particular naming scheme for its entries, not all users include the URL in the entry name. Hence, enforcing the domain to be contained in the entry name will render the suggestions useless for many users.

**Comment by bkazez** [comment]
I see. You could have a preference checkbox?
