### ISSUE TITLE
After autofill, focus the password field

### ISSUE THREAD

**Issue by bkazez** [passff/passff#539]
### Versions
- Operating system: macOS 13.4 (22F66)
- Browser: FF 114.0.2 (64-bit)
- PassFF: 1.14.1

### Description
After autofill, it would be more efficient to be able to submit the form by pressing return/enter. Right now autofill doesn't leave any form fields focused. The most logical imo would be the password field, since that's the last thing in visual order.

**Comment by tuxor1337** [comment]
Unfortunately, we do not have this kind of control over the focus: https://github.com/passff/passff/issues/260

**Comment by bkazez** [comment]
BitWarden, 1Password, and LastPass do not have this issue. Maybe worth reopening and looking at how BW does it?On Jul 3, 2023, at 00:41, Thomas Vogt ***@***.***> wrote:﻿
Unfortunately, extensions do not have this kind of control over the focus: #260

**Comment by bkazez** [comment]
On second thought, perhaps it’s merely that in those other apps, the keyboard shortcut autofills without showing the extension interface at all. See #538.On Jul 3, 2023, at 00:41, Thomas Vogt ***@***.***> wrote:﻿
Unfortunately, extensions do not have this kind of control over the focus: #260
