### ISSUE TITLE
Set default keyboard shortcut to the same one as the most popular password manager

### ISSUE THREAD

**Issue by bkazez** [passff/passff#540]
### Versions
- Operating system: macOS 13.4 (22F66)
- Browser: FF 114.0.2 (64-bit)
- PassFF: 1.14.1

### Description
To help users transition from other password managers, use the (platform-specific) most popular password manager's shortcut as the default one for passff. Right now it's ctrl-Y, which is not just different from everything else but also feels weird on a Mac (everything uses command - command-shift-L for bitwarden, command-backslash for 1password).

**Comment by tuxor1337** [comment]
Thanks for the report! Ctrl-Y has a different meaning for many users, see #352 #388

**Comment by bkazez** [comment]
To be clear, I like being able to change the keyboard shortcut. I am just suggesting that the first (default) value be something different. On a Mac, control on its own is very nonstandard. As one of the commenters in those other tickets mentioned, command would make more sense but command-Y is a standard shortcut for redo (since the 90s). Copying whatever another password manager does would help users adopt passff more easily. On Jul 3, 2023, at 00:39, Thomas Vogt ***@***.***> wrote:﻿
Thanks for the report! Ctrl-Y has a different meaning for many users, see #352 #388
