### ISSUE TITLE
Do not display warning when pass is named with an IP address ± port

### ISSUE THREAD

**Issue by bkazez** [passff/passff#541]
### Versions
- Operating system: macOS 13.4 (22F66)
- Browser: FF 114.0.2 (64-bit)
- PassFF: 1.14.1

### Description
Right now if you add an item like 192.168.3.4:3000 to pass, and try to autofill, it displays a warning saying that "There was an error parsing the URL (...) from the password database." If the URL is a valid IP address ± port, do not show this warning.

**Comment by tuxor1337** [comment]
Thanks for the report!

Do you use the setting "Warn about potential phishing sites, such as when the domain listed in the database differs from that of the current page"? And did you set the "url" field inside the entry? Did you specify a protocol (e.g. https://)?

**Comment by bkazez** [comment]
> Warn about potential phishing sites
Yes.

> Did you specify a protocol (e.g. https://)?

No. I just added a protocol and now I get two warnings: first, that the domain doesn't match (which is not correct), and second, that the protocol is insecure.

**Comment by tuxor1337** [comment]
This will be fixed once #520 is merged (the PR will add options to customize this behavior).
