### ISSUE TITLE
Per-record field name for OTP field

### ISSUE THREAD

**Issue by madduck** [passff/passff#547]
A specific site I am using has a 2FA login using OTP. The ID of the input field is "loginkey", which is quite a misnomer. Instead of adding "loginkey" to the global preferences for OTP fields, I'd like to inform `pass` to fill the form field with an OTP key for this specific site.

Not sure this is a documented feature, but if I wanted to fill the field loginkey with a value, I could add

```
loginkey: something
```

to the password file for the site, and it'll fill the form field accordingly.

Since OTP doesn't have static values, this won't work, and instead, maybe a sentinel value needs to be used e.g.

```
loginkey: *otpauth*
```

or maybe conversely:

```
OTP field: loginkey
```

Is this something you might consider? I could take a stab at a PR of course, but would love input first before I spend too much time on this.

**Comment by tuxor1337** [comment]
It's a good idea to support entry-specific input names for certain fields. Implementation-wise this would be easiest like this:

```
AephieryZ2Ya
login: kevin
url: example.com
otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example
pin: 1234
loginkey: PASSFF_INPUT_OTP
fancyinput: PASSFF_INPUT_LOGIN
```

Then, if the user tells PassFF to fill the form, it would loop through the "other" fields like it's currently implemented:
https://github.com/passff/passff/blob/2f3fb4476cabe8715472ee5807607887d758dfc1/src/modules/page.js#L257-L261
But if it finds that the value `passwordData._other[matching]` is a certain keyword like `PASSFF_INPUT_LOGIN` it would fill the value stored in the login field, and if the value is the keyword `PASSFF_INPUT_OTP` it would fill the otp token that has just been generated (currently, an otp token is generated regardless of the existence of a matching input element on the current web page).

**Comment by madduck** [comment]
This looks great, and while my initial thought was to reuse YAML references, let's not overcomplicate things, especially since we're not using YAML.

The only thing I'll say is `s/INPUT/FIELD/` since we're not really talking input, but fields. But either way, this would be great to have, and I'll be the first to test.

**Comment by tuxor1337** [comment]
Either of INPUT or FIELD in the flag name is okay with me. The field name is both the name of a field and of an input. The flag then tells you that the corresponding "input" is actually to be used for a different purpose (like OTP or LOGIN), and it also tells you at the same time to use the value stored in a different "field" (like OTP or LOGIN).

**Comment by madduck** [comment]
Thank you!
