### ISSUE TITLE
Blank username gets ignored by passff, but is ok when listed from pass cli

### ISSUE THREAD

**Issue by ggets** [passff/passff#549]
### Versions
- Operating system: Windows 11 build 22621
- Browser: Firefox 117 beta
- PassFF: from mozilla extension store, config unchanged
- Host app: latest, unmodified

Status line output: [14:44:14] show -> (0) no error message

### Observations
Output from console:
```
> pass show https://test.com/Realm:\ Authenticate/000
Username: ""
Password: testpass
Realm: Authenticate

```

When displaying the info from the browser extension:
![image](https://github.com/passff/passff/assets/4815620/56f93be9-e1aa-4752-b10c-23c6d6393293)

---

### Actual behaviour
Username not parsed, because it's blank. Assumes username from .gpg file name.
Worth mentioning is, I tried `Username: `, `Username: ''` and `Username: ""` and still experienced the same behavior.

### Expected behaviour
Username field parsed and respectively sent as blank when authenticating

**Comment by tuxor1337** [comment]
From the README:
> If your login credentials do not include any login name information (only a password), you can instruct PassFF to omit filling any login name by adding login: PASSFF_OMIT_FIELD to your pass entry. The same keyword can be used for credentials without password, but only login name.

**Comment by ggets** [comment]
Excuse my asking, but is this not exactly the oppsosite case? I haven't set any variables, nor changed any default config. So, if understand this correctly, the empty field should be included, not ommitted, right?

**Comment by tuxor1337** [comment]
If you include `login: PASSFF_OMIT_FIELD` in your pass entry, PassFF will not attempt to fill any "username" input fields on the website. From your original post, I understand that this is what you want to achieve. If that's true, please include `login: PASSFF_OMIT_FIELD` in your pass entry and this issue should be solved.

**Comment by ggets** [comment]
Ok, now that I understand it correctly, I tested it and it works fine. Should this not be the default behaviour, though?

**Comment by tuxor1337** [comment]
In your case, it seems like the actual problem with your setup is that you don't put the password in the first line. The first line is **always** reserved for the password (see README, and see `-c` option for `pass`). If you have a field called "password" in one of the other lines, the value in the first line will be overwritten by that value.

**Comment by ggets** [comment]
Probably, but when testing I tried ommiting the line altogether, but it resulted the same behaviour.

**Comment by tuxor1337** [comment]
Yes, ommiting it will result in the entry's name being used as the username (see README).
