### ISSUE TITLE
It work with the terminal but not a shortcut in hyprland

### ISSUE THREAD

**Issue by WiredMic** [passff/passff#550]
### Versions
- Operating system: Arch Linux with hyprland on wayland
- Browser: firefox
- PassFF: 1.15
- Host app: 1.2.3

Status line output: `[01:11:48] ls -> (1) Error: / is not in the password store.`

### Observations

- Output of `pass`: 
- Your preferences
  - In PassFF: 
  - In the host app `passff.py`: 
- Messages in the web console: 
`Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). 2 [customElements.js:499:24](chrome://global/content/customElements.js)`
`Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). [panel.js:62:22](chrome://global/content/elements/panel.js)`

---

### Steps to reproduce the issue
1. open firefox thought hyprland or wofi on hyprland.
2. download the extension from firefox and the host from the github.
3. click on the icon and see it does not work.

### Actual behaviour

When I try to use passff through a firefox instance that has been open by ether wofi or a hyprland short cut it does not work. However, if i open firefox with the kitty terminal emulator it works.

The error it gives is:
```
Connection to the host app failed or returned an unexpected result!

Make sure you have the latest version of the PassFF host app installed by following the [official installation instructions](https://github.com/passff/passff#installation).
```

### Expected behaviour

The extension should work if I open firefox with wofi or a hyprland command.

**Comment by WiredMic** [comment]
I am not a web developer, so if anyone can help me it would be much appreciated.

**Comment by tuxor1337** [comment]
You might need to set the `PASSWORD_STORE_DIR` environment variable in the right places, as noted in: https://github.com/passff/passff/issues/521#issuecomment-1497992859 At first, try to set this variable in yout `$HOME/.profile`, and restart your system. If that doesn't work, set the variable directly in the `passff.py` script.

**Comment by WiredMic** [comment]
thank you that worked
