### ISSUE TITLE
Not working on bahn.de

### ISSUE THREAD

**Issue by spth** [passff/passff#553]
### Versions
- Operating system: Debian GNU/Linux testing
- Browser: Forefox 115.2.0esr (64-Bit)
- PassFF: 1.15

### Observations
bahn.de is the website of the German federal railway company. It is a very common way to buy train tickets in and from/to Germany.

---

### Steps to reproduce the issue
1. Got to bahn.de
2. Click "Login"

### Actual behaviour
The login dialog that opens up does not have the "P" for passff to fill in the username and password, despite me having a .password-store/bahn.de file

### Expected behaviour
The "P" appears to click on to ask for the GPG passphrase, and then fill in the username and password.

**Comment by tuxor1337** [comment]
Unfortunately, this type of input field is notoriously difficult to support because it has that "clear" button on the right. The "P" is underneath and fully or partly hidden by the "clear" button.

**Comment by tuxor1337** [comment]
Are you aware that you can right-click and use the "PassFF" submenu of the context menu?

**Comment by spth** [comment]
> Are you aware that you can right-click and use the "PassFF" submenu of the context menu?

Thanks. I wasn't ware of it, in the past I always opened a terminal window to invoke pass for bahn.de there, and copied the two lines into the browser.

**Comment by tuxor1337** [comment]
I think, they changed something on bahn.de which fixes this issue.
