### ISSUE TITLE
Hard to use on elster.de

### ISSUE THREAD

**Issue by spth** [passff/passff#554]
### Versions
- Operating system: Debian GNU/Linux testing
- Browser: Forefox 115.2.0esr (64-Bit)
- PassFF: 1.15

### Observations
elster.de is the German federal government website for filing tax declarations. This is thus a very important website for German residents.

### Steps to reproduce the issue
1. Go to elster.de
2. Click "Jetzt einloggen"

### Actual behaviour
In the "Passwort" field, the "P" is hidden behind an eye symbol; only a single column of grey pixels can be clicked to get to passff. When clicking that one (which is hard), passff works normally.

### Expected behaviour
The "P" should be fully visible and easy to click.

**Comment by tuxor1337** [comment]
I think, it's unrealistic for PassFF to work around all kinds of "clear" button overlays.
