### ISSUE TITLE
Hide PassFF in toolbar

### ISSUE THREAD

**Issue by rixx** [passff/passff#557]
### Versions
- Operating system: Linux
- Browser: Firefox

## Feature request

I trigger passff only with my keyboard – as such, it would be nice to not show the icon in the toolbar, as I never click on it, and it adds to general clutter. (And extension icons cannot currently be moved to the hidden overflow menu.)

Would it be possible to add a setting to hide the toolbar icon (and/or just move to the default extensions menu, where extensions usually live), while still making the keyboard-triggered context menu work? Not sure if that's within Firefox's capabilities, but if it is, I'd appreciate it a lot!

**Comment by tuxor1337** [comment]
Did you try right clicking on the toolbar icon and disabling the "Pin to toolbar" option? It works for me and it won't affect the shortcut menu.

**Comment by rixx** [comment]
ooh, I completely missed that that exists and only tried the overflow menu thing. Sorry for taking up your time with something like this!
