### ISSUE TITLE
Use the container name while matching

### ISSUE THREAD

**Issue by NicolaSmaniotto** [passff/passff#558]
For some websites I have multiple accounts, stored in different top level folders, something like:

```
a/example.com
b/example.com
```

Right now opening `example.com` the first result is the one in `a`, since they both match and the result are sorted alphabetically.

It would be useful to include the name of the current [container](https://github.com/mozilla/multi-account-containers/) in the search, so that opening `example.com` while inside container `b` would better match the second one.

**Comment by tuxor1337** [comment]
This would probably be implemented via the contextualIdentities API (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities).
