### ISSUE TITLE
Logo - proposed design

### ISSUE THREAD

**Issue by morciej** [passff/passff#560]
## Environment (pro forma)
Firefox 122.0 on Linux Mint 21.3 Virginia (base Ubuntu 22.04 Jammy)

### Versions (applies to)
- Operating system: All
- Browser: All
- PassFF: 1.16
- Host app: N/A

### Observations

- Output of `pass`: Logo could be better
- Your preferences : More Artsy :-)
---

### Steps to reproduce the issue
1. Install extension
2. Look
3. Sigh

### Actual behaviour

Logo is not the best

### Expected behaviour

Better logo

I actually designed a logo that I *think* is a bit better. Attached: PNG, SVG, SVG light version.

![icon](https://github.com/passff/passff/assets/17895139/4a1b7bbc-b051-452d-8577-cd642052076f)
![icon](https://github.com/passff/passff/assets/17895139/713d5a02-1405-45c7-b09e-b8cec29d2b15)
![icon-light](https://github.com/passff/passff/assets/17895139/9d1db017-ecbc-46f2-b4d6-33d15f7f5dfd)

I hope you can use it. No rights reserved - mention would be nice.

**Comment by tuxor1337** [comment]
Your efforts are very much appreciated!

However, for me personally, the current logo is actually fine. Let's see what other people say.

**Comment by morciej** [comment]
NP.
