### ISSUE TITLE
passff don't show passwords

### ISSUE THREAD

**Issue by torm84** [passff/passff#561]
### Versions
- Operating system: "NixOS 23.11 (Tapir)"
- Browser: firefox 122.0
- PassFF: 1.16
- Host app: 1.2.3

Status line output: `[20:46:26] ls -> (0) no error message`

### Observations
passff-host show correct information:

> echo -e "\x19\x00\x00\x00[\"otp\",\"/OpenVPN\"]" | /nix/store/a9r8pcxblvv9xqygfdxww2dhkbp1x5wv-passff-host-1.2.3/share/passff-host/passff.py | tail -c +4; echo
> {"exitCode": 0, "stdout": "954563\n", "stderr": "", "version": "1.2.3"}

### Steps to reproduce the issue
click on passff plugin

### Actual behaviour
passff extention in firefox browser show a blank window, without some passwords

### Expected behaviour
passff extention should show my passwords

**Comment by tuxor1337** [comment]
Might be a duplicate of https://github.com/passff/passff/issues/429. Do you have a file called .gpg at the root of your password store directory? Then please delete it and restart Firefox.

**Comment by torm84** [comment]
Wow, yes. After deleting .gpg the problem was solved. Thank you, i didn't find that thread.
