### ISSUE TITLE
Password selection dialog opens up in a new window

### ISSUE THREAD

**Issue by fkranhold** [passff/passff#563]
### Versions
- Operating system: Arch Linux, Kernel 6.8.7-arch1-1
- Browser: Firefox 125.0.1-1
- PassFF: 1.16
- Host app: 1:1.2.4-1

Status line output: `[18:41:49] ls -> (0) no error message`

### Observations

I use sway as a compositor. When opening an .htaccess-protected site, the password selection dialog of passff appears in a new window rather than in a corner of the existing firefox window (where it shows up if I click on the passff icon in the symbol bar). This new window is not marked as a ‘dialog’, and so it appears as a new ‘tile’, resizing the existing firefox window, see the screenshot. It would be great if, instead, the dialog shows up within the existing window.

![20240420_18h42m12s_grim](https://github.com/passff/passff/assets/45993364/370cf0e7-a252-4559-a761-78766df6388e)

### Steps to reproduce the issue
1. Use sway as a compositor.
2. Open an .htaccess-protected website.

**Comment by tuxor1337** [comment]
I don't think that there is anything that we can do about this since there is no way to create a modal dialog in the `browser.windows.create` API: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create

**Comment by tuxor1337** [comment]
Similar to #411, I don't think that there is anything we can do about this unless something changes upstream.

Feel free to reopen if you know a different extension which has a nice UI from which we could learn.
