### ISSUE TITLE
Disable auto-submit on logins through pass configuration

### ISSUE THREAD

**Issue by shioyama** [passff/passff#58]
Hey first off this is a great plugin, thanks for creating and maintaining it!

I have a feature request, which is to allow configuration in pass to tell passff not to auto-submit for a given login (site). I find myself frequently jumping to login to sites, a couple of which require human input or something special that passff cannot do automatically, so they always fail. I don't want passff to try to auto-submit the form on _just these sites_, but there seems to be no way to do that kind of configuration.

If you could put something like `AutoSubmit: false` in the pass file for those special sites, and have passff see that and not auto-submit, that would be great.

**Comment by nwallace** [comment]
Thanks for the suggestion. I agree, and I think we can use the work we're doing for #61 to support an option like this as well.

**Comment by shioyama** [comment]
Thanks!
